/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
	"fmt"
)

// EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn the model 'EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn'
type EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn string

// List of Enumfile-based-json-sync-failed-ops-log-publisherSchemaUrn
const (
	ENUMFILEBASEDJSONSYNCFAILEDOPSLOGPUBLISHERSCHEMAURN_URNPINGIDENTITYSCHEMASCONFIGURATION2_0LOG_PUBLISHERFILE_BASED_JSON_SYNC_FAILED_OPS EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn = "urn:pingidentity:schemas:configuration:2.0:log-publisher:file-based-json-sync-failed-ops"
)

// All allowed values of EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn enum
var AllowedEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnEnumValues = []EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn{
	"urn:pingidentity:schemas:configuration:2.0:log-publisher:file-based-json-sync-failed-ops",
}

func (v *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn(value)
	for _, existing := range AllowedEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn", value)
}

// NewEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnFromValue returns a pointer to a valid EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnFromValue(v string) (*EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn, error) {
	ev := EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn: valid values are %v", v, AllowedEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) IsValid() bool {
	for _, existing := range AllowedEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrnEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Enumfile-based-json-sync-failed-ops-log-publisherSchemaUrn value
func (v EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) Ptr() *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn {
	return &v
}

type NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn struct {
	value *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn
	isSet bool
}

func (v NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) Get() *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn {
	return v.value
}

func (v *NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) Set(val *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn(val *EnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) *NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn {
	return &NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn{value: val, isSet: true}
}

func (v NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumfileBasedJsonSyncFailedOpsLogPublisherSchemaUrn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
