/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
	"fmt"
)

// EnumexternalServerTransactionIsolationLevelProp This property specifies the default transaction isolation level for connections to this JDBC External Server.
type EnumexternalServerTransactionIsolationLevelProp string

// List of Enumexternal-server-transactionIsolationLevelProp
const (
	ENUMEXTERNALSERVERTRANSACTIONISOLATIONLEVELPROP_READ_COMMITTED   EnumexternalServerTransactionIsolationLevelProp = "read-committed"
	ENUMEXTERNALSERVERTRANSACTIONISOLATIONLEVELPROP_READ_UNCOMMITTED EnumexternalServerTransactionIsolationLevelProp = "read-uncommitted"
	ENUMEXTERNALSERVERTRANSACTIONISOLATIONLEVELPROP_REPEATABLE_READ  EnumexternalServerTransactionIsolationLevelProp = "repeatable-read"
	ENUMEXTERNALSERVERTRANSACTIONISOLATIONLEVELPROP_SERIALIZABLE     EnumexternalServerTransactionIsolationLevelProp = "serializable"
)

// All allowed values of EnumexternalServerTransactionIsolationLevelProp enum
var AllowedEnumexternalServerTransactionIsolationLevelPropEnumValues = []EnumexternalServerTransactionIsolationLevelProp{
	"read-committed",
	"read-uncommitted",
	"repeatable-read",
	"serializable",
}

func (v *EnumexternalServerTransactionIsolationLevelProp) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumexternalServerTransactionIsolationLevelProp(value)
	for _, existing := range AllowedEnumexternalServerTransactionIsolationLevelPropEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumexternalServerTransactionIsolationLevelProp", value)
}

// NewEnumexternalServerTransactionIsolationLevelPropFromValue returns a pointer to a valid EnumexternalServerTransactionIsolationLevelProp
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumexternalServerTransactionIsolationLevelPropFromValue(v string) (*EnumexternalServerTransactionIsolationLevelProp, error) {
	ev := EnumexternalServerTransactionIsolationLevelProp(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumexternalServerTransactionIsolationLevelProp: valid values are %v", v, AllowedEnumexternalServerTransactionIsolationLevelPropEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumexternalServerTransactionIsolationLevelProp) IsValid() bool {
	for _, existing := range AllowedEnumexternalServerTransactionIsolationLevelPropEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Enumexternal-server-transactionIsolationLevelProp value
func (v EnumexternalServerTransactionIsolationLevelProp) Ptr() *EnumexternalServerTransactionIsolationLevelProp {
	return &v
}

type NullableEnumexternalServerTransactionIsolationLevelProp struct {
	value *EnumexternalServerTransactionIsolationLevelProp
	isSet bool
}

func (v NullableEnumexternalServerTransactionIsolationLevelProp) Get() *EnumexternalServerTransactionIsolationLevelProp {
	return v.value
}

func (v *NullableEnumexternalServerTransactionIsolationLevelProp) Set(val *EnumexternalServerTransactionIsolationLevelProp) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumexternalServerTransactionIsolationLevelProp) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumexternalServerTransactionIsolationLevelProp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumexternalServerTransactionIsolationLevelProp(val *EnumexternalServerTransactionIsolationLevelProp) *NullableEnumexternalServerTransactionIsolationLevelProp {
	return &NullableEnumexternalServerTransactionIsolationLevelProp{value: val, isSet: true}
}

func (v NullableEnumexternalServerTransactionIsolationLevelProp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumexternalServerTransactionIsolationLevelProp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
