/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the InvertedStaticGroupReferentialIntegrityPluginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvertedStaticGroupReferentialIntegrityPluginResponse{}

// InvertedStaticGroupReferentialIntegrityPluginResponse struct for InvertedStaticGroupReferentialIntegrityPluginResponse
type InvertedStaticGroupReferentialIntegrityPluginResponse struct {
	Schemas []EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn `json:"schemas"`
	// Indicates whether the server should prevent updates to user entries that attempt to add them as a member of an inverted static group that does not exist.
	PreventAddingMembersToNonexistentGroups *bool `json:"preventAddingMembersToNonexistentGroups,omitempty"`
	// Indicates whether the server should prevent attempts to add a group as a regular member of an inverted static group. If the members of another group should be considered members of an inverted static group, then the other group should be added as a nested group rather than a regular member.
	PreventAddingGroupsAsInvertedStaticGroupMembers *bool `json:"preventAddingGroupsAsInvertedStaticGroupMembers,omitempty"`
	// Indicates whether the server should prevent updates to inverted static groups that add references to nested groups that don't exist.
	PreventNestingNonexistentGroups *bool `json:"preventNestingNonexistentGroups,omitempty"`
	// A description for this Plugin
	Description *string `json:"description,omitempty"`
	// Indicates whether the plug-in is enabled for use.
	Enabled bool `json:"enabled"`
	// Indicates whether the plug-in should be invoked for internal operations.
	InvokeForInternalOperations                   *bool                                              `json:"invokeForInternalOperations,omitempty"`
	Meta                                          *MetaMeta                                          `json:"meta,omitempty"`
	Urnpingidentityschemasconfigurationmessages20 *MetaUrnPingidentitySchemasConfigurationMessages20 `json:"urn:pingidentity:schemas:configuration:messages:2.0,omitempty"`
	// Name of the Plugin
	Id string `json:"id"`
}

// NewInvertedStaticGroupReferentialIntegrityPluginResponse instantiates a new InvertedStaticGroupReferentialIntegrityPluginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvertedStaticGroupReferentialIntegrityPluginResponse(schemas []EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn, enabled bool, id string) *InvertedStaticGroupReferentialIntegrityPluginResponse {
	this := InvertedStaticGroupReferentialIntegrityPluginResponse{}
	this.Schemas = schemas
	this.Enabled = enabled
	this.Id = id
	return &this
}

// NewInvertedStaticGroupReferentialIntegrityPluginResponseWithDefaults instantiates a new InvertedStaticGroupReferentialIntegrityPluginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvertedStaticGroupReferentialIntegrityPluginResponseWithDefaults() *InvertedStaticGroupReferentialIntegrityPluginResponse {
	this := InvertedStaticGroupReferentialIntegrityPluginResponse{}
	return &this
}

// GetSchemas returns the Schemas field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetSchemas() []EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn {
	if o == nil {
		var ret []EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetSchemasOk() ([]EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetSchemas(v []EnuminvertedStaticGroupReferentialIntegrityPluginSchemaUrn) {
	o.Schemas = v
}

// GetPreventAddingMembersToNonexistentGroups returns the PreventAddingMembersToNonexistentGroups field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventAddingMembersToNonexistentGroups() bool {
	if o == nil || IsNil(o.PreventAddingMembersToNonexistentGroups) {
		var ret bool
		return ret
	}
	return *o.PreventAddingMembersToNonexistentGroups
}

// GetPreventAddingMembersToNonexistentGroupsOk returns a tuple with the PreventAddingMembersToNonexistentGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventAddingMembersToNonexistentGroupsOk() (*bool, bool) {
	if o == nil || IsNil(o.PreventAddingMembersToNonexistentGroups) {
		return nil, false
	}
	return o.PreventAddingMembersToNonexistentGroups, true
}

// HasPreventAddingMembersToNonexistentGroups returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasPreventAddingMembersToNonexistentGroups() bool {
	if o != nil && !IsNil(o.PreventAddingMembersToNonexistentGroups) {
		return true
	}

	return false
}

// SetPreventAddingMembersToNonexistentGroups gets a reference to the given bool and assigns it to the PreventAddingMembersToNonexistentGroups field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetPreventAddingMembersToNonexistentGroups(v bool) {
	o.PreventAddingMembersToNonexistentGroups = &v
}

// GetPreventAddingGroupsAsInvertedStaticGroupMembers returns the PreventAddingGroupsAsInvertedStaticGroupMembers field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventAddingGroupsAsInvertedStaticGroupMembers() bool {
	if o == nil || IsNil(o.PreventAddingGroupsAsInvertedStaticGroupMembers) {
		var ret bool
		return ret
	}
	return *o.PreventAddingGroupsAsInvertedStaticGroupMembers
}

// GetPreventAddingGroupsAsInvertedStaticGroupMembersOk returns a tuple with the PreventAddingGroupsAsInvertedStaticGroupMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventAddingGroupsAsInvertedStaticGroupMembersOk() (*bool, bool) {
	if o == nil || IsNil(o.PreventAddingGroupsAsInvertedStaticGroupMembers) {
		return nil, false
	}
	return o.PreventAddingGroupsAsInvertedStaticGroupMembers, true
}

// HasPreventAddingGroupsAsInvertedStaticGroupMembers returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasPreventAddingGroupsAsInvertedStaticGroupMembers() bool {
	if o != nil && !IsNil(o.PreventAddingGroupsAsInvertedStaticGroupMembers) {
		return true
	}

	return false
}

// SetPreventAddingGroupsAsInvertedStaticGroupMembers gets a reference to the given bool and assigns it to the PreventAddingGroupsAsInvertedStaticGroupMembers field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetPreventAddingGroupsAsInvertedStaticGroupMembers(v bool) {
	o.PreventAddingGroupsAsInvertedStaticGroupMembers = &v
}

// GetPreventNestingNonexistentGroups returns the PreventNestingNonexistentGroups field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventNestingNonexistentGroups() bool {
	if o == nil || IsNil(o.PreventNestingNonexistentGroups) {
		var ret bool
		return ret
	}
	return *o.PreventNestingNonexistentGroups
}

// GetPreventNestingNonexistentGroupsOk returns a tuple with the PreventNestingNonexistentGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetPreventNestingNonexistentGroupsOk() (*bool, bool) {
	if o == nil || IsNil(o.PreventNestingNonexistentGroups) {
		return nil, false
	}
	return o.PreventNestingNonexistentGroups, true
}

// HasPreventNestingNonexistentGroups returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasPreventNestingNonexistentGroups() bool {
	if o != nil && !IsNil(o.PreventNestingNonexistentGroups) {
		return true
	}

	return false
}

// SetPreventNestingNonexistentGroups gets a reference to the given bool and assigns it to the PreventNestingNonexistentGroups field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetPreventNestingNonexistentGroups(v bool) {
	o.PreventNestingNonexistentGroups = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetInvokeForInternalOperations returns the InvokeForInternalOperations field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetInvokeForInternalOperations() bool {
	if o == nil || IsNil(o.InvokeForInternalOperations) {
		var ret bool
		return ret
	}
	return *o.InvokeForInternalOperations
}

// GetInvokeForInternalOperationsOk returns a tuple with the InvokeForInternalOperations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetInvokeForInternalOperationsOk() (*bool, bool) {
	if o == nil || IsNil(o.InvokeForInternalOperations) {
		return nil, false
	}
	return o.InvokeForInternalOperations, true
}

// HasInvokeForInternalOperations returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasInvokeForInternalOperations() bool {
	if o != nil && !IsNil(o.InvokeForInternalOperations) {
		return true
	}

	return false
}

// SetInvokeForInternalOperations gets a reference to the given bool and assigns it to the InvokeForInternalOperations field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetInvokeForInternalOperations(v bool) {
	o.InvokeForInternalOperations = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetMeta() MetaMeta {
	if o == nil || IsNil(o.Meta) {
		var ret MetaMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetMetaOk() (*MetaMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaMeta and assigns it to the Meta field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetMeta(v MetaMeta) {
	o.Meta = &v
}

// GetUrnpingidentityschemasconfigurationmessages20 returns the Urnpingidentityschemasconfigurationmessages20 field value if set, zero value otherwise.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetUrnpingidentityschemasconfigurationmessages20() MetaUrnPingidentitySchemasConfigurationMessages20 {
	if o == nil || IsNil(o.Urnpingidentityschemasconfigurationmessages20) {
		var ret MetaUrnPingidentitySchemasConfigurationMessages20
		return ret
	}
	return *o.Urnpingidentityschemasconfigurationmessages20
}

// GetUrnpingidentityschemasconfigurationmessages20Ok returns a tuple with the Urnpingidentityschemasconfigurationmessages20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetUrnpingidentityschemasconfigurationmessages20Ok() (*MetaUrnPingidentitySchemasConfigurationMessages20, bool) {
	if o == nil || IsNil(o.Urnpingidentityschemasconfigurationmessages20) {
		return nil, false
	}
	return o.Urnpingidentityschemasconfigurationmessages20, true
}

// HasUrnpingidentityschemasconfigurationmessages20 returns a boolean if a field has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) HasUrnpingidentityschemasconfigurationmessages20() bool {
	if o != nil && !IsNil(o.Urnpingidentityschemasconfigurationmessages20) {
		return true
	}

	return false
}

// SetUrnpingidentityschemasconfigurationmessages20 gets a reference to the given MetaUrnPingidentitySchemasConfigurationMessages20 and assigns it to the Urnpingidentityschemasconfigurationmessages20 field.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetUrnpingidentityschemasconfigurationmessages20(v MetaUrnPingidentitySchemasConfigurationMessages20) {
	o.Urnpingidentityschemasconfigurationmessages20 = &v
}

// GetId returns the Id field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InvertedStaticGroupReferentialIntegrityPluginResponse) SetId(v string) {
	o.Id = v
}

func (o InvertedStaticGroupReferentialIntegrityPluginResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvertedStaticGroupReferentialIntegrityPluginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	if !IsNil(o.PreventAddingMembersToNonexistentGroups) {
		toSerialize["preventAddingMembersToNonexistentGroups"] = o.PreventAddingMembersToNonexistentGroups
	}
	if !IsNil(o.PreventAddingGroupsAsInvertedStaticGroupMembers) {
		toSerialize["preventAddingGroupsAsInvertedStaticGroupMembers"] = o.PreventAddingGroupsAsInvertedStaticGroupMembers
	}
	if !IsNil(o.PreventNestingNonexistentGroups) {
		toSerialize["preventNestingNonexistentGroups"] = o.PreventNestingNonexistentGroups
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.InvokeForInternalOperations) {
		toSerialize["invokeForInternalOperations"] = o.InvokeForInternalOperations
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Urnpingidentityschemasconfigurationmessages20) {
		toSerialize["urn:pingidentity:schemas:configuration:messages:2.0"] = o.Urnpingidentityschemasconfigurationmessages20
	}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableInvertedStaticGroupReferentialIntegrityPluginResponse struct {
	value *InvertedStaticGroupReferentialIntegrityPluginResponse
	isSet bool
}

func (v NullableInvertedStaticGroupReferentialIntegrityPluginResponse) Get() *InvertedStaticGroupReferentialIntegrityPluginResponse {
	return v.value
}

func (v *NullableInvertedStaticGroupReferentialIntegrityPluginResponse) Set(val *InvertedStaticGroupReferentialIntegrityPluginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInvertedStaticGroupReferentialIntegrityPluginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInvertedStaticGroupReferentialIntegrityPluginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvertedStaticGroupReferentialIntegrityPluginResponse(val *InvertedStaticGroupReferentialIntegrityPluginResponse) *NullableInvertedStaticGroupReferentialIntegrityPluginResponse {
	return &NullableInvertedStaticGroupReferentialIntegrityPluginResponse{value: val, isSet: true}
}

func (v NullableInvertedStaticGroupReferentialIntegrityPluginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvertedStaticGroupReferentialIntegrityPluginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
