openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Alarm Manager config object
  title: PingData Alarm Manager Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access the Alarm Manager
  name: alarm-manager
paths:
  /alarm-manager:
    get:
      summary: Returns a single Alarm Manager
      operationId: get-alarm-manager
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alarm-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Alarm Manager does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Alarm Manager by name
      operationId: update-alarm-manager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-alarm-manager-request'
        description: Update an existing Alarm Manager
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alarm-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Alarm Manager does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    alarm-manager-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumalarm-managerSchemaUrn'
        defaultGaugeAlertLevel:
          $ref: '#/components/schemas/EnumdefaultGaugeAlertLevelProp'
        generatedAlertTypes:
          type: array
          items:
            $ref: '#/components/schemas/EnumgeneratedAlertTypesProp'
        suppressedAlarm:
          type: array
          items:
            $ref: '#/components/schemas/EnumsuppressedAlarmProp'
      required:
      - defaultGaugeAlertLevel
      - generatedAlertTypes
    Enumalarm-managerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:alarm-manager"
    update-alarm-manager-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumgeneratedAlertTypesProp:
      type: string
      enum:
      - "standard"
      - "alarm"
      description: Indicates what kind of alert types should be generated.
    EnumdefaultGaugeAlertLevelProp:
      type: string
      enum:
      - "always"
      - "warning-and-above"
      - "minor-and-above"
      - "major-and-above"
      - "critical-only"
      - "never"
      description: Specifies the level at which alerts are sent for alarms raised by the Alarm Manager.
    EnumsuppressedAlarmProp:
      type: string
      enum:
      - "no-enabled-alert-handlers"
      - "pdp-unavailable"
      description: Specifies the names of the alarm alert types that should be suppressed. If the condition that triggers an alarm in this list occurs, then the alarm will not be raised and no alerts will be generated. Only a subset of alarms can be suppressed in this way. Alarms triggered by a gauge can be disabled by disabling the gauge.
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
