openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Alarm Manager config object
  title: PingData Alarm Manager Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-91/pd_ds_use_config_api
tags:
- description: Access the Alarm Manager
  name: alarm-manager
paths:
  /alarm-manager:
    get:
      summary: Returns a single Alarm Manager
      operationId: get-alarm-manager
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alarm-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Alarm Manager does not exist
      security:
      - basicAuth: []
      tags:
      - alarm-manager
    patch:
      summary: Update an existing Alarm Manager by name
      operationId: update-alarm-manager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Alarm Manager
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alarm-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Alarm Manager does not exist
      security:
      - basicAuth: []
      tags:
      - alarm-manager
components:
  schemas:
    Enumalarm-manager-defaultGaugeAlertLevelProp:
      type: string
      enum:
      - "always"
      - "warning-and-above"
      - "minor-and-above"
      - "major-and-above"
      - "critical-only"
      - "never"
      description: >-
          Specifies the level at which alerts are sent for alarms raised by the Alarm Manager.
    Enumalarm-manager-generatedAlertTypesProp:
      type: string
      enum:
      - "standard"
      - "alarm"
      description: >-
          Indicates what kind of alert types should be generated.
    Enumalarm-manager-suppressedAlarmProp:
      type: string
      enum:
      - "no-enabled-alert-handlers"
      - "pdp-unavailable"
      description: >-
          Specifies the names of the alarm alert types that should be suppressed. If the condition that triggers an alarm in this list occurs, then the alarm will not be raised and no alerts will be generated. Only a subset of alarms can be suppressed in this way. Alarms triggered by a gauge can be disabled by disabling the gauge.
    alarm-manager-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumalarm-managerSchemaUrn'
          defaultGaugeAlertLevel:
            $ref: '#/components/schemas/Enumalarm-manager-defaultGaugeAlertLevelProp'
          generatedAlertTypes:
            type: array
            items:
              $ref: '#/components/schemas/Enumalarm-manager-generatedAlertTypesProp'
          suppressedAlarm:
            type: array
            items:
              $ref: '#/components/schemas/Enumalarm-manager-suppressedAlarmProp'
      - $ref: '#/components/schemas/meta'
      required:
      - defaultGaugeAlertLevel
      - generatedAlertTypes
    Enumalarm-managerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:alarm-manager"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
