openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Azure Authentication Method config object
  title: PingData Azure Authentication Method Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access azure-authentication-methods
  name: azure-authentication-method
paths:
  /azure-authentication-methods:
    post:
      summary: Add a new Azure Authentication Method to the config
      operationId: add-azure-authentication-method
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-default-request'
              - $ref: '#/components/schemas/add-client-secret-request'
              - $ref: '#/components/schemas/add-username-password-request'
        description: Create a new Azure Authentication Method in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/client-secret-response'
                - $ref: '#/components/schemas/username-password-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Azure Authentication Method already exists
      security:
      - basicAuth: []
      tags:
      - location
  /azure-authentication-methods/{azure-authentication-method-name}:
    delete:
      summary: Delete a Azure Authentication Method
      operationId: delete-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method to be deleted
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Azure Authentication Method does not exist
        "409":
          description: The Azure Authentication Method cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Azure Authentication Method
      operationId: get-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method to be read
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/client-secret-response'
                - $ref: '#/components/schemas/username-password-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Azure Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Azure Authentication Method by name
      operationId: update-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method to be updated
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-azure-authentication-method-request'
        description: Update an existing Azure Authentication Method
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/client-secret-response'
                - $ref: '#/components/schemas/username-password-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Azure Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    add-default-request:
      allOf:
      - type: object
        properties:
          methodName:
            description: Name of the new Azure Authentication Method
            type: string
        required:
        - methodName
      - $ref: '#/components/schemas/default-shared'
    default-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Azure Authentication Method
            type: string
        required:
        - id
      - $ref: '#/components/schemas/default-shared'
    default-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumdefaultSchemaUrn'
        tenantID:
          type: string
          description: The tenant ID to use to authenticate. If this is not provided, then it will be obtained from the AZURE_TENANT_ID environment variable.
        clientID:
          type: string
          description: The client ID to use to authenticate. If this is not provided, then it will be obtained from the AZURE_CLIENT_ID
        description:
          type: string
          description: A description for this Azure Authentication Method
      required:
      - schemas
    EnumdefaultSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:default"
    add-client-secret-request:
      allOf:
      - type: object
        properties:
          methodName:
            description: Name of the new Azure Authentication Method
            type: string
        required:
        - methodName
      - $ref: '#/components/schemas/client-secret-shared'
    client-secret-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Azure Authentication Method
            type: string
        required:
        - id
      - $ref: '#/components/schemas/client-secret-shared'
    client-secret-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumclient-secretSchemaUrn'
        tenantID:
          type: string
          description: The tenant ID to use to authenticate.
        clientID:
          type: string
          description: The client ID to use to authenticate.
        clientSecret:
          type: string
          format: password
          description: The client secret to use to authenticate.
        description:
          type: string
          description: A description for this Azure Authentication Method
      required:
      - schemas
      - tenantID
      - clientID
      - clientSecret
    Enumclient-secretSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:client-secret"
    add-username-password-request:
      allOf:
      - type: object
        properties:
          methodName:
            description: Name of the new Azure Authentication Method
            type: string
        required:
        - methodName
      - $ref: '#/components/schemas/username-password-shared'
    username-password-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Azure Authentication Method
            type: string
        required:
        - id
      - $ref: '#/components/schemas/username-password-shared'
    username-password-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumusername-passwordSchemaUrn'
        tenantID:
          type: string
          description: The tenant ID to use to authenticate.
        clientID:
          type: string
          description: The client ID to use to authenticate.
        username:
          type: string
          description: The username for the user to authenticate.
        password:
          type: string
          format: password
          description: The password for the user to authenticate.
        description:
          type: string
          description: A description for this Azure Authentication Method
      required:
      - schemas
      - tenantID
      - clientID
      - username
      - password
    Enumusername-passwordSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:username-password"
    update-azure-authentication-method-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
