openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Azure Authentication Method config object
  title: PingData Azure Authentication Method Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
tags:
- description: Access azure-authentication-methods
  name: azure-authentication-method
paths:
  /azure-authentication-methods:
    post:
      summary: Add a new Azure Authentication Method to the config
      operationId: add-azure-authentication-method
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-default-azure-authentication-method-request'
              - $ref: '#/components/schemas/add-client-secret-azure-authentication-method-request'
              - $ref: '#/components/schemas/add-username-password-azure-authentication-method-request'
        description: Create a new Azure Authentication Method in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-azure-authentication-method-response'
                - $ref: '#/components/schemas/client-secret-azure-authentication-method-response'
                - $ref: '#/components/schemas/username-password-azure-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Azure Authentication Method already exists
      security:
      - basicAuth: []
      tags:
      - azure-authentication-method
  /azure-authentication-methods/{azure-authentication-method-name}:
    delete:
      summary: Delete a Azure Authentication Method
      operationId: delete-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Azure Authentication Method does not exist
        "409":
          description: The Azure Authentication Method cannot be deleted
      security:
      - basicAuth: []
      tags:
      - azure-authentication-method
    get:
      summary: Returns a single Azure Authentication Method
      operationId: get-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-azure-authentication-method-response'
                - $ref: '#/components/schemas/client-secret-azure-authentication-method-response'
                - $ref: '#/components/schemas/username-password-azure-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Azure Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - azure-authentication-method
    patch:
      summary: Update an existing Azure Authentication Method by name
      operationId: update-azure-authentication-method
      parameters:
      - description: Name of the Azure Authentication Method
        explode: false
        in: path
        name: azure-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Azure Authentication Method
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-azure-authentication-method-response'
                - $ref: '#/components/schemas/client-secret-azure-authentication-method-response'
                - $ref: '#/components/schemas/username-password-azure-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Azure Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - azure-authentication-method
components:
  schemas:
    add-default-azure-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Azure Authentication Method
      - $ref: '#/components/schemas/default-azure-authentication-method-shared'
      required:
      - methodName
    default-azure-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Azure Authentication Method
      - $ref: '#/components/schemas/default-azure-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    default-azure-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumdefault-azure-authentication-methodSchemaUrn'
        tenantID:
          type: string
          description: >-
              The tenant ID to use to authenticate. If this is not provided, then it will be obtained from the AZURE_TENANT_ID environment variable.
        clientID:
          type: string
          description: >-
              The client ID to use to authenticate. If this is not provided, then it will be obtained from the AZURE_CLIENT_ID
        description:
          type: string
          description: >-
              A description for this Azure Authentication Method
      required:
      - schemas
    Enumdefault-azure-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:default"
    add-client-secret-azure-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Azure Authentication Method
      - $ref: '#/components/schemas/client-secret-azure-authentication-method-shared'
      required:
      - methodName
    client-secret-azure-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Azure Authentication Method
      - $ref: '#/components/schemas/client-secret-azure-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    client-secret-azure-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumclient-secret-azure-authentication-methodSchemaUrn'
        tenantID:
          type: string
          description: >-
              The tenant ID to use to authenticate.
        clientID:
          type: string
          description: >-
              The client ID to use to authenticate.
        clientSecret:
          type: string
          format: password
          description: >-
              The client secret to use to authenticate.
        description:
          type: string
          description: >-
              A description for this Azure Authentication Method
      required:
      - schemas
      - tenantID
      - clientID
      - clientSecret
    Enumclient-secret-azure-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:client-secret"
    add-username-password-azure-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Azure Authentication Method
      - $ref: '#/components/schemas/username-password-azure-authentication-method-shared'
      required:
      - methodName
    username-password-azure-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Azure Authentication Method
      - $ref: '#/components/schemas/username-password-azure-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    username-password-azure-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumusername-password-azure-authentication-methodSchemaUrn'
        tenantID:
          type: string
          description: >-
              The tenant ID to use to authenticate.
        clientID:
          type: string
          description: >-
              The client ID to use to authenticate.
        username:
          type: string
          description: >-
              The username for the user to authenticate.
        password:
          type: string
          format: password
          description: >-
              The password for the user to authenticate.
        description:
          type: string
          description: >-
              A description for this Azure Authentication Method
      required:
      - schemas
      - tenantID
      - clientID
      - username
      - password
    Enumusername-password-azure-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:azure-authentication-method:username-password"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
