openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Certificate Mapper config object
  title: PingData Certificate Mapper Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access certificate-mappers
  name: certificate-mapper
paths:
  /certificate-mappers:
    post:
      summary: Add a new Certificate Mapper to the config
      operationId: add-certificate-mapper
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-subject-equals-dn-certificate-mapper-request'
              - $ref: '#/components/schemas/add-subject-dn-to-user-attribute-certificate-mapper-request'
              - $ref: '#/components/schemas/add-groovy-scripted-certificate-mapper-request'
              - $ref: '#/components/schemas/add-subject-attribute-to-user-attribute-certificate-mapper-request'
              - $ref: '#/components/schemas/add-fingerprint-certificate-mapper-request'
              - $ref: '#/components/schemas/add-third-party-certificate-mapper-request'
        description: Create a new Certificate Mapper in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/subject-equals-dn-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-dn-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-attribute-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/fingerprint-certificate-mapper-response'
                - $ref: '#/components/schemas/third-party-certificate-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Certificate Mapper already exists
      security:
      - basicAuth: []
      tags:
      - certificate-mapper
  /certificate-mappers/{certificate-mapper-name}:
    delete:
      summary: Delete a Certificate Mapper
      operationId: delete-certificate-mapper
      parameters:
      - description: Name of the Certificate Mapper
        explode: false
        in: path
        name: certificate-mapper-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Certificate Mapper does not exist
        "409":
          description: The Certificate Mapper cannot be deleted
      security:
      - basicAuth: []
      tags:
      - certificate-mapper
    get:
      summary: Returns a single Certificate Mapper
      operationId: get-certificate-mapper
      parameters:
      - description: Name of the Certificate Mapper
        explode: false
        in: path
        name: certificate-mapper-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/subject-equals-dn-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-dn-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-attribute-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/fingerprint-certificate-mapper-response'
                - $ref: '#/components/schemas/third-party-certificate-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Certificate Mapper does not exist
      security:
      - basicAuth: []
      tags:
      - certificate-mapper
    patch:
      summary: Update an existing Certificate Mapper by name
      operationId: update-certificate-mapper
      parameters:
      - description: Name of the Certificate Mapper
        explode: false
        in: path
        name: certificate-mapper-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Certificate Mapper
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/subject-equals-dn-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-dn-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-certificate-mapper-response'
                - $ref: '#/components/schemas/subject-attribute-to-user-attribute-certificate-mapper-response'
                - $ref: '#/components/schemas/fingerprint-certificate-mapper-response'
                - $ref: '#/components/schemas/third-party-certificate-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Certificate Mapper does not exist
      security:
      - basicAuth: []
      tags:
      - certificate-mapper
components:
  schemas:
    add-subject-equals-dn-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/subject-equals-dn-certificate-mapper-shared'
    subject-equals-dn-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/subject-equals-dn-certificate-mapper-shared'
    subject-equals-dn-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsubject-equals-dn-certificate-mapperSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - enabled
    Enumsubject-equals-dn-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:subject-equals-dn"
    add-subject-dn-to-user-attribute-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/subject-dn-to-user-attribute-certificate-mapper-shared'
    subject-dn-to-user-attribute-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/subject-dn-to-user-attribute-certificate-mapper-shared'
      required:
      - subjectAttribute
    subject-dn-to-user-attribute-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsubject-dn-to-user-attribute-certificate-mapperSchemaUrn'
        subjectAttribute:
          type: string
          description: >-
              Specifies the name or OID of the attribute whose value should exactly match the certificate subject DN.
        userBaseDN:
          type: array
          items:
            type: string
          description: >-
              Specifies the base DNs that should be used when performing searches to map the client certificate to a user entry.
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - enabled
    Enumsubject-dn-to-user-attribute-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:subject-dn-to-user-attribute"
    add-groovy-scripted-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/groovy-scripted-certificate-mapper-shared'
    groovy-scripted-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/groovy-scripted-certificate-mapper-shared'
    groovy-scripted-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scripted-certificate-mapperSchemaUrn'
        scriptClass:
          type: string
          description: >-
              The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted Certificate Mapper.
        scriptArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Scripted Certificate Mapper. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - scriptClass
      - enabled
    Enumgroovy-scripted-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:groovy-scripted"
    add-subject-attribute-to-user-attribute-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/subject-attribute-to-user-attribute-certificate-mapper-shared'
    subject-attribute-to-user-attribute-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/subject-attribute-to-user-attribute-certificate-mapper-shared'
    subject-attribute-to-user-attribute-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsubject-attribute-to-user-attribute-certificate-mapperSchemaUrn'
        subjectAttributeMapping:
          type: array
          items:
            type: string
          description: >-
              Specifies a mapping between certificate attributes and user attributes.
        userBaseDN:
          type: array
          items:
            type: string
          description: >-
              Specifies the base DNs that should be used when performing searches to map the client certificate to a user entry.
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - subjectAttributeMapping
      - enabled
    Enumsubject-attribute-to-user-attribute-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:subject-attribute-to-user-attribute"
    add-fingerprint-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/fingerprint-certificate-mapper-shared'
    fingerprint-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/fingerprint-certificate-mapper-shared'
      required:
      - fingerprintAttribute
    fingerprint-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumfingerprint-certificate-mapperSchemaUrn'
        fingerprintAttribute:
          type: string
          description: >-
              Specifies the attribute in which to look for the fingerprint.
        fingerprintAlgorithm:
          $ref: '#/components/schemas/Enumcertificate-mapper-fingerprintAlgorithmProp'
        userBaseDN:
          type: array
          items:
            type: string
          description: >-
              Specifies the set of base DNs below which to search for users.
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - fingerprintAlgorithm
      - enabled
    Enumfingerprint-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:fingerprint"
    add-third-party-certificate-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            description: Name of the new Certificate Mapper
            type: string
        required:
        - mapperName
      - $ref: '#/components/schemas/third-party-certificate-mapper-shared'
    third-party-certificate-mapper-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Certificate Mapper
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-certificate-mapper-shared'
    third-party-certificate-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-certificate-mapperSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Certificate Mapper.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Certificate Mapper. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Certificate Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Certificate Mapper is enabled.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-party-certificate-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:certificate-mapper:third-party"
    Enumcertificate-mapper-fingerprintAlgorithmProp:
      type: string
      enum:
      - "md5"
      - "sha1"
      - "sha256"
      description: >-
          Specifies the name of the digest algorithm to compute the fingerprint of client certificates.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
