openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Conjur Authentication Method config object
  title: PingData Conjur Authentication Method Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
tags:
- description: Access conjur-authentication-methods
  name: conjur-authentication-method
paths:
  /conjur-authentication-methods:
    post:
      summary: Add a new Conjur Authentication Method to the config
      operationId: add-conjur-authentication-method
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-api-key-conjur-authentication-method-request'
        description: Create a new Conjur Authentication Method in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-key-conjur-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Conjur Authentication Method already exists
      security:
      - basicAuth: []
      tags:
      - conjur-authentication-method
  /conjur-authentication-methods/{conjur-authentication-method-name}:
    delete:
      summary: Delete a Conjur Authentication Method
      operationId: delete-conjur-authentication-method
      parameters:
      - description: Name of the Conjur Authentication Method
        explode: false
        in: path
        name: conjur-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Conjur Authentication Method does not exist
        "409":
          description: The Conjur Authentication Method cannot be deleted
      security:
      - basicAuth: []
      tags:
      - conjur-authentication-method
    get:
      summary: Returns a single Conjur Authentication Method
      operationId: get-conjur-authentication-method
      parameters:
      - description: Name of the Conjur Authentication Method
        explode: false
        in: path
        name: conjur-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-key-conjur-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Conjur Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - conjur-authentication-method
    patch:
      summary: Update an existing Conjur Authentication Method by name
      operationId: update-conjur-authentication-method
      parameters:
      - description: Name of the Conjur Authentication Method
        explode: false
        in: path
        name: conjur-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Conjur Authentication Method
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-key-conjur-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Conjur Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - conjur-authentication-method
components:
  schemas:
    add-api-key-conjur-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Conjur Authentication Method
      - $ref: '#/components/schemas/api-key-conjur-authentication-method-shared'
      required:
      - methodName
    api-key-conjur-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Conjur Authentication Method
      - $ref: '#/components/schemas/api-key-conjur-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    api-key-conjur-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumapi-key-conjur-authentication-methodSchemaUrn'
        username:
          type: string
          description: >-
              The username for the user to authenticate.
        password:
          type: string
          format: password
          description: >-
              The password for the user to authenticate. This will be used to obtain an API key for the target user.
        apiKey:
          type: string
          format: password
          description: >-
              The API key for the user to authenticate.
        description:
          type: string
          description: >-
              A description for this Conjur Authentication Method
      required:
      - schemas
      - username
    Enumapi-key-conjur-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:conjur-authentication-method:api-key"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
