openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Consent Service config object
  title: PingData Consent Service Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
tags:
- description: Access the Consent Service
  name: consent-service
paths:
  /consent-service:
    get:
      summary: Returns a single Consent Service
      operationId: get-consent-service
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/consent-service-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Consent Service does not exist
      security:
      - basicAuth: []
      tags:
      - consent-service
    patch:
      summary: Update an existing Consent Service by name
      operationId: update-consent-service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Consent Service
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/consent-service-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Consent Service does not exist
      security:
      - basicAuth: []
      tags:
      - consent-service
components:
  schemas:
    consent-service-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumconsent-serviceSchemaUrn'
          enabled:
            type: boolean
            description: >-
                Indicates whether the Consent Service is enabled.
          baseDN:
            type: string
            description: >-
                The base DN under which consent records are stored.
          bindDN:
            type: string
            description: >-
                The DN of an internal service account used by the Consent Service to make internal LDAP requests.
          searchSizeLimit:
            type: integer
            description: >-
                The maximum number of consent resources that may be returned from a search request.
          consentRecordIdentityMapper:
            type: array
            items:
              type: string
            description: >-
                If specified, the Identity Mapper(s) that may be used to map consent record subject and actor values to DNs. This is typically only needed if privileged API clients will be used.
          serviceAccountDN:
            type: array
            items:
              type: string
            description: >-
                The set of account DNs that the Consent Service will consider to be privileged.
          unprivilegedConsentScope:
            type: string
            description: >-
                The name of a scope that must be present in an access token accepted by the Consent Service for unprivileged clients.
          privilegedConsentScope:
            type: string
            description: >-
                The name of a scope that must be present in an access token accepted by the Consent Service if the client is to be considered privileged.
          audience:
            type: string
            description: >-
                A string or URI that identifies the Consent Service in the context of OAuth2 authorization.
      - $ref: '#/components/schemas/meta'
      required:
      - enabled
    Enumconsent-serviceSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:consent-service"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
