openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Correlated LDAP Data View config object
  title: PingData Correlated LDAP Data View Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access correlated-ldap-data-views
  name: correlated-ldap-data-view
paths:
  /correlated-ldap-data-views:
    post:
      summary: Add a new Correlated LDAP Data View to the config
      operationId: add-correlated-ldap-data-view
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-correlated-ldap-data-view-request'
        description: Create a new Correlated LDAP Data View in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/correlated-ldap-data-view-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Correlated LDAP Data View already exists
      security:
      - basicAuth: []
      tags:
      - correlated-ldap-data-view
  /correlated-ldap-data-views/{correlated-ldap-data-view-name}:
    delete:
      summary: Delete a Correlated LDAP Data View
      operationId: delete-correlated-ldap-data-view
      parameters:
      - description: Name of the Correlated LDAP Data View to be deleted
        explode: false
        in: path
        name: correlated-ldap-data-view-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Correlated LDAP Data View does not exist
        "409":
          description: The Correlated LDAP Data View cannot be deleted
      security:
      - basicAuth: []
      tags:
      - correlated-ldap-data-view
    get:
      summary: Returns a single Correlated LDAP Data View
      operationId: get-correlated-ldap-data-view
      parameters:
      - description: Name of the Correlated LDAP Data View to be read
        explode: false
        in: path
        name: correlated-ldap-data-view-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/correlated-ldap-data-view-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Correlated LDAP Data View does not exist
      security:
      - basicAuth: []
      tags:
      - correlated-ldap-data-view
    patch:
      summary: Update an existing Correlated LDAP Data View by name
      operationId: update-correlated-ldap-data-view
      parameters:
      - description: Name of the Correlated LDAP Data View to be updated
        explode: false
        in: path
        name: correlated-ldap-data-view-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Correlated LDAP Data View
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/correlated-ldap-data-view-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Correlated LDAP Data View does not exist
      security:
      - basicAuth: []
      tags:
      - correlated-ldap-data-view
components:
  schemas:
    add-correlated-ldap-data-view-request:
      allOf:
      - type: object
        properties:
          viewName:
            description: Name of the new Correlated LDAP Data View
            type: string
        required:
        - viewName
      - $ref: '#/components/schemas/correlated-ldap-data-view-shared'
    correlated-ldap-data-view-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Correlated LDAP Data View
            type: string
        required:
        - id
      - $ref: '#/components/schemas/correlated-ldap-data-view-shared'
    correlated-ldap-data-view-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumcorrelated-ldap-data-viewSchemaUrn'
        structuralLDAPObjectclass:
          type: string
          description: >-
              Specifies the LDAP structural object class that should be exposed by this Correlated LDAP Data View.
        auxiliaryLDAPObjectclass:
          type: array
          items:
            type: string
          description: >-
              Specifies an auxiliary LDAP object class that should be exposed by this Correlated LDAP Data View.
        includeBaseDN:
          type: string
          description: >-
              Specifies the base DN of the branch of the LDAP directory that can be accessed by this Correlated LDAP Data View.
        includeFilter:
          type: array
          items:
            type: string
          description: >-
              The set of LDAP filters that define the LDAP entries that should be included in this Correlated LDAP Data View.
        includeOperationalAttribute:
          type: array
          items:
            type: string
          description: >-
              Specifies the set of operational LDAP attributes to be provided by this Correlated LDAP Data View.
        createDNPattern:
          type: string
          description: >-
              Specifies the template to use for the DN when creating new entries.
        primaryCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the parent SCIM Resource Type whose value will be used to match objects in the Correlated LDAP Data View. If multiple correlation attributes are required they may be created using additional correlation-attribute-pairs.
        secondaryCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the Correlated LDAP Data View whose value will be matched with the primary-correlation-attribute. If multiple correlation attributes are required they may be specified by creating additional correlation-attribute-pairs.
      required:
      - structuralLDAPObjectclass
      - includeBaseDN
      - primaryCorrelationAttribute
      - secondaryCorrelationAttribute
    Enumcorrelated-ldap-data-viewSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:correlated-ldap-data-view"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
