openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Crypto Manager config object
  title: PingData Crypto Manager Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access the Crypto Manager
  name: crypto-manager
paths:
  /crypto-manager:
    get:
      summary: Returns a single Crypto Manager
      operationId: get-crypto-manager
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/crypto-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Crypto Manager does not exist
      security:
      - basicAuth: []
      tags:
      - crypto-manager
    patch:
      summary: Update an existing Crypto Manager by name
      operationId: update-crypto-manager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Crypto Manager
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/crypto-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Crypto Manager does not exist
      security:
      - basicAuth: []
      tags:
      - crypto-manager
components:
  schemas:
    crypto-manager-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumcrypto-managerSchemaUrn'
          digestAlgorithm:
            type: string
            description: >-
                Specifies the preferred message digest algorithm for the Directory Server.
          macAlgorithm:
            type: string
            description: >-
                Specifies the preferred MAC algorithm for the Directory Server.
          macKeyLength:
            type: integer
            description: >-
                Specifies the key length in bits for the preferred MAC algorithm.
          signingEncryptionSettingsID:
            type: string
            description: >-
                The ID of the encryption settings definition to use for generating digital signatures. If this is not specified, then the server's preferred encryption settings definition will be used.
          cipherTransformation:
            type: string
            description: >-
                Specifies the cipher for the Directory Server using the syntax algorithm/mode/padding.
          cipherKeyLength:
            type: integer
            description: >-
                Specifies the key length in bits for the preferred cipher.
          keyWrappingTransformation:
            type: string
            description: >-
                The preferred key wrapping transformation for the Directory Server. This value must be the same for all server instances in a replication topology.
          sslProtocol:
            type: array
            items:
              type: string
            description: >-
                Specifies the names of TLS protocols that are allowed for use in secure communication.
          sslCipherSuite:
            type: array
            items:
              type: string
            description: >-
                Specifies the names of the TLS cipher suites that are allowed for use in secure communication.
          outboundSSLProtocol:
            type: array
            items:
              type: string
            description: >-
                Specifies the names of the TLS protocols that will be enabled for outbound connections initiated by the Directory Server.
          outboundSSLCipherSuite:
            type: array
            items:
              type: string
            description: >-
                Specifies the names of the TLS cipher suites that will be enabled for outbound connections initiated by the Directory Server.
          enableSha1CipherSuites:
            type: boolean
            description: >-
                Indicates whether to enable support for TLS cipher suites that use the SHA-1 digest algorithm. The SHA-1 digest algorithm is no longer considered secure and is not recommended for use.
          enableRsaKeyExchangeCipherSuites:
            type: boolean
            description: >-
                Indicates whether to enable support for TLS cipher suites that use the RSA key exchange algorithm. Cipher suites that rely on RSA key exchange are not recommended because they do not support forward secrecy, which means that if the private key is compromised, then any communication negotiated using that private key should also be considered compromised.
          sslCertNickname:
            type: string
            description: >-
                Specifies the nickname (also called the alias) of the certificate that the Crypto Manager should use when performing SSL communication.
      - $ref: '#/components/schemas/meta'
    Enumcrypto-managerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:crypto-manager"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
