openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Delegated Admin Correlated REST Resource config object
  title: PingData Delegated Admin Correlated REST Resource Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access delegated-admin-correlated-rest-resources
  name: delegated-admin-correlated-rest-resource
paths:
  /delegated-admin-correlated-rest-resources:
    post:
      summary: Add a new Delegated Admin Correlated REST Resource to the config
      operationId: add-delegated-admin-correlated-rest-resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-delegated-admin-correlated-rest-resource-request'
        description: Create a new Delegated Admin Correlated REST Resource in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delegated-admin-correlated-rest-resource-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Delegated Admin Correlated REST Resource already exists
      security:
      - basicAuth: []
      tags:
      - delegated-admin-correlated-rest-resource
  /delegated-admin-correlated-rest-resources/{delegated-admin-correlated-rest-resource-name}:
    delete:
      summary: Delete a Delegated Admin Correlated REST Resource
      operationId: delete-delegated-admin-correlated-rest-resource
      parameters:
      - description: Name of the Delegated Admin Correlated REST Resource to be deleted
        explode: false
        in: path
        name: delegated-admin-correlated-rest-resource-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Delegated Admin Correlated REST Resource does not exist
        "409":
          description: The Delegated Admin Correlated REST Resource cannot be deleted
      security:
      - basicAuth: []
      tags:
      - delegated-admin-correlated-rest-resource
    get:
      summary: Returns a single Delegated Admin Correlated REST Resource
      operationId: get-delegated-admin-correlated-rest-resource
      parameters:
      - description: Name of the Delegated Admin Correlated REST Resource to be read
        explode: false
        in: path
        name: delegated-admin-correlated-rest-resource-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delegated-admin-correlated-rest-resource-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Delegated Admin Correlated REST Resource does not exist
      security:
      - basicAuth: []
      tags:
      - delegated-admin-correlated-rest-resource
    patch:
      summary: Update an existing Delegated Admin Correlated REST Resource by name
      operationId: update-delegated-admin-correlated-rest-resource
      parameters:
      - description: Name of the Delegated Admin Correlated REST Resource to be updated
        explode: false
        in: path
        name: delegated-admin-correlated-rest-resource-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Delegated Admin Correlated REST Resource
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delegated-admin-correlated-rest-resource-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Delegated Admin Correlated REST Resource does not exist
      security:
      - basicAuth: []
      tags:
      - delegated-admin-correlated-rest-resource
components:
  schemas:
    add-delegated-admin-correlated-rest-resource-request:
      allOf:
      - type: object
        properties:
          resourceName:
            description: Name of the new Delegated Admin Correlated REST Resource
            type: string
        required:
        - resourceName
      - $ref: '#/components/schemas/delegated-admin-correlated-rest-resource-shared'
    delegated-admin-correlated-rest-resource-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Delegated Admin Correlated REST Resource
            type: string
        required:
        - id
      - $ref: '#/components/schemas/delegated-admin-correlated-rest-resource-shared'
    delegated-admin-correlated-rest-resource-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumdelegated-admin-correlated-rest-resourceSchemaUrn'
        displayName:
          type: string
          description: >-
              A human readable display name for this Delegated Admin Correlated REST Resource.
        correlatedRESTResource:
          type: string
          description: >-
              The REST Resource Type that will be linked to this REST Resource Type.
        primaryRESTResourceCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the parent REST Resource Type whose value will be used to match objects in the Delegated Admin Correlated REST Resource. This attribute must be writeable when use-secondary-value-for-linking is enabled.
        secondaryRESTResourceCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the Delegated Admin Correlated REST Resource whose value will be matched with the primary-rest-resource-correlation-attribute. This attribute must be writeable when use-secondary-value-for-linking is disabled.
        useSecondaryValueForLinking:
          type: boolean
          description: >-
              Indicates whether links should be created using the secondary correlation attribute value.
      required:
      - displayName
      - correlatedRESTResource
      - primaryRESTResourceCorrelationAttribute
      - secondaryRESTResourceCorrelationAttribute
    Enumdelegated-admin-correlated-rest-resourceSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:delegated-admin-correlated-rest-resource"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
