openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Failure Lockout Action config object
  title: PingData Failure Lockout Action Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-100/pd_ds_use_config_api
tags:
- description: Access failure-lockout-actions
  name: failure-lockout-action
paths:
  /failure-lockout-actions:
    get:
      summary: Returns a list of all Failure Lockout Action objects
      operationId: list-failure-lockout-actions
      parameters:
      - in: query
        name: filter
        schema:
          type: string
        required: false
        description: SCIM filter
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure-lockout-actionListResponse'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
      security:
      - basicAuth: []
      tags:
      - failure-lockout-action
    post:
      summary: Add a new Failure Lockout Action to the config
      operationId: add-failure-lockout-action
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-delay-bind-response-failure-lockout-action-request'
              - $ref: '#/components/schemas/add-no-operation-failure-lockout-action-request'
              - $ref: '#/components/schemas/add-lock-account-failure-lockout-action-request'
        description: Create a new Failure Lockout Action in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-response'
                - $ref: '#/components/schemas/no-operation-failure-lockout-action-response'
                - $ref: '#/components/schemas/lock-account-failure-lockout-action-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Failure Lockout Action already exists
      security:
      - basicAuth: []
      tags:
      - failure-lockout-action
  /failure-lockout-actions/{failure-lockout-action-name}:
    delete:
      summary: Delete a Failure Lockout Action
      operationId: delete-failure-lockout-action
      parameters:
      - description: Name of the Failure Lockout Action
        explode: false
        in: path
        name: failure-lockout-action-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Failure Lockout Action does not exist
        "409":
          description: The Failure Lockout Action cannot be deleted
      security:
      - basicAuth: []
      tags:
      - failure-lockout-action
    get:
      summary: Returns a single Failure Lockout Action
      operationId: get-failure-lockout-action
      parameters:
      - description: Name of the Failure Lockout Action
        explode: false
        in: path
        name: failure-lockout-action-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-response'
                - $ref: '#/components/schemas/no-operation-failure-lockout-action-response'
                - $ref: '#/components/schemas/lock-account-failure-lockout-action-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Failure Lockout Action does not exist
      security:
      - basicAuth: []
      tags:
      - failure-lockout-action
    patch:
      summary: Update an existing Failure Lockout Action by name
      operationId: update-failure-lockout-action
      parameters:
      - description: Name of the Failure Lockout Action
        explode: false
        in: path
        name: failure-lockout-action-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Failure Lockout Action
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-response'
                - $ref: '#/components/schemas/no-operation-failure-lockout-action-response'
                - $ref: '#/components/schemas/lock-account-failure-lockout-action-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Failure Lockout Action does not exist
      security:
      - basicAuth: []
      tags:
      - failure-lockout-action
components:
  schemas:
    add-no-operation-failure-lockout-action-request:
      allOf:
      - type: object
        properties:
          actionName:
            type: string
            description: >-
                Name of the new Failure Lockout Action
      - $ref: '#/components/schemas/no-operation-failure-lockout-action-shared'
      required:
      - actionName
    no-operation-failure-lockout-action-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Failure Lockout Action
      - $ref: '#/components/schemas/no-operation-failure-lockout-action-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    no-operation-failure-lockout-action-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumno-operation-failure-lockout-actionSchemaUrn'
        generateAccountStatusNotification:
          type: boolean
          description: >-
              Indicates whether to generate an account status notification for cases in which this failure lockout action is invoked for a bind attempt with too many outstanding authentication failures.
        description:
          type: string
          description: >-
              A description for this Failure Lockout Action
      required:
      - schemas
    Enumno-operation-failure-lockout-actionSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:failure-lockout-action:no-operation"
    add-delay-bind-response-failure-lockout-action-request:
      allOf:
      - type: object
        properties:
          actionName:
            type: string
            description: >-
                Name of the new Failure Lockout Action
      - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-shared'
      required:
      - actionName
    delay-bind-response-failure-lockout-action-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Failure Lockout Action
      - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    delay-bind-response-failure-lockout-action-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumdelay-bind-response-failure-lockout-actionSchemaUrn'
        delay:
          type: string
          description: >-
              The length of time to delay the bind response for accounts with too many failed authentication attempts.
        allowBlockingDelay:
          type: boolean
          description: >-
              Indicates whether to delay the response for authentication attempts even if that delay may block the thread being used to process the attempt.
        generateAccountStatusNotification:
          type: boolean
          description: >-
              Indicates whether to generate an account status notification for cases in which a bind response is delayed because of failure lockout.
        description:
          type: string
          description: >-
              A description for this Failure Lockout Action
      required:
      - schemas
      - delay
    Enumdelay-bind-response-failure-lockout-actionSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:failure-lockout-action:delay-bind-response"
    add-lock-account-failure-lockout-action-request:
      allOf:
      - type: object
        properties:
          actionName:
            type: string
            description: >-
                Name of the new Failure Lockout Action
      - $ref: '#/components/schemas/lock-account-failure-lockout-action-shared'
      required:
      - actionName
    lock-account-failure-lockout-action-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Failure Lockout Action
      - $ref: '#/components/schemas/lock-account-failure-lockout-action-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    lock-account-failure-lockout-action-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumlock-account-failure-lockout-actionSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Failure Lockout Action
      required:
      - schemas
    Enumlock-account-failure-lockout-actionSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:failure-lockout-action:lock-account"
    failure-lockout-actionListResponse:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: string
        totalResults:
          type: number
        Resources:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/no-operation-failure-lockout-action-response'
            - $ref: '#/components/schemas/delay-bind-response-failure-lockout-action-response'
            - $ref: '#/components/schemas/lock-account-failure-lockout-action-response'
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
