openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Group Implementation config object
  title: PingData Group Implementation Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access group-implementations
  name: group-implementation
paths:
  /group-implementations/{group-implementation-name}:
    get:
      summary: Returns a single Group Implementation
      operationId: get-group-implementation
      parameters:
      - description: Name of the Group Implementation to be read
        explode: false
        in: path
        name: group-implementation-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/static-group-implementation-response'
                - $ref: '#/components/schemas/virtual-static-group-implementation-response'
                - $ref: '#/components/schemas/dynamic-group-implementation-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Group Implementation does not exist
      security:
      - basicAuth: []
      tags:
      - group-implementation
    patch:
      summary: Update an existing Group Implementation by name
      operationId: update-group-implementation
      parameters:
      - description: Name of the Group Implementation to be updated
        explode: false
        in: path
        name: group-implementation-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Group Implementation
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/static-group-implementation-response'
                - $ref: '#/components/schemas/virtual-static-group-implementation-response'
                - $ref: '#/components/schemas/dynamic-group-implementation-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Group Implementation does not exist
      security:
      - basicAuth: []
      tags:
      - group-implementation
components:
  schemas:
    static-group-implementation-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumstatic-group-implementationSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Group Implementation
        enabled:
          type: boolean
          description: >-
              Indicates whether the Group Implementation is enabled.
      required:
      - schemas
      - enabled
    Enumstatic-group-implementationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:group-implementation:static"
    virtual-static-group-implementation-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumvirtual-static-group-implementationSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Group Implementation
        enabled:
          type: boolean
          description: >-
              Indicates whether the Group Implementation is enabled.
      required:
      - schemas
      - enabled
    Enumvirtual-static-group-implementationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:group-implementation:virtual-static"
    dynamic-group-implementation-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumdynamic-group-implementationSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Group Implementation
        enabled:
          type: boolean
          description: >-
              Indicates whether the Group Implementation is enabled.
      required:
      - schemas
      - enabled
    Enumdynamic-group-implementationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:group-implementation:dynamic"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
