openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the HTTP Configuration config object
  title: PingData HTTP Configuration Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access the HTTP Configuration
  name: http-configuration
paths:
  /http-configuration:
    get:
      summary: Returns a single HTTP Configuration
      operationId: get-http-configuration
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-configuration-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The HTTP Configuration does not exist
      security:
      - basicAuth: []
      tags:
      - http-configuration
    patch:
      summary: Update an existing HTTP Configuration by name
      operationId: update-http-configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing HTTP Configuration
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-configuration-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The HTTP Configuration does not exist
      security:
      - basicAuth: []
      tags:
      - http-configuration
components:
  schemas:
    http-configuration-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumhttp-configurationSchemaUrn'
          includeStackTracesInErrorPages:
            type: boolean
            description: >-
                Indicates whether exceptions thrown by servlet or web application extensions will be included in the resulting error page response. Stack traces can be helpful in diagnosing application errors, but in production they may reveal information that might be useful to a malicious attacker.
          includeServletInformationInErrorPages:
            type: boolean
            description: >-
                Indicates whether to expose servlet information in the error page response.
      - $ref: '#/components/schemas/meta'
    Enumhttp-configurationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:http-configuration"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
