openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the HTTP Servlet Cross Origin Policy config object
  title: PingData HTTP Servlet Cross Origin Policy Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-100/pd_ds_use_config_api
tags:
- description: Access http-servlet-cross-origin-policies
  name: http-servlet-cross-origin-policy
paths:
  /http-servlet-cross-origin-policies:
    get:
      summary: Returns a list of all HTTP Servlet Cross Origin Policy objects
      operationId: list-http-servlet-cross-origin-policies
      parameters:
      - in: query
        name: filter
        schema:
          type: string
        required: false
        description: SCIM filter
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-servlet-cross-origin-policyListResponse'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
      security:
      - basicAuth: []
      tags:
      - http-servlet-cross-origin-policy
    post:
      summary: Add a new HTTP Servlet Cross Origin Policy to the config
      operationId: add-http-servlet-cross-origin-policy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-http-servlet-cross-origin-policy-request'
        description: Create a new HTTP Servlet Cross Origin Policy in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-servlet-cross-origin-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The HTTP Servlet Cross Origin Policy already exists
      security:
      - basicAuth: []
      tags:
      - http-servlet-cross-origin-policy
  /http-servlet-cross-origin-policies/{http-servlet-cross-origin-policy-name}:
    delete:
      summary: Delete a HTTP Servlet Cross Origin Policy
      operationId: delete-http-servlet-cross-origin-policy
      parameters:
      - description: Name of the HTTP Servlet Cross Origin Policy
        explode: false
        in: path
        name: http-servlet-cross-origin-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The HTTP Servlet Cross Origin Policy does not exist
        "409":
          description: The HTTP Servlet Cross Origin Policy cannot be deleted
      security:
      - basicAuth: []
      tags:
      - http-servlet-cross-origin-policy
    get:
      summary: Returns a single HTTP Servlet Cross Origin Policy
      operationId: get-http-servlet-cross-origin-policy
      parameters:
      - description: Name of the HTTP Servlet Cross Origin Policy
        explode: false
        in: path
        name: http-servlet-cross-origin-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-servlet-cross-origin-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The HTTP Servlet Cross Origin Policy does not exist
      security:
      - basicAuth: []
      tags:
      - http-servlet-cross-origin-policy
    patch:
      summary: Update an existing HTTP Servlet Cross Origin Policy by name
      operationId: update-http-servlet-cross-origin-policy
      parameters:
      - description: Name of the HTTP Servlet Cross Origin Policy
        explode: false
        in: path
        name: http-servlet-cross-origin-policy-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing HTTP Servlet Cross Origin Policy
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/http-servlet-cross-origin-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The HTTP Servlet Cross Origin Policy does not exist
      security:
      - basicAuth: []
      tags:
      - http-servlet-cross-origin-policy
components:
  schemas:
    add-http-servlet-cross-origin-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new HTTP Servlet Cross Origin Policy
      - $ref: '#/components/schemas/http-servlet-cross-origin-policy-shared'
      required:
      - policyName
    http-servlet-cross-origin-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the HTTP Servlet Cross Origin Policy
      - $ref: '#/components/schemas/http-servlet-cross-origin-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    http-servlet-cross-origin-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumhttp-servlet-cross-origin-policySchemaUrn'
        description:
          type: string
          description: >-
              A description for this HTTP Servlet Cross Origin Policy
        corsAllowedMethods:
          type: array
          items:
            type: string
          description: >-
              A list of HTTP methods allowed for cross-origin access to resources. i.e. one or more of GET, POST, PUT, DELETE, etc.
        corsAllowedOrigins:
          type: array
          items:
            type: string
          description: >-
              A list of origins that are allowed to execute cross-origin requests.
        corsExposedHeaders:
          type: array
          items:
            type: string
          description: >-
              A list of HTTP headers other than the simple response headers that browsers are allowed to access.
        corsAllowedHeaders:
          type: array
          items:
            type: string
          description: >-
              A list of HTTP headers that are supported by the resource and can be specified in a cross-origin request.
        corsPreflightMaxAge:
          type: string
          description: >-
              The maximum amount of time that a preflight request can be cached by a client.
        corsAllowCredentials:
          type: boolean
          description: >-
              Indicates whether the servlet extension allows CORS requests with username/password credentials.
    Enumhttp-servlet-cross-origin-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:http-servlet-cross-origin-policy"
    http-servlet-cross-origin-policyListResponse:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: string
        totalResults:
          type: number
        Resources:
          type: array
          items:
            $ref: '#/components/schemas/http-servlet-cross-origin-policy-response'
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
