openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Identity Mapper config object
  title: PingData Identity Mapper Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access identity-mappers
  name: identity-mapper
paths:
  /identity-mappers:
    post:
      summary: Add a new Identity Mapper to the config
      operationId: add-identity-mapper
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-exact-match-identity-mapper-request'
              - $ref: '#/components/schemas/add-groovy-scripted-identity-mapper-request'
              - $ref: '#/components/schemas/add-regular-expression-identity-mapper-request'
              - $ref: '#/components/schemas/add-aggregate-identity-mapper-request'
              - $ref: '#/components/schemas/add-third-party-identity-mapper-request'
        description: Create a new Identity Mapper in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/exact-match-identity-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-identity-mapper-response'
                - $ref: '#/components/schemas/regular-expression-identity-mapper-response'
                - $ref: '#/components/schemas/aggregate-identity-mapper-response'
                - $ref: '#/components/schemas/third-party-identity-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Identity Mapper already exists
      security:
      - basicAuth: []
      tags:
      - identity-mapper
  /identity-mappers/{identity-mapper-name}:
    delete:
      summary: Delete a Identity Mapper
      operationId: delete-identity-mapper
      parameters:
      - description: Name of the Identity Mapper
        explode: false
        in: path
        name: identity-mapper-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Identity Mapper does not exist
        "409":
          description: The Identity Mapper cannot be deleted
      security:
      - basicAuth: []
      tags:
      - identity-mapper
    get:
      summary: Returns a single Identity Mapper
      operationId: get-identity-mapper
      parameters:
      - description: Name of the Identity Mapper
        explode: false
        in: path
        name: identity-mapper-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/exact-match-identity-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-identity-mapper-response'
                - $ref: '#/components/schemas/regular-expression-identity-mapper-response'
                - $ref: '#/components/schemas/aggregate-identity-mapper-response'
                - $ref: '#/components/schemas/third-party-identity-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Identity Mapper does not exist
      security:
      - basicAuth: []
      tags:
      - identity-mapper
    patch:
      summary: Update an existing Identity Mapper by name
      operationId: update-identity-mapper
      parameters:
      - description: Name of the Identity Mapper
        explode: false
        in: path
        name: identity-mapper-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Identity Mapper
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/exact-match-identity-mapper-response'
                - $ref: '#/components/schemas/groovy-scripted-identity-mapper-response'
                - $ref: '#/components/schemas/regular-expression-identity-mapper-response'
                - $ref: '#/components/schemas/aggregate-identity-mapper-response'
                - $ref: '#/components/schemas/third-party-identity-mapper-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Identity Mapper does not exist
      security:
      - basicAuth: []
      tags:
      - identity-mapper
components:
  schemas:
    add-exact-match-identity-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            type: string
            description: >-
                Name of the new Identity Mapper
      - $ref: '#/components/schemas/exact-match-identity-mapper-shared'
      required:
      - mapperName
    exact-match-identity-mapper-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Identity Mapper
      - $ref: '#/components/schemas/exact-match-identity-mapper-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - matchAttribute
    exact-match-identity-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumexact-match-identity-mapperSchemaUrn'
        matchAttribute:
          type: array
          items:
            type: string
          description: >-
              Specifies the attribute whose value should exactly match the ID string provided to this identity mapper.
        matchBaseDN:
          type: array
          items:
            type: string
          description: >-
              Specifies the set of base DNs below which to search for users.
        matchFilter:
          type: string
          description: >-
              An optional filter that mapped users must match.
        description:
          type: string
          description: >-
              A description for this Identity Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Identity Mapper is enabled for use.
      required:
      - schemas
      - enabled
    Enumexact-match-identity-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:identity-mapper:exact-match"
    add-groovy-scripted-identity-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            type: string
            description: >-
                Name of the new Identity Mapper
      - $ref: '#/components/schemas/groovy-scripted-identity-mapper-shared'
      required:
      - mapperName
    groovy-scripted-identity-mapper-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Identity Mapper
      - $ref: '#/components/schemas/groovy-scripted-identity-mapper-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    groovy-scripted-identity-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scripted-identity-mapperSchemaUrn'
        scriptClass:
          type: string
          description: >-
              The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted Identity Mapper.
        scriptArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Scripted Identity Mapper. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Identity Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Identity Mapper is enabled for use.
      required:
      - schemas
      - scriptClass
      - enabled
    Enumgroovy-scripted-identity-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:identity-mapper:groovy-scripted"
    add-regular-expression-identity-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            type: string
            description: >-
                Name of the new Identity Mapper
      - $ref: '#/components/schemas/regular-expression-identity-mapper-shared'
      required:
      - mapperName
    regular-expression-identity-mapper-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Identity Mapper
      - $ref: '#/components/schemas/regular-expression-identity-mapper-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - matchAttribute
    regular-expression-identity-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumregular-expression-identity-mapperSchemaUrn'
        matchAttribute:
          type: array
          items:
            type: string
          description: >-
              Specifies the name or OID of the attribute whose value should match the provided identifier string after it has been processed by the associated regular expression.
        matchBaseDN:
          type: array
          items:
            type: string
          description: >-
              Specifies the base DN(s) that should be used when performing searches to map the provided ID string to a user entry. If multiple values are given, searches are performed below all the specified base DNs.
        matchFilter:
          type: string
          description: >-
              An optional filter that mapped users must match.
        matchPattern:
          type: string
          description: >-
              Specifies the regular expression pattern that is used to identify portions of the ID string that will be replaced.
        replacePattern:
          type: string
          description: >-
              Specifies the replacement pattern that should be used for substrings in the ID string that match the provided regular expression pattern.
        description:
          type: string
          description: >-
              A description for this Identity Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Identity Mapper is enabled for use.
      required:
      - schemas
      - matchPattern
      - enabled
    Enumregular-expression-identity-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:identity-mapper:regular-expression"
    add-aggregate-identity-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            type: string
            description: >-
                Name of the new Identity Mapper
      - $ref: '#/components/schemas/aggregate-identity-mapper-shared'
      required:
      - mapperName
    aggregate-identity-mapper-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Identity Mapper
      - $ref: '#/components/schemas/aggregate-identity-mapper-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    aggregate-identity-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumaggregate-identity-mapperSchemaUrn'
        allIncludedIdentityMapper:
          type: array
          items:
            type: string
          description: >-
              The set of identity mappers that must all match the target entry. Each identity mapper must uniquely match the same target entry. If any of the identity mappers match multiple entries, if any of them match zero entries, or if any of them match different entries, then the mapping will fail.
        anyIncludedIdentityMapper:
          type: array
          items:
            type: string
          description: >-
              The set of identity mappers that will be used to identify the target entry. At least one identity mapper must uniquely match an entry. If multiple identity mappers match entries, then they must all uniquely match the same entry. If none of the identity mappers match any entries, if any of them match multiple entries, or if any of them match different entries, then the mapping will fail.
        description:
          type: string
          description: >-
              A description for this Identity Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Identity Mapper is enabled for use.
      required:
      - schemas
      - enabled
    Enumaggregate-identity-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:identity-mapper:aggregate"
    add-third-party-identity-mapper-request:
      allOf:
      - type: object
        properties:
          mapperName:
            type: string
            description: >-
                Name of the new Identity Mapper
      - $ref: '#/components/schemas/third-party-identity-mapper-shared'
      required:
      - mapperName
    third-party-identity-mapper-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Identity Mapper
      - $ref: '#/components/schemas/third-party-identity-mapper-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    third-party-identity-mapper-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-identity-mapperSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Identity Mapper.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Identity Mapper. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Identity Mapper
        enabled:
          type: boolean
          description: >-
              Indicates whether the Identity Mapper is enabled for use.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-party-identity-mapperSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:identity-mapper:third-party"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
