openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Inter Server Authentication Info config object
  title: PingData Inter Server Authentication Info Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access inter-server-authentication-info
  name: inter-server-authentication-info
paths:
  /inter-server-authentication-info/{inter-server-authentication-info-name}:
    get:
      summary: Returns a single Inter Server Authentication Info
      operationId: get-inter-server-authentication-info
      parameters:
      - description: Name of the Inter Server Authentication Info to be read
        explode: false
        in: path
        name: inter-server-authentication-info-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/password-inter-server-authentication-info-response'
                - $ref: '#/components/schemas/certificate-inter-server-authentication-info-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Inter Server Authentication Info does not exist
      security:
      - basicAuth: []
      tags:
      - inter-server-authentication-info
    patch:
      summary: Update an existing Inter Server Authentication Info by name
      operationId: update-inter-server-authentication-info
      parameters:
      - description: Name of the Inter Server Authentication Info to be updated
        explode: false
        in: path
        name: inter-server-authentication-info-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Inter Server Authentication Info
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/password-inter-server-authentication-info-response'
                - $ref: '#/components/schemas/certificate-inter-server-authentication-info-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Inter Server Authentication Info does not exist
      security:
      - basicAuth: []
      tags:
      - inter-server-authentication-info
components:
  schemas:
    password-inter-server-authentication-info-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumpassword-inter-server-authentication-infoSchemaUrn'
          id:
            description: Name of the Inter Server Authentication Info
            type: string
          authenticationType:
            $ref: '#/components/schemas/Enuminter-server-authentication-info-authenticationTypeProp'
          bindDN:
            type: string
            description: >-
                A DN of the username that should be used for the bind request.
          username:
            type: string
            description: >-
                The username that should be used for the bind request.
          password:
            type: string
            format: password
            description: >-
                The password for the username or bind-dn.
          purpose:
            type: array
            items:
              $ref: '#/components/schemas/Enuminter-server-authentication-info-purposeProp'
        required:
        - schemas
        - password
        - id
    Enumpassword-inter-server-authentication-infoSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:inter-server-authentication-info:password"
    certificate-inter-server-authentication-info-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumcertificate-inter-server-authentication-infoSchemaUrn'
          id:
            description: Name of the Inter Server Authentication Info
            type: string
          purpose:
            type: array
            items:
              $ref: '#/components/schemas/Enuminter-server-authentication-info-purposeProp'
        required:
        - schemas
        - id
    Enumcertificate-inter-server-authentication-infoSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:inter-server-authentication-info:certificate"
    Enuminter-server-authentication-info-authenticationTypeProp:
      type: string
      enum:
      - "simple"
      - "sasl-plain"
      description: >-
          Identifies the type of password authentication that will be used.
    Enuminter-server-authentication-info-purposeProp:
      type: string
      enum:
      - "mirrored-config"
      description: >-
          Identifies the purpose of this Inter Server Authentication Info.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
