openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the JSON Attribute Constraints config object
  title: PingData JSON Attribute Constraints Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access json-attribute-constraints
  name: json-attribute-constraints
paths:
  /json-attribute-constraints:
    post:
      summary: Add a new JSON Attribute Constraints to the config
      operationId: add-json-attribute-constraints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-json-attribute-constraints-request'
        description: Create a new JSON Attribute Constraints in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json-attribute-constraints-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The JSON Attribute Constraints already exists
      security:
      - basicAuth: []
      tags:
      - json-attribute-constraints
  /json-attribute-constraints/{json-attribute-constraints-name}:
    delete:
      summary: Delete a JSON Attribute Constraints
      operationId: delete-json-attribute-constraints
      parameters:
      - description: Name of the JSON Attribute Constraints to be deleted
        explode: false
        in: path
        name: json-attribute-constraints-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The JSON Attribute Constraints does not exist
        "409":
          description: The JSON Attribute Constraints cannot be deleted
      security:
      - basicAuth: []
      tags:
      - json-attribute-constraints
    get:
      summary: Returns a single JSON Attribute Constraints
      operationId: get-json-attribute-constraints
      parameters:
      - description: Name of the JSON Attribute Constraints to be read
        explode: false
        in: path
        name: json-attribute-constraints-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json-attribute-constraints-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The JSON Attribute Constraints does not exist
      security:
      - basicAuth: []
      tags:
      - json-attribute-constraints
    patch:
      summary: Update an existing JSON Attribute Constraints by name
      operationId: update-json-attribute-constraints
      parameters:
      - description: Name of the JSON Attribute Constraints to be updated
        explode: false
        in: path
        name: json-attribute-constraints-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing JSON Attribute Constraints
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json-attribute-constraints-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The JSON Attribute Constraints does not exist
      security:
      - basicAuth: []
      tags:
      - json-attribute-constraints
components:
  schemas:
    add-json-attribute-constraints-request:
      allOf:
      - type: object
        properties:
          attributeType:
            description: Name of the new JSON Attribute Constraints
            type: string
        required:
        - attributeType
      - $ref: '#/components/schemas/json-attribute-constraints-shared'
    json-attribute-constraints-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the JSON Attribute Constraints
            type: string
        required:
        - id
      - $ref: '#/components/schemas/json-attribute-constraints-shared'
    json-attribute-constraints-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumjson-attribute-constraintsSchemaUrn'
        description:
          type: string
          description: >-
              A description for this JSON Attribute Constraints
        enabled:
          type: boolean
          description: >-
              Indicates whether this JSON Attribute Constraints is enabled.
        attributeType:
          type: string
          description: >-
              The name or OID of the LDAP attribute type whose values will be subject to the associated field constraints. This attribute type must be defined in the server schema, and it must have a "JSON object" syntax.
        allowUnnamedFields:
          type: boolean
          description: >-
              Indicates whether JSON objects stored as values of attributes with the associated attribute-type will be permitted to include fields for which there is no subordinate json-field-constraints definition. If unnamed fields are allowed, then no constraints will be imposed on the values of those fields. However, if unnamed fields are not allowed, then the server will reject any attempt to store a JSON object with a field for which there is no corresponding json-fields-constraints definition.
      required:
      - attributeType
    Enumjson-attribute-constraintsSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:json-attribute-constraints"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
