openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the LDAP SDK Debug Logger config object
  title: PingData LDAP SDK Debug Logger Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access the LDAP SDK Debug Logger
  name: ldap-sdk-debug-logger
paths:
  /ldap-sdk-debug-logger:
    get:
      summary: Returns a single LDAP SDK Debug Logger
      operationId: get-ldap-sdk-debug-logger
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ldap-sdk-debug-logger-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The LDAP SDK Debug Logger does not exist
      security:
      - basicAuth: []
      tags:
      - ldap-sdk-debug-logger
    patch:
      summary: Update an existing LDAP SDK Debug Logger by name
      operationId: update-ldap-sdk-debug-logger
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing LDAP SDK Debug Logger
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ldap-sdk-debug-logger-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The LDAP SDK Debug Logger does not exist
      security:
      - basicAuth: []
      tags:
      - ldap-sdk-debug-logger
components:
  schemas:
    ldap-sdk-debug-logger-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumldap-sdk-debug-loggerSchemaUrn'
        description:
          type: string
          description: >-
              A description for this LDAP SDK Debug Logger
        enabled:
          type: boolean
          description: >-
              Indicates whether this LDAP SDK Debug Logger is enabled.
        logFile:
          type: string
          description: >-
              The path and base name of the file to use for log files generated by this LDAP SDK Debug Logger. The path may be either absolute or relative to the server root.
        debugLevel:
          $ref: '#/components/schemas/Enumldap-sdk-debug-logger-debugLevelProp'
        debugType:
          type: array
          items:
            $ref: '#/components/schemas/Enumldap-sdk-debug-logger-debugTypeProp'
        includeStackTrace:
          type: boolean
          description: >-
              Indicates whether a stack trace of the thread which called the debug method should be included in debug log messages.
        logFilePermissions:
          type: string
          description: >-
              The UNIX permissions of the log files created by this LDAP SDK Debug Logger.
        timeInterval:
          type: string
          description: >-
              Specifies the interval at which to check whether the log files need to be rotated.
        autoFlush:
          type: boolean
          description: >-
              Specifies whether to flush the writer after every log record.
        asynchronous:
          type: boolean
          description: >-
              Indicates whether the LDAP SDK Debug Logger will publish records asynchronously.
        queueSize:
          type: integer
          description: >-
              The maximum number of log records that can be stored in the asynchronous queue.
        bufferSize:
          type: string
          description: >-
              Specifies the log file buffer size.
        append:
          type: boolean
          description: >-
              Specifies whether to append to existing log files.
        rotationPolicy:
          type: array
          items:
            type: string
            description: >-
                The rotation policy to use for the LDAP SDK Debug Logger .
        rotationListener:
          type: array
          items:
            type: string
            description: >-
                A listener that should be notified whenever a log file is rotated out of service.
        retentionPolicy:
          type: array
          items:
            type: string
            description: >-
                The retention policy to use for the LDAP SDK Debug Logger .
        compressionMechanism:
          $ref: '#/components/schemas/Enumldap-sdk-debug-logger-compressionMechanismProp'
        signLog:
          type: boolean
          description: >-
              Indicates whether the log should be cryptographically signed so that the log content cannot be altered in an undetectable manner.
        encryptLog:
          type: boolean
          description: >-
              Indicates whether log files should be encrypted so that their content is not available to unauthorized users.
        encryptionSettingsDefinitionID:
          type: string
          description: >-
              Specifies the ID of the encryption settings definition that should be used to encrypt the data. If this is not provided, the server's preferred encryption settings definition will be used. The "encryption-settings list" command can be used to obtain a list of the encryption settings definitions available in the server.
        timestampPrecision:
          $ref: '#/components/schemas/Enumldap-sdk-debug-logger-timestampPrecisionProp'
        loggingErrorBehavior:
          $ref: '#/components/schemas/Enumldap-sdk-debug-logger-loggingErrorBehaviorProp'
      required:
      - enabled
      - logFile
      - debugLevel
      - debugType
      - includeStackTrace
      - logFilePermissions
      - asynchronous
      - rotationPolicy
      - retentionPolicy
    Enumldap-sdk-debug-loggerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:ldap-sdk-debug-logger"
    Enumldap-sdk-debug-logger-debugLevelProp:
      type: string
      enum:
      - "severe"
      - "warning"
      - "info"
      - "config"
      - "fine"
      - "finer"
      - "finest"
      description: >-
          The minimum debug level that should be used for messages to be logged.
    Enumldap-sdk-debug-logger-loggingErrorBehaviorProp:
      type: string
      enum:
      - "standard-error"
      - "lockdown-mode"
      description: >-
          Specifies the behavior that the server should exhibit if an error occurs during logging processing.
    Enumldap-sdk-debug-logger-debugTypeProp:
      type: string
      enum:
      - "asn1"
      - "coding-error"
      - "connect"
      - "exception"
      - "ldap"
      - "ldif"
      - "monitor"
      - "other"
      description: >-
          The types of debug messages that should be logged.
    Enumldap-sdk-debug-logger-timestampPrecisionProp:
      type: string
      enum:
      - "seconds"
      - "milliseconds"
      description: >-
          Specifies the smallest time unit to be included in timestamps.
    Enumldap-sdk-debug-logger-compressionMechanismProp:
      type: string
      enum:
      - "none"
      - "gzip"
      description: >-
          Specifies the type of compression (if any) to use for log files that are written.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
