openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the LDAP Correlation Attribute Pair config object
  title: PingData LDAP Correlation Attribute Pair Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access ldap-correlation-attribute-pairs
  name: ldap-correlation-attribute-pair
paths:
  /ldap-correlation-attribute-pairs:
    post:
      summary: Add a new LDAP Correlation Attribute Pair to the config
      operationId: add-ldap-correlation-attribute-pair
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-ldap-correlation-attribute-pair-request'
        description: Create a new LDAP Correlation Attribute Pair in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ldap-correlation-attribute-pair-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The LDAP Correlation Attribute Pair already exists
      security:
      - basicAuth: []
      tags:
      - ldap-correlation-attribute-pair
  /ldap-correlation-attribute-pairs/{ldap-correlation-attribute-pair-name}:
    delete:
      summary: Delete a LDAP Correlation Attribute Pair
      operationId: delete-ldap-correlation-attribute-pair
      parameters:
      - description: Name of the LDAP Correlation Attribute Pair to be deleted
        explode: false
        in: path
        name: ldap-correlation-attribute-pair-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The LDAP Correlation Attribute Pair does not exist
        "409":
          description: The LDAP Correlation Attribute Pair cannot be deleted
      security:
      - basicAuth: []
      tags:
      - ldap-correlation-attribute-pair
    get:
      summary: Returns a single LDAP Correlation Attribute Pair
      operationId: get-ldap-correlation-attribute-pair
      parameters:
      - description: Name of the LDAP Correlation Attribute Pair to be read
        explode: false
        in: path
        name: ldap-correlation-attribute-pair-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ldap-correlation-attribute-pair-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The LDAP Correlation Attribute Pair does not exist
      security:
      - basicAuth: []
      tags:
      - ldap-correlation-attribute-pair
    patch:
      summary: Update an existing LDAP Correlation Attribute Pair by name
      operationId: update-ldap-correlation-attribute-pair
      parameters:
      - description: Name of the LDAP Correlation Attribute Pair to be updated
        explode: false
        in: path
        name: ldap-correlation-attribute-pair-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing LDAP Correlation Attribute Pair
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ldap-correlation-attribute-pair-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The LDAP Correlation Attribute Pair does not exist
      security:
      - basicAuth: []
      tags:
      - ldap-correlation-attribute-pair
components:
  schemas:
    add-ldap-correlation-attribute-pair-request:
      allOf:
      - type: object
        properties:
          pairName:
            description: Name of the new LDAP Correlation Attribute Pair
            type: string
        required:
        - pairName
      - $ref: '#/components/schemas/ldap-correlation-attribute-pair-shared'
    ldap-correlation-attribute-pair-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the LDAP Correlation Attribute Pair
            type: string
        required:
        - id
      - $ref: '#/components/schemas/ldap-correlation-attribute-pair-shared'
    ldap-correlation-attribute-pair-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumldap-correlation-attribute-pairSchemaUrn'
        primaryCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the base SCIM Resource Type whose value will be used to match objects in the Correlated LDAP Data View.
        secondaryCorrelationAttribute:
          type: string
          description: >-
              The LDAP attribute from the Correlated LDAP Data View whose value will be matched.
      required:
      - primaryCorrelationAttribute
      - secondaryCorrelationAttribute
    Enumldap-correlation-attribute-pairSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:ldap-correlation-attribute-pair"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
