openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Location config object
  title: PingData Location Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
tags:
- description: Access locations
  name: location
paths:
  /locations:
    post:
      summary: Add a new Location to the config
      operationId: add-location
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-location-request'
        description: Create a new Location in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Location already exists
      security:
      - basicAuth: []
      tags:
      - location
  /locations/{location-name}:
    delete:
      summary: Delete a Location
      operationId: delete-location
      parameters:
      - description: Name of the Location
        explode: false
        in: path
        name: location-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Location does not exist
        "409":
          description: The Location cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Location
      operationId: get-location
      parameters:
      - description: Name of the Location
        explode: false
        in: path
        name: location-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Location does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Location by name
      operationId: update-location
      parameters:
      - description: Name of the Location
        explode: false
        in: path
        name: location-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Location
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Location does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    add-location-request:
      allOf:
      - type: object
        properties:
          locationName:
            type: string
            description: >-
                Name of the new Location
      - $ref: '#/components/schemas/location-shared'
      required:
      - locationName
    location-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Location
      - $ref: '#/components/schemas/location-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    location-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumlocationSchemaUrn'
        description:
          type: string
          description: >-
              A description for this Location
    EnumlocationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:location"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
