openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Local DB VLV Index config object
  title: PingData Local DB VLV Index Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access local-db-vlv-indexes
  name: local-db-vlv-index
paths:
  /local-db-vlv-indexes:
    post:
      summary: Add a new Local DB VLV Index to the config
      operationId: add-local-db-vlv-index
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-local-db-vlv-index-request'
        description: Create a new Local DB VLV Index in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/local-db-vlv-index-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Local DB VLV Index already exists
      security:
      - basicAuth: []
      tags:
      - local-db-vlv-index
  /local-db-vlv-indexes/{local-db-vlv-index-name}:
    delete:
      summary: Delete a Local DB VLV Index
      operationId: delete-local-db-vlv-index
      parameters:
      - description: Name of the Local DB VLV Index to be deleted
        explode: false
        in: path
        name: local-db-vlv-index-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Local DB VLV Index does not exist
        "409":
          description: The Local DB VLV Index cannot be deleted
      security:
      - basicAuth: []
      tags:
      - local-db-vlv-index
    get:
      summary: Returns a single Local DB VLV Index
      operationId: get-local-db-vlv-index
      parameters:
      - description: Name of the Local DB VLV Index to be read
        explode: false
        in: path
        name: local-db-vlv-index-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/local-db-vlv-index-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Local DB VLV Index does not exist
      security:
      - basicAuth: []
      tags:
      - local-db-vlv-index
    patch:
      summary: Update an existing Local DB VLV Index by name
      operationId: update-local-db-vlv-index
      parameters:
      - description: Name of the Local DB VLV Index to be updated
        explode: false
        in: path
        name: local-db-vlv-index-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Local DB VLV Index
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/local-db-vlv-index-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Local DB VLV Index does not exist
      security:
      - basicAuth: []
      tags:
      - local-db-vlv-index
components:
  schemas:
    add-local-db-vlv-index-request:
      allOf:
      - type: object
        properties:
          indexName:
            description: Name of the new Local DB VLV Index
            type: string
        required:
        - indexName
      - $ref: '#/components/schemas/local-db-vlv-index-shared'
    local-db-vlv-index-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Local DB VLV Index
            type: string
        required:
        - id
      - $ref: '#/components/schemas/local-db-vlv-index-shared'
    local-db-vlv-index-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumlocal-db-vlv-indexSchemaUrn'
        baseDN:
          type: string
          description: >-
              Specifies the base DN used in the search query that is being indexed.
        scope:
          $ref: '#/components/schemas/Enumlocal-db-vlv-index-scopeProp'
        filter:
          type: string
          description: >-
              Specifies the LDAP filter used in the query that is being indexed.
        sortOrder:
          type: string
          description: >-
              Specifies the names of the attributes that are used to sort the entries for the query being indexed.
        name:
          type: string
          description: >-
              Specifies a unique name for this VLV index.
        maxBlockSize:
          type: integer
          description: >-
              Specifies the number of entry IDs to store in a single sorted set before it must be split.
        cacheMode:
          $ref: '#/components/schemas/Enumlocal-db-vlv-index-cacheModeProp'
      required:
      - baseDN
      - scope
      - filter
      - sortOrder
      - name
    Enumlocal-db-vlv-indexSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:local-db-vlv-index"
    Enumlocal-db-vlv-index-cacheModeProp:
      type: string
      enum:
      - "cache-keys-and-values"
      - "cache-keys-only"
      - "no-caching"
      - "keep-hot"
      - "default"
      - "make-cold"
      - "evict-leaf-immediately"
      - "evict-bin-immediately"
      description: >-
          Specifies the cache mode that should be used when accessing the records in the database for this index.
    Enumlocal-db-vlv-index-scopeProp:
      type: string
      enum:
      - "base-object"
      - "single-level"
      - "whole-subtree"
      - "subordinate-subtree"
      description: >-
          Specifies the LDAP scope of the query that is being indexed.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
