openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Log File Rotation Listener config object
  title: PingData Log File Rotation Listener Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access log-file-rotation-listeners
  name: log-file-rotation-listener
paths:
  /log-file-rotation-listeners:
    post:
      summary: Add a new Log File Rotation Listener to the config
      operationId: add-log-file-rotation-listener
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-summarize-log-file-rotation-listener-request'
              - $ref: '#/components/schemas/add-copy-log-file-rotation-listener-request'
              - $ref: '#/components/schemas/add-third-party-log-file-rotation-listener-request'
        description: Create a new Log File Rotation Listener in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/summarize-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/copy-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/third-party-log-file-rotation-listener-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Log File Rotation Listener already exists
      security:
      - basicAuth: []
      tags:
      - log-file-rotation-listener
  /log-file-rotation-listeners/{log-file-rotation-listener-name}:
    delete:
      summary: Delete a Log File Rotation Listener
      operationId: delete-log-file-rotation-listener
      parameters:
      - description: Name of the Log File Rotation Listener
        explode: false
        in: path
        name: log-file-rotation-listener-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log File Rotation Listener does not exist
        "409":
          description: The Log File Rotation Listener cannot be deleted
      security:
      - basicAuth: []
      tags:
      - log-file-rotation-listener
    get:
      summary: Returns a single Log File Rotation Listener
      operationId: get-log-file-rotation-listener
      parameters:
      - description: Name of the Log File Rotation Listener
        explode: false
        in: path
        name: log-file-rotation-listener-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/summarize-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/copy-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/third-party-log-file-rotation-listener-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log File Rotation Listener does not exist
      security:
      - basicAuth: []
      tags:
      - log-file-rotation-listener
    patch:
      summary: Update an existing Log File Rotation Listener by name
      operationId: update-log-file-rotation-listener
      parameters:
      - description: Name of the Log File Rotation Listener
        explode: false
        in: path
        name: log-file-rotation-listener-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Log File Rotation Listener
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/summarize-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/copy-log-file-rotation-listener-response'
                - $ref: '#/components/schemas/third-party-log-file-rotation-listener-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Log File Rotation Listener does not exist
      security:
      - basicAuth: []
      tags:
      - log-file-rotation-listener
components:
  schemas:
    add-summarize-log-file-rotation-listener-request:
      allOf:
      - type: object
        properties:
          listenerName:
            description: Name of the new Log File Rotation Listener
            type: string
        required:
        - listenerName
      - $ref: '#/components/schemas/summarize-log-file-rotation-listener-shared'
    summarize-log-file-rotation-listener-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Log File Rotation Listener
            type: string
        required:
        - id
      - $ref: '#/components/schemas/summarize-log-file-rotation-listener-shared'
    summarize-log-file-rotation-listener-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsummarize-log-file-rotation-listenerSchemaUrn'
        outputDirectory:
          type: string
          description: >-
              The path to the directory in which the summarize-access-log output should be written. If no value is provided, the output file will be written into the same directory as the rotated log file.
        description:
          type: string
          description: >-
              A description for this Log File Rotation Listener
        enabled:
          type: boolean
          description: >-
              Indicates whether the Log File Rotation Listener is enabled for use.
      required:
      - schemas
      - enabled
    Enumsummarize-log-file-rotation-listenerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-file-rotation-listener:summarize"
    add-copy-log-file-rotation-listener-request:
      allOf:
      - type: object
        properties:
          listenerName:
            description: Name of the new Log File Rotation Listener
            type: string
        required:
        - listenerName
      - $ref: '#/components/schemas/copy-log-file-rotation-listener-shared'
    copy-log-file-rotation-listener-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Log File Rotation Listener
            type: string
        required:
        - id
      - $ref: '#/components/schemas/copy-log-file-rotation-listener-shared'
    copy-log-file-rotation-listener-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumcopy-log-file-rotation-listenerSchemaUrn'
        copyToDirectory:
          type: string
          description: >-
              The path to the directory to which log files should be copied. It must be different from the directory to which the log file is originally written, and administrators should ensure that the filesystem has sufficient space to hold files as they are copied.
        compressOnCopy:
          type: boolean
          description: >-
              Indicates whether the file should be gzip-compressed as it is copied into the destination directory.
        description:
          type: string
          description: >-
              A description for this Log File Rotation Listener
        enabled:
          type: boolean
          description: >-
              Indicates whether the Log File Rotation Listener is enabled for use.
      required:
      - schemas
      - copyToDirectory
      - enabled
    Enumcopy-log-file-rotation-listenerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-file-rotation-listener:copy"
    add-third-party-log-file-rotation-listener-request:
      allOf:
      - type: object
        properties:
          listenerName:
            description: Name of the new Log File Rotation Listener
            type: string
        required:
        - listenerName
      - $ref: '#/components/schemas/third-party-log-file-rotation-listener-shared'
    third-party-log-file-rotation-listener-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Log File Rotation Listener
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-log-file-rotation-listener-shared'
    third-party-log-file-rotation-listener-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-log-file-rotation-listenerSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Log File Rotation Listener.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Log File Rotation Listener. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Log File Rotation Listener
        enabled:
          type: boolean
          description: >-
              Indicates whether the Log File Rotation Listener is enabled for use.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-party-log-file-rotation-listenerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-file-rotation-listener:third-party"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
