openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Log Retention Policy config object
  title: PingData Log Retention Policy Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access log-retention-policies
  name: log-retention-policy
paths:
  /log-retention-policies:
    get:
      summary: Returns a list of all Log Retention Policy objects
      operationId: list-log-retention-policies
      parameters:
      - in: query
        name: filter
        schema:
          type: string
        required: false
        description: SCIM filter
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/log-retention-policyListResponse'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
      security:
      - basicAuth: []
      tags:
      - log-retention-policy
    post:
      summary: Add a new Log Retention Policy to the config
      operationId: add-log-retention-policy
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-time-limit-log-retention-policy-request'
              - $ref: '#/components/schemas/add-never-delete-log-retention-policy-request'
              - $ref: '#/components/schemas/add-file-count-log-retention-policy-request'
              - $ref: '#/components/schemas/add-free-disk-space-log-retention-policy-request'
              - $ref: '#/components/schemas/add-size-limit-log-retention-policy-request'
        description: Create a new Log Retention Policy in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-retention-policy-response'
                - $ref: '#/components/schemas/never-delete-log-retention-policy-response'
                - $ref: '#/components/schemas/file-count-log-retention-policy-response'
                - $ref: '#/components/schemas/free-disk-space-log-retention-policy-response'
                - $ref: '#/components/schemas/size-limit-log-retention-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Log Retention Policy already exists
      security:
      - basicAuth: []
      tags:
      - log-retention-policy
  /log-retention-policies/{log-retention-policy-name}:
    delete:
      summary: Delete a Log Retention Policy
      operationId: delete-log-retention-policy
      parameters:
      - description: Name of the Log Retention Policy
        explode: false
        in: path
        name: log-retention-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Retention Policy does not exist
        "409":
          description: The Log Retention Policy cannot be deleted
      security:
      - basicAuth: []
      tags:
      - log-retention-policy
    get:
      summary: Returns a single Log Retention Policy
      operationId: get-log-retention-policy
      parameters:
      - description: Name of the Log Retention Policy
        explode: false
        in: path
        name: log-retention-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-retention-policy-response'
                - $ref: '#/components/schemas/never-delete-log-retention-policy-response'
                - $ref: '#/components/schemas/file-count-log-retention-policy-response'
                - $ref: '#/components/schemas/free-disk-space-log-retention-policy-response'
                - $ref: '#/components/schemas/size-limit-log-retention-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Retention Policy does not exist
      security:
      - basicAuth: []
      tags:
      - log-retention-policy
    patch:
      summary: Update an existing Log Retention Policy by name
      operationId: update-log-retention-policy
      parameters:
      - description: Name of the Log Retention Policy
        explode: false
        in: path
        name: log-retention-policy-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Log Retention Policy
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-retention-policy-response'
                - $ref: '#/components/schemas/never-delete-log-retention-policy-response'
                - $ref: '#/components/schemas/file-count-log-retention-policy-response'
                - $ref: '#/components/schemas/free-disk-space-log-retention-policy-response'
                - $ref: '#/components/schemas/size-limit-log-retention-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Log Retention Policy does not exist
      security:
      - basicAuth: []
      tags:
      - log-retention-policy
components:
  schemas:
    add-time-limit-log-retention-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Retention Policy
      - $ref: '#/components/schemas/time-limit-log-retention-policy-shared'
      required:
      - policyName
    time-limit-log-retention-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Retention Policy
      - $ref: '#/components/schemas/time-limit-log-retention-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    time-limit-log-retention-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumtime-limit-log-retention-policySchemaUrn'
        retainDuration:
          type: string
          description: >-
              Specifies the desired minimum length of time that each log file should be retained.
        description:
          type: string
          description: >-
              A description for this Log Retention Policy
      required:
      - schemas
      - retainDuration
    Enumtime-limit-log-retention-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:time-limit"
    add-never-delete-log-retention-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Retention Policy
      - $ref: '#/components/schemas/never-delete-log-retention-policy-shared'
      required:
      - policyName
    never-delete-log-retention-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Retention Policy
      - $ref: '#/components/schemas/never-delete-log-retention-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    never-delete-log-retention-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumnever-delete-log-retention-policySchemaUrn'
        description:
          type: string
          description: >-
              A description for this Log Retention Policy
      required:
      - schemas
    Enumnever-delete-log-retention-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:never-delete"
    add-file-count-log-retention-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Retention Policy
      - $ref: '#/components/schemas/file-count-log-retention-policy-shared'
      required:
      - policyName
    file-count-log-retention-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Retention Policy
      - $ref: '#/components/schemas/file-count-log-retention-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    file-count-log-retention-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumfile-count-log-retention-policySchemaUrn'
        numberOfFiles:
          type: integer
          description: >-
              Specifies the number of archived log files to retain before the oldest ones are cleaned.
        description:
          type: string
          description: >-
              A description for this Log Retention Policy
      required:
      - schemas
      - numberOfFiles
    Enumfile-count-log-retention-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:file-count"
    add-free-disk-space-log-retention-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Retention Policy
      - $ref: '#/components/schemas/free-disk-space-log-retention-policy-shared'
      required:
      - policyName
    free-disk-space-log-retention-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Retention Policy
      - $ref: '#/components/schemas/free-disk-space-log-retention-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    free-disk-space-log-retention-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumfree-disk-space-log-retention-policySchemaUrn'
        freeDiskSpace:
          type: string
          description: >-
              Specifies the minimum amount of free disk space that should be available on the file system on which the archived log files are stored.
        description:
          type: string
          description: >-
              A description for this Log Retention Policy
      required:
      - schemas
      - freeDiskSpace
    Enumfree-disk-space-log-retention-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:free-disk-space"
    add-size-limit-log-retention-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Retention Policy
      - $ref: '#/components/schemas/size-limit-log-retention-policy-shared'
      required:
      - policyName
    size-limit-log-retention-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Retention Policy
      - $ref: '#/components/schemas/size-limit-log-retention-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    size-limit-log-retention-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsize-limit-log-retention-policySchemaUrn'
        diskSpaceUsed:
          type: string
          description: >-
              Specifies the maximum total disk space used by the log files.
        description:
          type: string
          description: >-
              A description for this Log Retention Policy
      required:
      - schemas
      - diskSpaceUsed
    Enumsize-limit-log-retention-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:size-limit"
    log-retention-policyListResponse:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: string
        totalResults:
          type: number
        Resources:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/time-limit-log-retention-policy-response'
            - $ref: '#/components/schemas/never-delete-log-retention-policy-response'
            - $ref: '#/components/schemas/file-count-log-retention-policy-response'
            - $ref: '#/components/schemas/free-disk-space-log-retention-policy-response'
            - $ref: '#/components/schemas/size-limit-log-retention-policy-response'
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
