openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Log Field Syntax config object
  title: PingData Log Field Syntax Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access log-field-syntaxes
  name: log-field-syntax
paths:
  /log-field-syntaxes:
    post:
      summary: Add a new Log Field Syntax to the config
      operationId: add-log-field-syntax
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
        description: Create a new Log Field Syntax in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Log Field Syntax already exists
      security:
      - basicAuth: []
      tags:
      - location
  /log-field-syntaxes/{log-field-syntax-name}:
    delete:
      summary: Delete a Log Field Syntax
      operationId: delete-log-field-syntax
      parameters:
      - description: Name of the Log Field Syntax to be deleted
        explode: false
        in: path
        name: log-field-syntax-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Field Syntax does not exist
        "409":
          description: The Log Field Syntax cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Log Field Syntax
      operationId: get-log-field-syntax
      parameters:
      - description: Name of the Log Field Syntax to be read
        explode: false
        in: path
        name: log-field-syntax-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/json-response'
                - $ref: '#/components/schemas/attribute-based-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Field Syntax does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Log Field Syntax by name
      operationId: update-log-field-syntax
      parameters:
      - description: Name of the Log Field Syntax to be updated
        explode: false
        in: path
        name: log-field-syntax-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-log-field-syntax-request'
        description: Update an existing Log Field Syntax
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/json-response'
                - $ref: '#/components/schemas/attribute-based-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Log Field Syntax does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    json-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumjsonSchemaUrn'
        includedSensitiveField:
          type: array
          items:
            type: string
            description: The names of the JSON fields that will be considered sensitive.
        excludedSensitiveField:
          type: array
          items:
            type: string
            description: The names of the JSON fields that will not be considered sensitive.
        description:
          type: string
          description: A description for this Log Field Syntax
        defaultBehavior:
          $ref: '#/components/schemas/EnumdefaultBehaviorProp'
      required:
      - schemas
    EnumjsonSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-field-syntax:json"
    attribute-based-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumattribute-basedSchemaUrn'
        includedSensitiveAttribute:
          type: array
          items:
            type: string
            description: The set of attribute types that will be considered sensitive.
        excludedSensitiveAttribute:
          type: array
          items:
            type: string
            description: The set of attribute types that will not be considered sensitive.
        description:
          type: string
          description: A description for this Log Field Syntax
        defaultBehavior:
          $ref: '#/components/schemas/EnumdefaultBehaviorProp'
      required:
      - schemas
    Enumattribute-basedSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-field-syntax:attribute-based"
    update-log-field-syntax-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumdefaultBehaviorProp:
      type: string
      enum:
      - "preserve"
      - "omit"
      - "redact-entire-value"
      - "redact-value-components"
      - "tokenize-entire-value"
      - "tokenize-value-components"
      description: The default behavior that the server should exhibit when logging fields with this syntax. This may be overridden on a per-field basis.
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
