openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Log Rotation Policy config object
  title: PingData Log Rotation Policy Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-91/pd_ds_use_config_api
tags:
- description: Access log-rotation-policies
  name: log-rotation-policy
paths:
  /log-rotation-policies:
    post:
      summary: Add a new Log Rotation Policy to the config
      operationId: add-log-rotation-policy
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-time-limit-log-rotation-policy-request'
              - $ref: '#/components/schemas/add-fixed-time-log-rotation-policy-request'
              - $ref: '#/components/schemas/add-never-rotate-log-rotation-policy-request'
              - $ref: '#/components/schemas/add-size-limit-log-rotation-policy-request'
        description: Create a new Log Rotation Policy in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-rotation-policy-response'
                - $ref: '#/components/schemas/fixed-time-log-rotation-policy-response'
                - $ref: '#/components/schemas/never-rotate-log-rotation-policy-response'
                - $ref: '#/components/schemas/size-limit-log-rotation-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Log Rotation Policy already exists
      security:
      - basicAuth: []
      tags:
      - log-rotation-policy
  /log-rotation-policies/{log-rotation-policy-name}:
    delete:
      summary: Delete a Log Rotation Policy
      operationId: delete-log-rotation-policy
      parameters:
      - description: Name of the Log Rotation Policy
        explode: false
        in: path
        name: log-rotation-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Rotation Policy does not exist
        "409":
          description: The Log Rotation Policy cannot be deleted
      security:
      - basicAuth: []
      tags:
      - log-rotation-policy
    get:
      summary: Returns a single Log Rotation Policy
      operationId: get-log-rotation-policy
      parameters:
      - description: Name of the Log Rotation Policy
        explode: false
        in: path
        name: log-rotation-policy-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-rotation-policy-response'
                - $ref: '#/components/schemas/fixed-time-log-rotation-policy-response'
                - $ref: '#/components/schemas/never-rotate-log-rotation-policy-response'
                - $ref: '#/components/schemas/size-limit-log-rotation-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Rotation Policy does not exist
      security:
      - basicAuth: []
      tags:
      - log-rotation-policy
    patch:
      summary: Update an existing Log Rotation Policy by name
      operationId: update-log-rotation-policy
      parameters:
      - description: Name of the Log Rotation Policy
        explode: false
        in: path
        name: log-rotation-policy-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Log Rotation Policy
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/time-limit-log-rotation-policy-response'
                - $ref: '#/components/schemas/fixed-time-log-rotation-policy-response'
                - $ref: '#/components/schemas/never-rotate-log-rotation-policy-response'
                - $ref: '#/components/schemas/size-limit-log-rotation-policy-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Log Rotation Policy does not exist
      security:
      - basicAuth: []
      tags:
      - log-rotation-policy
components:
  schemas:
    add-time-limit-log-rotation-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Rotation Policy
      - $ref: '#/components/schemas/time-limit-log-rotation-policy-shared'
      required:
      - policyName
    time-limit-log-rotation-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Rotation Policy
      - $ref: '#/components/schemas/time-limit-log-rotation-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    time-limit-log-rotation-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumtime-limit-log-rotation-policySchemaUrn'
        rotationInterval:
          type: string
          description: >-
              Specifies the time interval between rotations.
        description:
          type: string
          description: >-
              A description for this Log Rotation Policy
      required:
      - schemas
      - rotationInterval
    Enumtime-limit-log-rotation-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-rotation-policy:time-limit"
    add-fixed-time-log-rotation-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Rotation Policy
      - $ref: '#/components/schemas/fixed-time-log-rotation-policy-shared'
      required:
      - policyName
    fixed-time-log-rotation-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Rotation Policy
      - $ref: '#/components/schemas/fixed-time-log-rotation-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    fixed-time-log-rotation-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumfixed-time-log-rotation-policySchemaUrn'
        timeOfDay:
          type: array
          items:
            type: string
          description: >-
              Specifies the time of day at which log rotation should occur.
        description:
          type: string
          description: >-
              A description for this Log Rotation Policy
      required:
      - schemas
      - timeOfDay
    Enumfixed-time-log-rotation-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-rotation-policy:fixed-time"
    add-never-rotate-log-rotation-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Rotation Policy
      - $ref: '#/components/schemas/never-rotate-log-rotation-policy-shared'
      required:
      - policyName
    never-rotate-log-rotation-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Rotation Policy
      - $ref: '#/components/schemas/never-rotate-log-rotation-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    never-rotate-log-rotation-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumnever-rotate-log-rotation-policySchemaUrn'
        description:
          type: string
          description: >-
              A description for this Log Rotation Policy
      required:
      - schemas
    Enumnever-rotate-log-rotation-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-rotation-policy:never-rotate"
    add-size-limit-log-rotation-policy-request:
      allOf:
      - type: object
        properties:
          policyName:
            type: string
            description: >-
                Name of the new Log Rotation Policy
      - $ref: '#/components/schemas/size-limit-log-rotation-policy-shared'
      required:
      - policyName
    size-limit-log-rotation-policy-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Log Rotation Policy
      - $ref: '#/components/schemas/size-limit-log-rotation-policy-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    size-limit-log-rotation-policy-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsize-limit-log-rotation-policySchemaUrn'
        fileSizeLimit:
          type: string
          description: >-
              Specifies the maximum size that a log file can reach before it is rotated.
        description:
          type: string
          description: >-
              A description for this Log Rotation Policy
      required:
      - schemas
      - fileSizeLimit
    Enumsize-limit-log-rotation-policySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-rotation-policy:size-limit"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
