openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Log Field Syntax config object
  title: PingData Log Field Syntax Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access log-field-syntaxes
  name: log-field-syntax
paths:
  /log-field-syntaxes/{log-field-syntax-name}:
    get:
      summary: Returns a single Log Field Syntax
      operationId: get-log-field-syntax
      parameters:
      - description: Name of the Log Field Syntax
        explode: false
        in: path
        name: log-field-syntax-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/json-log-field-syntax-response'
                - $ref: '#/components/schemas/attribute-based-log-field-syntax-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Log Field Syntax does not exist
      security:
      - basicAuth: []
      tags:
      - log-field-syntax
    patch:
      summary: Update an existing Log Field Syntax by name
      operationId: update-log-field-syntax
      parameters:
      - description: Name of the Log Field Syntax
        explode: false
        in: path
        name: log-field-syntax-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Log Field Syntax
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/json-log-field-syntax-response'
                - $ref: '#/components/schemas/attribute-based-log-field-syntax-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Log Field Syntax does not exist
      security:
      - basicAuth: []
      tags:
      - log-field-syntax
components:
  schemas:
    json-log-field-syntax-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumjson-log-field-syntaxSchemaUrn'
          id:
            description: Name of the Log Field Syntax
            type: string
          includedSensitiveField:
            type: array
            items:
              type: string
            description: >-
                The names of the JSON fields that will be considered sensitive.
          excludedSensitiveField:
            type: array
            items:
              type: string
            description: >-
                The names of the JSON fields that will not be considered sensitive.
          description:
            type: string
            description: >-
                A description for this Log Field Syntax
          defaultBehavior:
            $ref: '#/components/schemas/Enumlog-field-syntax-defaultBehaviorProp'
        required:
        - schemas
        - id
    Enumjson-log-field-syntaxSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-field-syntax:json"
    attribute-based-log-field-syntax-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumattribute-based-log-field-syntaxSchemaUrn'
          id:
            description: Name of the Log Field Syntax
            type: string
          includedSensitiveAttribute:
            type: array
            items:
              type: string
            description: >-
                The set of attribute types that will be considered sensitive.
          excludedSensitiveAttribute:
            type: array
            items:
              type: string
            description: >-
                The set of attribute types that will not be considered sensitive.
          description:
            type: string
            description: >-
                A description for this Log Field Syntax
          defaultBehavior:
            $ref: '#/components/schemas/Enumlog-field-syntax-defaultBehaviorProp'
        required:
        - schemas
        - id
    Enumattribute-based-log-field-syntaxSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:log-field-syntax:attribute-based"
    Enumlog-field-syntax-defaultBehaviorProp:
      type: string
      enum:
      - "preserve"
      - "omit"
      - "redact-entire-value"
      - "redact-value-components"
      - "tokenize-entire-value"
      - "tokenize-value-components"
      description: >-
          The default behavior that the server should exhibit when logging fields with this syntax. This may be overridden on a per-field basis.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
