openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Mac Secret Key config object
  title: PingData Mac Secret Key Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access mac-secret-keys
  name: mac-secret-key
paths:
  /mac-secret-keys/{mac-secret-key-name}:
    get:
      summary: Returns a single Mac Secret Key
      operationId: get-mac-secret-key
      parameters:
      - description: Name of the Mac Secret Key to be read
        explode: false
        in: path
        name: mac-secret-key-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mac-secret-key-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Mac Secret Key does not exist
      security:
      - basicAuth: []
      tags:
      - mac-secret-key
    patch:
      summary: Update an existing Mac Secret Key by name
      operationId: update-mac-secret-key
      parameters:
      - description: Name of the Mac Secret Key to be updated
        explode: false
        in: path
        name: mac-secret-key-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Mac Secret Key
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mac-secret-key-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Mac Secret Key does not exist
      security:
      - basicAuth: []
      tags:
      - mac-secret-key
components:
  schemas:
    mac-secret-key-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enummac-secret-keySchemaUrn'
          macAlgorithmName:
            type: string
            description: >-
                The algorithm name used to generate this MAC key, e.g. HmacMD5, HmacSHA1, HMacSHA256, etc.
          keyID:
            type: string
            description: >-
                The unique system-generated identifier for the Secret Key.
          isCompromised:
            type: boolean
            description: >-
                If the key is compromised, an administrator may set this flag to immediately trigger the creation of a new secret key. After the new key is generated, the value of this property will be reset to false.
          symmetricKey:
            type: array
            items:
              type: string
            description: >-
                The symmetric key that is used for both encryption of plain text and decryption of cipher text. This stores the secret key for each server instance encrypted with that server's inter-server certificate.
          keyLengthBits:
            type: integer
            description: >-
                The length of the key in bits.
        required:
        - keyID
        - keyLengthBits
    Enummac-secret-keySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:mac-secret-key"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
