openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Matching Rule config object
  title: PingData Matching Rule Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access matching-rules
  name: matching-rule
paths:
  /matching-rules/{matching-rule-name}:
    get:
      summary: Returns a single Matching Rule
      operationId: get-matching-rule
      parameters:
      - description: Name of the Matching Rule
        explode: false
        in: path
        name: matching-rule-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ordering-matching-rule-response'
                - $ref: '#/components/schemas/approximate-matching-rule-response'
                - $ref: '#/components/schemas/equality-matching-rule-response'
                - $ref: '#/components/schemas/substring-matching-rule-response'
                - $ref: '#/components/schemas/generic-matching-rule-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Matching Rule does not exist
      security:
      - basicAuth: []
      tags:
      - matching-rule
    patch:
      summary: Update an existing Matching Rule by name
      operationId: update-matching-rule
      parameters:
      - description: Name of the Matching Rule
        explode: false
        in: path
        name: matching-rule-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Matching Rule
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ordering-matching-rule-response'
                - $ref: '#/components/schemas/approximate-matching-rule-response'
                - $ref: '#/components/schemas/equality-matching-rule-response'
                - $ref: '#/components/schemas/substring-matching-rule-response'
                - $ref: '#/components/schemas/generic-matching-rule-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Matching Rule does not exist
      security:
      - basicAuth: []
      tags:
      - matching-rule
components:
  schemas:
    ordering-matching-rule-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumordering-matching-ruleSchemaUrn'
          id:
            type: string
            description: >-
                Name of the Matching Rule
          enabled:
            type: boolean
            description: >-
                Indicates whether the Matching Rule is enabled for use.
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - schemas
      - enabled
    Enumordering-matching-ruleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:ordering"
    approximate-matching-rule-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumapproximate-matching-ruleSchemaUrn'
          id:
            type: string
            description: >-
                Name of the Matching Rule
          enabled:
            type: boolean
            description: >-
                Indicates whether the Matching Rule is enabled for use.
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - schemas
      - enabled
    Enumapproximate-matching-ruleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:approximate"
    equality-matching-rule-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumequality-matching-ruleSchemaUrn'
          id:
            type: string
            description: >-
                Name of the Matching Rule
          enabled:
            type: boolean
            description: >-
                Indicates whether the Matching Rule is enabled for use.
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - schemas
      - enabled
    Enumequality-matching-ruleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:equality"
    substring-matching-rule-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumsubstring-matching-ruleSchemaUrn'
          id:
            type: string
            description: >-
                Name of the Matching Rule
          enabled:
            type: boolean
            description: >-
                Indicates whether the Matching Rule is enabled for use.
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - schemas
      - enabled
    Enumsubstring-matching-ruleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:substring"
    generic-matching-rule-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumgeneric-matching-ruleSchemaUrn'
          id:
            type: string
            description: >-
                Name of the Matching Rule
          enabled:
            type: boolean
            description: >-
                Indicates whether the Matching Rule is enabled for use.
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - schemas
      - enabled
    Enumgeneric-matching-ruleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:generic"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
