openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Matching Rule config object
  title: PingData Matching Rule Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access matching-rules
  name: matching-rule
paths:
  /matching-rules:
    post:
      summary: Add a new Matching Rule to the config
      operationId: add-matching-rule
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
        description: Create a new Matching Rule in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Matching Rule already exists
      security:
      - basicAuth: []
      tags:
      - location
  /matching-rules/{matching-rule-name}:
    delete:
      summary: Delete a Matching Rule
      operationId: delete-matching-rule
      parameters:
      - description: Name of the Matching Rule to be deleted
        explode: false
        in: path
        name: matching-rule-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Matching Rule does not exist
        "409":
          description: The Matching Rule cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Matching Rule
      operationId: get-matching-rule
      parameters:
      - description: Name of the Matching Rule to be read
        explode: false
        in: path
        name: matching-rule-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ordering-response'
                - $ref: '#/components/schemas/approximate-response'
                - $ref: '#/components/schemas/equality-response'
                - $ref: '#/components/schemas/substring-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Matching Rule does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Matching Rule by name
      operationId: update-matching-rule
      parameters:
      - description: Name of the Matching Rule to be updated
        explode: false
        in: path
        name: matching-rule-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-matching-rule-request'
        description: Update an existing Matching Rule
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ordering-response'
                - $ref: '#/components/schemas/approximate-response'
                - $ref: '#/components/schemas/equality-response'
                - $ref: '#/components/schemas/substring-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Matching Rule does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    ordering-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumorderingSchemaUrn'
        enabled:
          type: boolean
          description: Indicates whether the Matching Rule is enabled for use.
      required:
      - schemas
      - enabled
    EnumorderingSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:ordering"
    approximate-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumapproximateSchemaUrn'
        enabled:
          type: boolean
          description: Indicates whether the Matching Rule is enabled for use.
      required:
      - schemas
      - enabled
    EnumapproximateSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:approximate"
    equality-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumequalitySchemaUrn'
        enabled:
          type: boolean
          description: Indicates whether the Matching Rule is enabled for use.
      required:
      - schemas
      - enabled
    EnumequalitySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:equality"
    substring-response:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumsubstringSchemaUrn'
        enabled:
          type: boolean
          description: Indicates whether the Matching Rule is enabled for use.
      required:
      - schemas
      - enabled
    EnumsubstringSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:matching-rule:substring"
    update-matching-rule-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
