openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Notification Manager config object
  title: PingData Notification Manager Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access notification-managers
  name: notification-manager
paths:
  /notification-managers:
    get:
      summary: Returns a list of all Notification Manager objects
      operationId: list-notification-managers
      parameters:
      - in: query
        name: filter
        schema:
          type: string
        required: false
        description: SCIM filter
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notification-managerListResponse'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
      security:
      - basicAuth: []
      tags:
      - notification-manager
    post:
      summary: Add a new Notification Manager to the config
      operationId: add-notification-manager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-third-party-notification-manager-request'
        description: Create a new Notification Manager in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/third-party-notification-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Notification Manager already exists
      security:
      - basicAuth: []
      tags:
      - notification-manager
  /notification-managers/{notification-manager-name}:
    delete:
      summary: Delete a Notification Manager
      operationId: delete-notification-manager
      parameters:
      - description: Name of the Notification Manager
        explode: false
        in: path
        name: notification-manager-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Notification Manager does not exist
        "409":
          description: The Notification Manager cannot be deleted
      security:
      - basicAuth: []
      tags:
      - notification-manager
    get:
      summary: Returns a single Notification Manager
      operationId: get-notification-manager
      parameters:
      - description: Name of the Notification Manager
        explode: false
        in: path
        name: notification-manager-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/third-party-notification-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Notification Manager does not exist
      security:
      - basicAuth: []
      tags:
      - notification-manager
    patch:
      summary: Update an existing Notification Manager by name
      operationId: update-notification-manager
      parameters:
      - description: Name of the Notification Manager
        explode: false
        in: path
        name: notification-manager-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Notification Manager
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/third-party-notification-manager-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Notification Manager does not exist
      security:
      - basicAuth: []
      tags:
      - notification-manager
components:
  schemas:
    Enumnotification-manager-transactionNotificationProp:
      type: string
      enum:
      - "individual"
      - "matched-operations"
      - "all-operations"
      description: >-
          Specifies how the operations in an external transaction (e.g. a multi-update extended operation or an LDAP transaction) are notified for this Notification Manager.
    add-third-party-notification-manager-request:
      allOf:
      - type: object
        properties:
          managerName:
            type: string
            description: >-
                Name of the new Notification Manager
      - $ref: '#/components/schemas/third-party-notification-manager-shared'
      required:
      - managerName
    third-party-notification-manager-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Notification Manager
      - $ref: '#/components/schemas/third-party-notification-manager-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
      - transactionNotification
    third-party-notification-manager-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-notification-managerSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Notification Manager.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Notification Manager. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Notification Manager
        enabled:
          type: boolean
          description: >-
              Indicates whether this Notification Manager is enabled within the server.
        subscriptionBaseDN:
          type: string
          description: >-
              Specifies the DN of the entry below which subscription data is stored for this Notification Manager. This needs to be in the backend that has the data to be notified on, and must not be the same entry as the backend base DN. The subscription base DN entry does not need to exist as it will be created by the server.
        transactionNotification:
          $ref: '#/components/schemas/Enumnotification-manager-transactionNotificationProp'
        monitorEntriesEnabled:
          type: boolean
          description: >-
              Enables monitor entries for this Notification Manager.
      required:
      - schemas
      - extensionClass
      - enabled
      - subscriptionBaseDN
    Enumthird-party-notification-managerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:notification-manager:third-party"
    notification-managerListResponse:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: string
        totalResults:
          type: number
        Resources:
          type: array
          items:
            $ref: '#/components/schemas/third-party-notification-manager-response'
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
