openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the OAuth Token Handler config object
  title: PingData OAuth Token Handler Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access oauth-token-handlers
  name: oauth-token-handler
paths:
  /oauth-token-handlers:
    post:
      summary: Add a new OAuth Token Handler to the config
      operationId: add-oauth-token-handler
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-groovy-scripted-oauth-token-handler-request'
              - $ref: '#/components/schemas/add-third-party-oauth-token-handler-request'
        description: Create a new OAuth Token Handler in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/groovy-scripted-oauth-token-handler-response'
                - $ref: '#/components/schemas/third-party-oauth-token-handler-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The OAuth Token Handler already exists
      security:
      - basicAuth: []
      tags:
      - oauth-token-handler
  /oauth-token-handlers/{oauth-token-handler-name}:
    delete:
      summary: Delete a OAuth Token Handler
      operationId: delete-oauth-token-handler
      parameters:
      - description: Name of the OAuth Token Handler
        explode: false
        in: path
        name: oauth-token-handler-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The OAuth Token Handler does not exist
        "409":
          description: The OAuth Token Handler cannot be deleted
      security:
      - basicAuth: []
      tags:
      - oauth-token-handler
    get:
      summary: Returns a single OAuth Token Handler
      operationId: get-oauth-token-handler
      parameters:
      - description: Name of the OAuth Token Handler
        explode: false
        in: path
        name: oauth-token-handler-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/groovy-scripted-oauth-token-handler-response'
                - $ref: '#/components/schemas/third-party-oauth-token-handler-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The OAuth Token Handler does not exist
      security:
      - basicAuth: []
      tags:
      - oauth-token-handler
    patch:
      summary: Update an existing OAuth Token Handler by name
      operationId: update-oauth-token-handler
      parameters:
      - description: Name of the OAuth Token Handler
        explode: false
        in: path
        name: oauth-token-handler-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing OAuth Token Handler
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/groovy-scripted-oauth-token-handler-response'
                - $ref: '#/components/schemas/third-party-oauth-token-handler-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The OAuth Token Handler does not exist
      security:
      - basicAuth: []
      tags:
      - oauth-token-handler
components:
  schemas:
    add-groovy-scripted-oauth-token-handler-request:
      allOf:
      - type: object
        properties:
          handlerName:
            description: Name of the new OAuth Token Handler
            type: string
        required:
        - handlerName
      - $ref: '#/components/schemas/groovy-scripted-oauth-token-handler-shared'
    groovy-scripted-oauth-token-handler-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the OAuth Token Handler
            type: string
        required:
        - id
      - $ref: '#/components/schemas/groovy-scripted-oauth-token-handler-shared'
    groovy-scripted-oauth-token-handler-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scripted-oauth-token-handlerSchemaUrn'
        scriptClass:
          type: string
          description: >-
              The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted OAuth Token Handler.
        scriptArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Scripted OAuth Token Handler. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this OAuth Token Handler
      required:
      - schemas
      - scriptClass
    Enumgroovy-scripted-oauth-token-handlerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:oauth-token-handler:groovy-scripted"
    add-third-party-oauth-token-handler-request:
      allOf:
      - type: object
        properties:
          handlerName:
            description: Name of the new OAuth Token Handler
            type: string
        required:
        - handlerName
      - $ref: '#/components/schemas/third-party-oauth-token-handler-shared'
    third-party-oauth-token-handler-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the OAuth Token Handler
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-oauth-token-handler-shared'
    third-party-oauth-token-handler-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-oauth-token-handlerSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party OAuth Token Handler.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party OAuth Token Handler. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this OAuth Token Handler
      required:
      - schemas
      - extensionClass
    Enumthird-party-oauth-token-handlerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:oauth-token-handler:third-party"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
