openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Password Generator config object
  title: PingData Password Generator Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-100/pd_ds_use_config_api
tags:
- description: Access password-generators
  name: password-generator
paths:
  /password-generators:
    get:
      summary: Returns a list of all Password Generator objects
      operationId: list-password-generators
      parameters:
      - in: query
        name: filter
        schema:
          type: string
        required: false
        description: SCIM filter
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/password-generatorListResponse'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
      security:
      - basicAuth: []
      tags:
      - password-generator
    post:
      summary: Add a new Password Generator to the config
      operationId: add-password-generator
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-random-password-generator-request'
              - $ref: '#/components/schemas/add-groovy-scripted-password-generator-request'
              - $ref: '#/components/schemas/add-passphrase-password-generator-request'
              - $ref: '#/components/schemas/add-third-party-password-generator-request'
        description: Create a new Password Generator in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-password-generator-response'
                - $ref: '#/components/schemas/groovy-scripted-password-generator-response'
                - $ref: '#/components/schemas/passphrase-password-generator-response'
                - $ref: '#/components/schemas/third-party-password-generator-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Password Generator already exists
      security:
      - basicAuth: []
      tags:
      - password-generator
  /password-generators/{password-generator-name}:
    delete:
      summary: Delete a Password Generator
      operationId: delete-password-generator
      parameters:
      - description: Name of the Password Generator
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Password Generator does not exist
        "409":
          description: The Password Generator cannot be deleted
      security:
      - basicAuth: []
      tags:
      - password-generator
    get:
      summary: Returns a single Password Generator
      operationId: get-password-generator
      parameters:
      - description: Name of the Password Generator
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-password-generator-response'
                - $ref: '#/components/schemas/groovy-scripted-password-generator-response'
                - $ref: '#/components/schemas/passphrase-password-generator-response'
                - $ref: '#/components/schemas/third-party-password-generator-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Password Generator does not exist
      security:
      - basicAuth: []
      tags:
      - password-generator
    patch:
      summary: Update an existing Password Generator by name
      operationId: update-password-generator
      parameters:
      - description: Name of the Password Generator
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Password Generator
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-password-generator-response'
                - $ref: '#/components/schemas/groovy-scripted-password-generator-response'
                - $ref: '#/components/schemas/passphrase-password-generator-response'
                - $ref: '#/components/schemas/third-party-password-generator-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Password Generator does not exist
      security:
      - basicAuth: []
      tags:
      - password-generator
components:
  schemas:
    add-random-password-generator-request:
      allOf:
      - type: object
        properties:
          generatorName:
            type: string
            description: >-
                Name of the new Password Generator
      - $ref: '#/components/schemas/random-password-generator-shared'
      required:
      - generatorName
    random-password-generator-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Password Generator
      - $ref: '#/components/schemas/random-password-generator-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    random-password-generator-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumrandom-password-generatorSchemaUrn'
        passwordCharacterSet:
          type: array
          items:
            type: string
          description: >-
              Specifies one or more named character sets.
        passwordFormat:
          type: string
          description: >-
              Specifies the format to use for the generated password.
        description:
          type: string
          description: >-
              A description for this Password Generator
        enabled:
          type: boolean
          description: >-
              Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - passwordCharacterSet
      - passwordFormat
      - enabled
    Enumrandom-password-generatorSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:random"
    add-passphrase-password-generator-request:
      allOf:
      - type: object
        properties:
          generatorName:
            type: string
            description: >-
                Name of the new Password Generator
      - $ref: '#/components/schemas/passphrase-password-generator-shared'
      required:
      - generatorName
    passphrase-password-generator-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Password Generator
      - $ref: '#/components/schemas/passphrase-password-generator-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    passphrase-password-generator-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumpassphrase-password-generatorSchemaUrn'
        dictionaryFile:
          type: string
          description: >-
              The path to the dictionary file that will be used to obtain the words for use in generated passwords.
        minimumPasswordCharacters:
          type: integer
          description: >-
              The minimum number of characters that generated passwords will be required to have.
        minimumPasswordWords:
          type: integer
          description: >-
              The minimum number of words that must be concatenated in the course of generating a password.
        capitalizeWords:
          type: boolean
          description: >-
              Indicates whether to capitalize each word used in the generated password.
        description:
          type: string
          description: >-
              A description for this Password Generator
        enabled:
          type: boolean
          description: >-
              Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - dictionaryFile
      - enabled
    Enumpassphrase-password-generatorSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:passphrase"
    add-groovy-scripted-password-generator-request:
      allOf:
      - type: object
        properties:
          generatorName:
            type: string
            description: >-
                Name of the new Password Generator
      - $ref: '#/components/schemas/groovy-scripted-password-generator-shared'
      required:
      - generatorName
    groovy-scripted-password-generator-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Password Generator
      - $ref: '#/components/schemas/groovy-scripted-password-generator-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    groovy-scripted-password-generator-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scripted-password-generatorSchemaUrn'
        scriptClass:
          type: string
          description: >-
              The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted Password Generator.
        scriptArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Scripted Password Generator. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Password Generator
        enabled:
          type: boolean
          description: >-
              Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - scriptClass
      - enabled
    Enumgroovy-scripted-password-generatorSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:groovy-scripted"
    add-third-party-password-generator-request:
      allOf:
      - type: object
        properties:
          generatorName:
            type: string
            description: >-
                Name of the new Password Generator
      - $ref: '#/components/schemas/third-party-password-generator-shared'
      required:
      - generatorName
    third-party-password-generator-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Password Generator
      - $ref: '#/components/schemas/third-party-password-generator-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    third-party-password-generator-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-password-generatorSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Password Generator.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Password Generator. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Password Generator
        enabled:
          type: boolean
          description: >-
              Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-party-password-generatorSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:third-party"
    password-generatorListResponse:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: string
        totalResults:
          type: number
        Resources:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/random-password-generator-response'
            - $ref: '#/components/schemas/passphrase-password-generator-response'
            - $ref: '#/components/schemas/groovy-scripted-password-generator-response'
            - $ref: '#/components/schemas/third-party-password-generator-response'
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
