openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Password Generator config object
  title: PingData Password Generator Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access password-generators
  name: password-generator
paths:
  /password-generators:
    post:
      summary: Add a new Password Generator to the config
      operationId: add-password-generator
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-random-request'
              - $ref: '#/components/schemas/add-groovy-scripted-request'
              - $ref: '#/components/schemas/add-passphrase-request'
              - $ref: '#/components/schemas/add-third-party-request'
        description: Create a new Password Generator in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/passphrase-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Password Generator already exists
      security:
      - basicAuth: []
      tags:
      - location
  /password-generators/{password-generator-name}:
    delete:
      summary: Delete a Password Generator
      operationId: delete-password-generator
      parameters:
      - description: Name of the Password Generator to be deleted
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Password Generator does not exist
        "409":
          description: The Password Generator cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Password Generator
      operationId: get-password-generator
      parameters:
      - description: Name of the Password Generator to be read
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/passphrase-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Password Generator does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Password Generator by name
      operationId: update-password-generator
      parameters:
      - description: Name of the Password Generator to be updated
        explode: false
        in: path
        name: password-generator-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-password-generator-request'
        description: Update an existing Password Generator
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/random-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/passphrase-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Password Generator does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    add-random-request:
      allOf:
      - type: object
        properties:
          generatorName:
            description: Name of the new Password Generator
            type: string
        required:
        - generatorName
      - $ref: '#/components/schemas/random-shared'
    random-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Password Generator
            type: string
        required:
        - id
      - $ref: '#/components/schemas/random-shared'
    random-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumrandomSchemaUrn'
        passwordCharacterSet:
          type: array
          items:
            type: string
            description: Specifies one or more named character sets.
        passwordFormat:
          type: string
          description: Specifies the format to use for the generated password.
        description:
          type: string
          description: A description for this Password Generator
        enabled:
          type: boolean
          description: Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - passwordCharacterSet
      - passwordFormat
      - enabled
    EnumrandomSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:random"
    add-groovy-scripted-request:
      allOf:
      - type: object
        properties:
          generatorName:
            description: Name of the new Password Generator
            type: string
        required:
        - generatorName
      - $ref: '#/components/schemas/groovy-scripted-shared'
    groovy-scripted-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Password Generator
            type: string
        required:
        - id
      - $ref: '#/components/schemas/groovy-scripted-shared'
    groovy-scripted-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scriptedSchemaUrn'
        scriptClass:
          type: string
          description: The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted Password Generator.
        scriptArgument:
          type: array
          items:
            type: string
            description: The set of arguments used to customize the behavior for the Scripted Password Generator. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: A description for this Password Generator
        enabled:
          type: boolean
          description: Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - scriptClass
      - enabled
    Enumgroovy-scriptedSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:groovy-scripted"
    add-passphrase-request:
      allOf:
      - type: object
        properties:
          generatorName:
            description: Name of the new Password Generator
            type: string
        required:
        - generatorName
      - $ref: '#/components/schemas/passphrase-shared'
    passphrase-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Password Generator
            type: string
        required:
        - id
      - $ref: '#/components/schemas/passphrase-shared'
    passphrase-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumpassphraseSchemaUrn'
        dictionaryFile:
          type: string
          description: The path to the dictionary file that will be used to obtain the words for use in generated passwords.
        minimumPasswordCharacters:
          type: integer
          description: The minimum number of characters that generated passwords will be required to have.
        minimumPasswordWords:
          type: integer
          description: The minimum number of words that must be concatenated in the course of generating a password.
        capitalizeWords:
          type: boolean
          description: Indicates whether to capitalize each word used in the generated password.
        description:
          type: string
          description: A description for this Password Generator
        enabled:
          type: boolean
          description: Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - dictionaryFile
      - enabled
    EnumpassphraseSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:passphrase"
    add-third-party-request:
      allOf:
      - type: object
        properties:
          generatorName:
            description: Name of the new Password Generator
            type: string
        required:
        - generatorName
      - $ref: '#/components/schemas/third-party-shared'
    third-party-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Password Generator
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-shared'
    third-party-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-partySchemaUrn'
        extensionClass:
          type: string
          description: The fully-qualified name of the Java class providing the logic for the Third Party Password Generator.
        extensionArgument:
          type: array
          items:
            type: string
            description: The set of arguments used to customize the behavior for the Third Party Password Generator. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: A description for this Password Generator
        enabled:
          type: boolean
          description: Indicates whether the Password Generator is enabled for use.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-partySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:password-generator:third-party"
    update-password-generator-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
