openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Root DSE Backend config object
  title: PingData Root DSE Backend Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
tags:
- description: Access the Root DSE Backend
  name: root-dse-backend
paths:
  /root-dse-backend:
    get:
      summary: Returns a single Root DSE Backend
      operationId: get-root-dse-backend
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root-dse-backend-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Root DSE Backend does not exist
      security:
      - basicAuth: []
      tags:
      - root-dse-backend
    patch:
      summary: Update an existing Root DSE Backend by name
      operationId: update-root-dse-backend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Root DSE Backend
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root-dse-backend-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Root DSE Backend does not exist
      security:
      - basicAuth: []
      tags:
      - root-dse-backend
components:
  schemas:
    root-dse-backend-response:
      allOf:
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumroot-dse-backendSchemaUrn'
          subordinateBaseDN:
            type: array
            items:
              type: string
            description: >-
                Specifies the set of base DNs used for singleLevel, wholeSubtree, and subordinateSubtree searches based at the root DSE.
          additionalSupportedControlOID:
            type: array
            items:
              type: string
            description: >-
                Specifies an additional OID that should appear in the list of supportedControl values in the server's root DSE.
          showAllAttributes:
            type: boolean
            description: >-
                Indicates whether all attributes in the root DSE are to be treated like user attributes (and therefore returned to clients by default) regardless of the Directory Server schema configuration.
          useLegacyVendorVersion:
            type: boolean
            description: >-
                Indicates whether the server's root DSE should reflect current or legacy values for the vendorName and vendorVersion attributes.
      - $ref: '#/components/schemas/meta'
      required:
      - showAllAttributes
    Enumroot-dse-backendSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:root-dse-backend"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
