openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Root DN config object
  title: PingData Root DN Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access the Root DN
  name: root-dn
paths:
  /root-dn:
    get:
      summary: Returns a single Root DN
      operationId: get-root-dn
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root-dn-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Root DN does not exist
      security:
      - basicAuth: []
      tags:
      - root-dn
    patch:
      summary: Update an existing Root DN by name
      operationId: update-root-dn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Root DN
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root-dn-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Root DN does not exist
      security:
      - basicAuth: []
      tags:
      - root-dn
components:
  schemas:
    root-dn-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumroot-dnSchemaUrn'
          defaultRootPrivilegeName:
            type: array
            items:
              $ref: '#/components/schemas/Enumroot-dn-defaultRootPrivilegeNameProp'
    Enumroot-dnSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:root-dn"
    Enumroot-dn-defaultRootPrivilegeNameProp:
      type: string
      enum:
      - "audit-data-security"
      - "bypass-acl"
      - "bypass-read-acl"
      - "modify-acl"
      - "config-read"
      - "config-write"
      - "jmx-read"
      - "jmx-write"
      - "jmx-notify"
      - "ldif-import"
      - "ldif-export"
      - "backend-backup"
      - "backend-restore"
      - "server-shutdown"
      - "server-restart"
      - "proxied-auth"
      - "disconnect-client"
      - "password-reset"
      - "update-schema"
      - "privilege-change"
      - "unindexed-search"
      - "unindexed-search-with-control"
      - "bypass-pw-policy"
      - "lockdown-mode"
      - "stream-values"
      - "third-party-task"
      - "use-admin-session"
      - "soft-delete-read"
      - "metrics-read"
      - "remote-log-read"
      - "manage-topology"
      - "permit-get-password-policy-state-issues"
      - "permit-proxied-mschapv2-details"
      - "permit-externally-processed-authentication"
      - "permit-export-reversible-passwords"
      - "permit-forwarding-client-connection-policy"
      - "exec-task"
      - "collect-support-data"
      - "file-servlet-access"
      - "permit-replace-certificate-request"
      description: >-
          Specifies the names of the privileges that root users will be granted by default.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
