openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the SCIM Attribute config object
  title: PingData SCIM Attribute Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access scim-attributes
  name: scim-attribute
paths:
  /scim-attributes:
    post:
      summary: Add a new SCIM Attribute to the config
      operationId: add-scim-attribute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-scim-attribute-request'
        description: Create a new SCIM Attribute in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-attribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The SCIM Attribute already exists
      security:
      - basicAuth: []
      tags:
      - scim-attribute
  /scim-attributes/{scim-attribute-name}:
    delete:
      summary: Delete a SCIM Attribute
      operationId: delete-scim-attribute
      parameters:
      - description: Name of the SCIM Attribute to be deleted
        explode: false
        in: path
        name: scim-attribute-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Attribute does not exist
        "409":
          description: The SCIM Attribute cannot be deleted
      security:
      - basicAuth: []
      tags:
      - scim-attribute
    get:
      summary: Returns a single SCIM Attribute
      operationId: get-scim-attribute
      parameters:
      - description: Name of the SCIM Attribute to be read
        explode: false
        in: path
        name: scim-attribute-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-attribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Attribute does not exist
      security:
      - basicAuth: []
      tags:
      - scim-attribute
    patch:
      summary: Update an existing SCIM Attribute by name
      operationId: update-scim-attribute
      parameters:
      - description: Name of the SCIM Attribute to be updated
        explode: false
        in: path
        name: scim-attribute-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing SCIM Attribute
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-attribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The SCIM Attribute does not exist
      security:
      - basicAuth: []
      tags:
      - scim-attribute
components:
  schemas:
    add-scim-attribute-request:
      allOf:
      - type: object
        properties:
          attributeName:
            description: Name of the new SCIM Attribute
            type: string
        required:
        - attributeName
      - $ref: '#/components/schemas/scim-attribute-shared'
    scim-attribute-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the SCIM Attribute
            type: string
        required:
        - id
      - $ref: '#/components/schemas/scim-attribute-shared'
    scim-attribute-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumscim-attributeSchemaUrn'
        description:
          type: string
          description: >-
              A description for this SCIM Attribute
        name:
          type: string
          description: >-
              The name of the attribute.
        type:
          $ref: '#/components/schemas/Enumscim-attribute-typeProp'
        required:
          type: boolean
          description: >-
              Specifies whether this attribute is required.
        caseExact:
          type: boolean
          description: >-
              Specifies whether the attribute values are case sensitive.
        multiValued:
          type: boolean
          description: >-
              Specifies whether this attribute may have multiple values.
        canonicalValue:
          type: array
          items:
            type: string
          description: >-
              Specifies the suggested canonical type values for the attribute.
        mutability:
          $ref: '#/components/schemas/Enumscim-attribute-mutabilityProp'
        returned:
          $ref: '#/components/schemas/Enumscim-attribute-returnedProp'
        referenceType:
          type: array
          items:
            type: string
          description: >-
              Specifies the SCIM resource types that may be referenced. This property is only applicable for attributes that are of type 'reference'. Valid values are: A SCIM resource type (e.g., 'User' or 'Group'), 'external' - indicating the resource is an external resource (e.g., such as a photo), or 'uri' - indicating that the reference is to a service endpoint or an identifier (such as a schema urn).
      required:
      - name
      - type
      - required
      - caseExact
      - multiValued
      - mutability
      - returned
    Enumscim-attributeSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:scim-attribute"
    Enumscim-attribute-mutabilityProp:
      type: string
      enum:
      - "read-only"
      - "read-write"
      - "immutable"
      - "write-only"
      description: >-
          Specifies the circumstances under which the values of the attribute can be written.
    Enumscim-attribute-typeProp:
      type: string
      enum:
      - "string"
      - "boolean"
      - "datetime"
      - "decimal"
      - "integer"
      - "binary"
      - "reference"
      - "complex"
      description: >-
          Specifies the data type for this attribute.
    Enumscim-attribute-returnedProp:
      type: string
      enum:
      - "by-default"
      - "upon-request"
      - "always"
      - "never"
      description: >-
          Specifies the circumstances under which the values of the attribute are returned in response to a request.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
