openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the SCIM Resource Type config object
  title: PingData SCIM Resource Type Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access scim-resource-types
  name: scim-resource-type
paths:
  /scim-resource-types:
    post:
      summary: Add a new SCIM Resource Type to the config
      operationId: add-scim-resource-type
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
        description: Create a new SCIM Resource Type in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The SCIM Resource Type already exists
      security:
      - basicAuth: []
      tags:
      - location
  /scim-resource-types/{scim-resource-type-name}:
    delete:
      summary: Delete a SCIM Resource Type
      operationId: delete-scim-resource-type
      parameters:
      - description: Name of the SCIM Resource Type to be deleted
        explode: false
        in: path
        name: scim-resource-type-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Resource Type does not exist
        "409":
          description: The SCIM Resource Type cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single SCIM Resource Type
      operationId: get-scim-resource-type
      parameters:
      - description: Name of the SCIM Resource Type to be read
        explode: false
        in: path
        name: scim-resource-type-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Resource Type does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing SCIM Resource Type by name
      operationId: update-scim-resource-type
      parameters:
      - description: Name of the SCIM Resource Type to be updated
        explode: false
        in: path
        name: scim-resource-type-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-scim-resource-type-request'
        description: Update an existing SCIM Resource Type
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The SCIM Resource Type does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    update-scim-resource-type-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
