openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the SCIM Subattribute config object
  title: PingData SCIM Subattribute Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access scim-subattributes
  name: scim-subattribute
paths:
  /scim-subattributes:
    post:
      summary: Add a new SCIM Subattribute to the config
      operationId: add-scim-subattribute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-scim-subattribute-request'
        description: Create a new SCIM Subattribute in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-subattribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The SCIM Subattribute already exists
      security:
      - basicAuth: []
      tags:
      - scim-subattribute
  /scim-subattributes/{scim-subattribute-name}:
    delete:
      summary: Delete a SCIM Subattribute
      operationId: delete-scim-subattribute
      parameters:
      - description: Name of the SCIM Subattribute to be deleted
        explode: false
        in: path
        name: scim-subattribute-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Subattribute does not exist
        "409":
          description: The SCIM Subattribute cannot be deleted
      security:
      - basicAuth: []
      tags:
      - scim-subattribute
    get:
      summary: Returns a single SCIM Subattribute
      operationId: get-scim-subattribute
      parameters:
      - description: Name of the SCIM Subattribute to be read
        explode: false
        in: path
        name: scim-subattribute-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-subattribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Subattribute does not exist
      security:
      - basicAuth: []
      tags:
      - scim-subattribute
    patch:
      summary: Update an existing SCIM Subattribute by name
      operationId: update-scim-subattribute
      parameters:
      - description: Name of the SCIM Subattribute to be updated
        explode: false
        in: path
        name: scim-subattribute-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing SCIM Subattribute
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-subattribute-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The SCIM Subattribute does not exist
      security:
      - basicAuth: []
      tags:
      - scim-subattribute
components:
  schemas:
    add-scim-subattribute-request:
      allOf:
      - type: object
        properties:
          subattributeName:
            description: Name of the new SCIM Subattribute
            type: string
        required:
        - subattributeName
      - $ref: '#/components/schemas/scim-subattribute-shared'
    scim-subattribute-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the SCIM Subattribute
            type: string
        required:
        - id
      - $ref: '#/components/schemas/scim-subattribute-shared'
    scim-subattribute-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumscim-subattributeSchemaUrn'
        description:
          type: string
          description: >-
              A description for this SCIM Subattribute
        type:
          $ref: '#/components/schemas/Enumscim-subattribute-typeProp'
        required:
          type: boolean
          description: >-
              Specifies whether this sub-attribute is required.
        caseExact:
          type: boolean
          description: >-
              Specifies whether the sub-attribute values are case sensitive.
        multiValued:
          type: boolean
          description: >-
              Specifies whether this attribute may have multiple values.
        canonicalValue:
          type: array
          items:
            type: string
          description: >-
              Specifies the suggested canonical type values for the sub-attribute.
        mutability:
          $ref: '#/components/schemas/Enumscim-subattribute-mutabilityProp'
        returned:
          $ref: '#/components/schemas/Enumscim-subattribute-returnedProp'
        referenceType:
          type: array
          items:
            type: string
          description: >-
              Specifies the SCIM resource types that may be referenced. This property is only applicable for sub-attributes that are of type 'reference'. Valid values are: A SCIM resource type (e.g., 'User' or 'Group'), 'external' - indicating the resource is an external resource (e.g., such as a photo), or 'uri' - indicating that the reference is to a service endpoint or an identifier (such as a schema urn).
      required:
      - type
      - required
      - caseExact
      - multiValued
      - mutability
      - returned
    Enumscim-subattributeSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:scim-subattribute"
    Enumscim-subattribute-mutabilityProp:
      type: string
      enum:
      - "read-only"
      - "read-write"
      - "immutable"
      - "write-only"
      description: >-
          Specifies the circumstances under which the values of the sub-attribute can be written.
    Enumscim-subattribute-typeProp:
      type: string
      enum:
      - "string"
      - "boolean"
      - "datetime"
      - "decimal"
      - "integer"
      - "binary"
      - "reference"
      description: >-
          Specifies the data type for this sub-attribute.
    Enumscim-subattribute-returnedProp:
      type: string
      enum:
      - "by-default"
      - "upon-request"
      - "always"
      - "never"
      description: >-
          Specifies the circumstances under which the values of the sub-attribute are returned in response to a request.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
