openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the SCIM Schema config object
  title: PingData SCIM Schema Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access scim-schemas
  name: scim-schema
paths:
  /scim-schemas:
    post:
      summary: Add a new SCIM Schema to the config
      operationId: add-scim-schema
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-scim-schema-request'
        description: Create a new SCIM Schema in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-schema-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The SCIM Schema already exists
      security:
      - basicAuth: []
      tags:
      - scim-schema
  /scim-schemas/{scim-schema-name}:
    delete:
      summary: Delete a SCIM Schema
      operationId: delete-scim-schema
      parameters:
      - description: Name of the SCIM Schema to be deleted
        explode: false
        in: path
        name: scim-schema-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Schema does not exist
        "409":
          description: The SCIM Schema cannot be deleted
      security:
      - basicAuth: []
      tags:
      - scim-schema
    get:
      summary: Returns a single SCIM Schema
      operationId: get-scim-schema
      parameters:
      - description: Name of the SCIM Schema to be read
        explode: false
        in: path
        name: scim-schema-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-schema-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The SCIM Schema does not exist
      security:
      - basicAuth: []
      tags:
      - scim-schema
    patch:
      summary: Update an existing SCIM Schema by name
      operationId: update-scim-schema
      parameters:
      - description: Name of the SCIM Schema to be updated
        explode: false
        in: path
        name: scim-schema-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing SCIM Schema
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scim-schema-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The SCIM Schema does not exist
      security:
      - basicAuth: []
      tags:
      - scim-schema
components:
  schemas:
    add-scim-schema-request:
      allOf:
      - type: object
        properties:
          schemaName:
            description: Name of the new SCIM Schema
            type: string
        required:
        - schemaName
      - $ref: '#/components/schemas/scim-schema-shared'
    scim-schema-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the SCIM Schema
            type: string
        required:
        - id
      - $ref: '#/components/schemas/scim-schema-shared'
      - $ref: '#/components/schemas/meta'
    scim-schema-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumscim-schemaSchemaUrn'
        description:
          type: string
          description: >-
              A description for this SCIM Schema
        schemaURN:
          type: string
          description: >-
              The URN which identifies this SCIM Schema.
        displayName:
          type: string
          description: >-
              The human readable name for this SCIM Schema.
      required:
      - schemaURN
    Enumscim-schemaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:scim-schema"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
