openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Search Reference Criteria config object
  title: PingData Search Reference Criteria Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access search-reference-criteria
  name: search-reference-criteria
paths:
  /search-reference-criteria:
    post:
      summary: Add a new Search Reference Criteria to the config
      operationId: add-search-reference-criteria
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-simple-search-reference-criteria-request'
              - $ref: '#/components/schemas/add-aggregate-search-reference-criteria-request'
              - $ref: '#/components/schemas/add-third-party-search-reference-criteria-request'
        description: Create a new Search Reference Criteria in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-reference-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-reference-criteria-response'
                - $ref: '#/components/schemas/third-party-search-reference-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Search Reference Criteria already exists
      security:
      - basicAuth: []
      tags:
      - search-reference-criteria
  /search-reference-criteria/{search-reference-criteria-name}:
    delete:
      summary: Delete a Search Reference Criteria
      operationId: delete-search-reference-criteria
      parameters:
      - description: Name of the Search Reference Criteria
        explode: false
        in: path
        name: search-reference-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Search Reference Criteria does not exist
        "409":
          description: The Search Reference Criteria cannot be deleted
      security:
      - basicAuth: []
      tags:
      - search-reference-criteria
    get:
      summary: Returns a single Search Reference Criteria
      operationId: get-search-reference-criteria
      parameters:
      - description: Name of the Search Reference Criteria
        explode: false
        in: path
        name: search-reference-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-reference-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-reference-criteria-response'
                - $ref: '#/components/schemas/third-party-search-reference-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Search Reference Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - search-reference-criteria
    patch:
      summary: Update an existing Search Reference Criteria by name
      operationId: update-search-reference-criteria
      parameters:
      - description: Name of the Search Reference Criteria
        explode: false
        in: path
        name: search-reference-criteria-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Search Reference Criteria
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-reference-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-reference-criteria-response'
                - $ref: '#/components/schemas/third-party-search-reference-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Search Reference Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - search-reference-criteria
components:
  schemas:
    add-simple-search-reference-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            type: string
            description: >-
                Name of the new Search Reference Criteria
      - $ref: '#/components/schemas/simple-search-reference-criteria-shared'
      required:
      - criteriaName
    simple-search-reference-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Search Reference Criteria
      - $ref: '#/components/schemas/simple-search-reference-criteria-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    simple-search-reference-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsimple-search-reference-criteriaSchemaUrn'
        requestCriteria:
          type: string
          description: >-
              Specifies a request criteria object that must match the associated request for references included in this Simple Search Reference Criteria.
        allIncludedReferenceControl:
          type: array
          items:
            type: string
          description: >-
              Specifies the OID of a control that must be present in search result references included in this Simple Search Reference Criteria. If any control OIDs are provided, then the reference must contain all of those controls.
        anyIncludedReferenceControl:
          type: array
          items:
            type: string
          description: >-
              Specifies the OID of a control that may be present in search result references included in this Simple Search Reference Criteria. If any control OIDs are provided, then the reference must contain at least one of those controls.
        notAllIncludedReferenceControl:
          type: array
          items:
            type: string
          description: >-
              Specifies the OID of a control that should not be present in search result references included in this Simple Search Reference Criteria. If any control OIDs are provided, then the reference must not contain at least one of those controls (that is, it may contain zero or more of those controls, but not all of them).
        noneIncludedReferenceControl:
          type: array
          items:
            type: string
          description: >-
              Specifies the OID of a control that must not be present in search result references included in this Simple Search Reference Criteria. If any control OIDs are provided, then the reference must not contain any of those controls.
        description:
          type: string
          description: >-
              A description for this Search Reference Criteria
      required:
      - schemas
    Enumsimple-search-reference-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-reference-criteria:simple"
    add-aggregate-search-reference-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            type: string
            description: >-
                Name of the new Search Reference Criteria
      - $ref: '#/components/schemas/aggregate-search-reference-criteria-shared'
      required:
      - criteriaName
    aggregate-search-reference-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Search Reference Criteria
      - $ref: '#/components/schemas/aggregate-search-reference-criteria-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    aggregate-search-reference-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumaggregate-search-reference-criteriaSchemaUrn'
        allIncludedSearchReferenceCriteria:
          type: array
          items:
            type: string
          description: >-
              Specifies a search reference criteria object that must match the associated search result reference in order to match the aggregate search reference criteria. If one or more all-included search reference criteria objects are provided, then a search result reference must match all of them in order to match the aggregate search reference criteria.
        anyIncludedSearchReferenceCriteria:
          type: array
          items:
            type: string
          description: >-
              Specifies a search reference criteria object that may match the associated search result reference in order to match the aggregate search reference criteria. If one or more any-included search reference criteria objects are provided, then a search result reference must match at least one of them in order to match the aggregate search reference criteria.
        notAllIncludedSearchReferenceCriteria:
          type: array
          items:
            type: string
          description: >-
              Specifies a search reference criteria object that should not match the associated search result reference in order to match the aggregate search reference criteria. If one or more not-all-included search reference criteria objects are provided, then a search result reference must not match all of them (that is, it may match zero or more of them, but it must not match all of them) in order to match the aggregate search reference criteria.
        noneIncludedSearchReferenceCriteria:
          type: array
          items:
            type: string
          description: >-
              Specifies a search reference criteria object that must not match the associated search result reference in order to match the aggregate search reference criteria. If one or more none-included search reference criteria objects are provided, then a search result reference must not match any of them in order to match the aggregate search reference criteria.
        description:
          type: string
          description: >-
              A description for this Search Reference Criteria
      required:
      - schemas
    Enumaggregate-search-reference-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-reference-criteria:aggregate"
    add-third-party-search-reference-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            type: string
            description: >-
                Name of the new Search Reference Criteria
      - $ref: '#/components/schemas/third-party-search-reference-criteria-shared'
      required:
      - criteriaName
    third-party-search-reference-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Search Reference Criteria
      - $ref: '#/components/schemas/third-party-search-reference-criteria-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    third-party-search-reference-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-search-reference-criteriaSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Search Reference Criteria.
        extensionArgument:
          type: array
          items:
            type: string
          description: >-
              The set of arguments used to customize the behavior for the Third Party Search Reference Criteria. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Search Reference Criteria
      required:
      - schemas
      - extensionClass
    Enumthird-party-search-reference-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-reference-criteria:third-party"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
