openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Search Entry Criteria config object
  title: PingData Search Entry Criteria Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access search-entry-criteria
  name: search-entry-criteria
paths:
  /search-entry-criteria:
    post:
      summary: Add a new Search Entry Criteria to the config
      operationId: add-search-entry-criteria
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-simple-search-entry-criteria-request'
              - $ref: '#/components/schemas/add-aggregate-search-entry-criteria-request'
              - $ref: '#/components/schemas/add-third-party-search-entry-criteria-request'
        description: Create a new Search Entry Criteria in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-entry-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-entry-criteria-response'
                - $ref: '#/components/schemas/third-party-search-entry-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Search Entry Criteria already exists
      security:
      - basicAuth: []
      tags:
      - search-entry-criteria
  /search-entry-criteria/{search-entry-criteria-name}:
    delete:
      summary: Delete a Search Entry Criteria
      operationId: delete-search-entry-criteria
      parameters:
      - description: Name of the Search Entry Criteria to be deleted
        explode: false
        in: path
        name: search-entry-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Search Entry Criteria does not exist
        "409":
          description: The Search Entry Criteria cannot be deleted
      security:
      - basicAuth: []
      tags:
      - search-entry-criteria
    get:
      summary: Returns a single Search Entry Criteria
      operationId: get-search-entry-criteria
      parameters:
      - description: Name of the Search Entry Criteria to be read
        explode: false
        in: path
        name: search-entry-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-entry-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-entry-criteria-response'
                - $ref: '#/components/schemas/third-party-search-entry-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Search Entry Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - search-entry-criteria
    patch:
      summary: Update an existing Search Entry Criteria by name
      operationId: update-search-entry-criteria
      parameters:
      - description: Name of the Search Entry Criteria to be updated
        explode: false
        in: path
        name: search-entry-criteria-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Search Entry Criteria
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/simple-search-entry-criteria-response'
                - $ref: '#/components/schemas/aggregate-search-entry-criteria-response'
                - $ref: '#/components/schemas/third-party-search-entry-criteria-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Search Entry Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - search-entry-criteria
components:
  schemas:
    add-simple-search-entry-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Search Entry Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/simple-search-entry-criteria-shared'
    simple-search-entry-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Search Entry Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/simple-search-entry-criteria-shared'
    simple-search-entry-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumsimple-search-entry-criteriaSchemaUrn'
        requestCriteria:
          type: string
          description: >-
              Specifies a request criteria object that must match the associated request for entries included in this Simple Search Entry Criteria. of them.
        allIncludedEntryControl:
          type: array
          items:
            type: string
            description: >-
                Specifies the OID of a control that must be present in search result entries included in this Simple Search Entry Criteria. If any control OIDs are provided, then the entry must contain all of those controls.
        anyIncludedEntryControl:
          type: array
          items:
            type: string
            description: >-
                Specifies the OID of a control that may be present in search result entries included in this Simple Search Entry Criteria. If any control OIDs are provided, then the entry must contain at least one of those controls.
        notAllIncludedEntryControl:
          type: array
          items:
            type: string
            description: >-
                Specifies the OID of a control that should not be present in search result entries included in this Simple Search Entry Criteria. If any control OIDs are provided, then the entry must not contain at least one of those controls (that is, it may contain zero or more of those controls, but not all of them).
        noneIncludedEntryControl:
          type: array
          items:
            type: string
            description: >-
                Specifies the OID of a control that must not be present in search result entries included in this Simple Search Entry Criteria. If any control OIDs are provided, then the entry must not contain any of those controls.
        includedEntryBaseDN:
          type: array
          items:
            type: string
            description: >-
                Specifies a base DN below which entries included in this Simple Search Entry Criteria may exist.
        excludedEntryBaseDN:
          type: array
          items:
            type: string
            description: >-
                Specifies a base DN below which entries included in this Simple Search Entry Criteria may not exist.
        allIncludedEntryFilter:
          type: array
          items:
            type: string
            description: >-
                Specifies a search filter that must match search result entries included in this Simple Search Entry Criteria. Note that this matching will be performed against the entry that is actually returned to the client and may not reflect the complete entry stored in the server. If any filters are provided, then the returned entry must match all of those filters.
        anyIncludedEntryFilter:
          type: array
          items:
            type: string
            description: >-
                Specifies a search filter that may match search result entries included in this Simple Search Entry Criteria. Note that this matching will be performed against the entry that is actually returned to the client and may not reflect the complete entry stored in the server. If any filters are provided, then the entry must match at least one of those filters.
        notAllIncludedEntryFilter:
          type: array
          items:
            type: string
            description: >-
                Specifies a search filter that should not match search result entries included in this Simple Search Entry Criteria. Note that this matching will be performed against the entry that is actually returned to the client and may not reflect the complete entry stored in the server. If any filters are provided, then the entry must not match at least one of those filters (that is, the entry may match zero or more of those filters, but not of all of them).
        noneIncludedEntryFilter:
          type: array
          items:
            type: string
            description: >-
                Specifies a search filter that must not match search result entries included in this Simple Search Entry Criteria. Note that this matching will be performed against the entry that is actually returned to the client and may not reflect the complete entry stored in the server. If any filters are provided, then the entry must not match any of those filters.
        allIncludedEntryGroupDN:
          type: array
          items:
            type: string
            description: >-
                Specifies the DN of a group in which the user associated with the entry must be a member to be included in this Simple Search Entry Criteria. If any group DNs are provided, then the entry must be a member of all of them.
        anyIncludedEntryGroupDN:
          type: array
          items:
            type: string
            description: >-
                Specifies the DN of a group in which the user associated with the entry may be a member to be included in this Simple Search Entry Criteria. If any group DNs are provided, then the entry must be a member of at least one of them.
        notAllIncludedEntryGroupDN:
          type: array
          items:
            type: string
            description: >-
                Specifies the DN of a group in which the user associated with the entry should not be a member to be included in this Simple Search Entry Criteria. If any group DNs are provided, then the entry must not be a member of at least one of them (that is, the entry may be a member of zero or more of the specified groups, but not of all of them).
        noneIncludedEntryGroupDN:
          type: array
          items:
            type: string
            description: >-
                Specifies the DN of a group in which the user associated with the entry must not be a member to be included in this Simple Search Entry Criteria. If any group DNs are provided, then the entry must not be a member of any of them.
        description:
          type: string
          description: >-
              A description for this Search Entry Criteria
      required:
      - schemas
    Enumsimple-search-entry-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-entry-criteria:simple"
    add-aggregate-search-entry-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Search Entry Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/aggregate-search-entry-criteria-shared'
    aggregate-search-entry-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Search Entry Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/aggregate-search-entry-criteria-shared'
    aggregate-search-entry-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumaggregate-search-entry-criteriaSchemaUrn'
        allIncludedSearchEntryCriteria:
          type: array
          items:
            type: string
            description: >-
                Specifies a search entry criteria object that must match the associated search result entry in order to match the aggregate search entry criteria. If one or more all-included search entry criteria objects are provided, then a search result entry must match all of them in order to match the aggregate search entry criteria.
        anyIncludedSearchEntryCriteria:
          type: array
          items:
            type: string
            description: >-
                Specifies a search entry criteria object that may match the associated search result entry in order to match the aggregate search entry criteria. If one or more any-included search entry criteria objects are provided, then a search result entry must match at least one of them in order to match the aggregate search entry criteria.
        notAllIncludedSearchEntryCriteria:
          type: array
          items:
            type: string
            description: >-
                Specifies a search entry criteria object that should not match the associated search result entry in order to match the aggregate search entry criteria. If one or more not-all-included search entry criteria objects are provided, then a search result entry must not match all of them (that is, it may match zero or more of them, but it must not match all of them) in order to match the aggregate search entry criteria.
        noneIncludedSearchEntryCriteria:
          type: array
          items:
            type: string
            description: >-
                Specifies a search entry criteria object that must not match the associated search result entry in order to match the aggregate search entry criteria. If one or more none-included search entry criteria objects are provided, then a search result entry must not match any of them in order to match the aggregate search entry criteria.
        description:
          type: string
          description: >-
              A description for this Search Entry Criteria
      required:
      - schemas
    Enumaggregate-search-entry-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-entry-criteria:aggregate"
    add-third-party-search-entry-criteria-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Search Entry Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/third-party-search-entry-criteria-shared'
    third-party-search-entry-criteria-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Search Entry Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-search-entry-criteria-shared'
    third-party-search-entry-criteria-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-party-search-entry-criteriaSchemaUrn'
        extensionClass:
          type: string
          description: >-
              The fully-qualified name of the Java class providing the logic for the Third Party Search Entry Criteria.
        extensionArgument:
          type: array
          items:
            type: string
            description: >-
                The set of arguments used to customize the behavior for the Third Party Search Entry Criteria. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: >-
              A description for this Search Entry Criteria
      required:
      - schemas
      - extensionClass
    Enumthird-party-search-entry-criteriaSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:search-entry-criteria:third-party"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
