openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Synchronization Provider config object
  title: PingData Synchronization Provider Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access synchronization-providers
  name: synchronization-provider
paths:
  /synchronization-providers/{synchronization-provider-name}:
    get:
      summary: Returns a single Synchronization Provider
      operationId: get-synchronization-provider
      parameters:
      - description: Name of the Synchronization Provider to be read
        explode: false
        in: path
        name: synchronization-provider-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/replication-synchronization-provider-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Synchronization Provider does not exist
      security:
      - basicAuth: []
      tags:
      - synchronization-provider
    patch:
      summary: Update an existing Synchronization Provider by name
      operationId: update-synchronization-provider
      parameters:
      - description: Name of the Synchronization Provider to be updated
        explode: false
        in: path
        name: synchronization-provider-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Synchronization Provider
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/replication-synchronization-provider-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Synchronization Provider does not exist
      security:
      - basicAuth: []
      tags:
      - synchronization-provider
components:
  schemas:
    replication-synchronization-provider-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          schemas:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/components/schemas/Enumreplication-synchronization-providerSchemaUrn'
          numUpdateReplayThreads:
            type: integer
            description: >-
                Specifies the number of update replay threads.
          description:
            type: string
            description: >-
                A description for this Synchronization Provider
          enabled:
            type: boolean
            description: >-
                Indicates whether the Synchronization Provider is enabled for use.
        required:
        - enabled
    Enumreplication-synchronization-providerSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:synchronization-provider:replication"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
