openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Token Claim Validation config object
  title: PingData Token Claim Validation Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access token-claim-validations
  name: token-claim-validation
paths:
  /token-claim-validations:
    post:
      summary: Add a new Token Claim Validation to the config
      operationId: add-token-claim-validation
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-string-array-token-claim-validation-request'
              - $ref: '#/components/schemas/add-boolean-token-claim-validation-request'
              - $ref: '#/components/schemas/add-string-token-claim-validation-request'
        description: Create a new Token Claim Validation in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/string-array-token-claim-validation-response'
                - $ref: '#/components/schemas/boolean-token-claim-validation-response'
                - $ref: '#/components/schemas/string-token-claim-validation-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Token Claim Validation already exists
      security:
      - basicAuth: []
      tags:
      - token-claim-validation
  /token-claim-validations/{token-claim-validation-name}:
    delete:
      summary: Delete a Token Claim Validation
      operationId: delete-token-claim-validation
      parameters:
      - description: Name of the Token Claim Validation to be deleted
        explode: false
        in: path
        name: token-claim-validation-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Token Claim Validation does not exist
        "409":
          description: The Token Claim Validation cannot be deleted
      security:
      - basicAuth: []
      tags:
      - token-claim-validation
    get:
      summary: Returns a single Token Claim Validation
      operationId: get-token-claim-validation
      parameters:
      - description: Name of the Token Claim Validation to be read
        explode: false
        in: path
        name: token-claim-validation-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/string-array-token-claim-validation-response'
                - $ref: '#/components/schemas/boolean-token-claim-validation-response'
                - $ref: '#/components/schemas/string-token-claim-validation-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Token Claim Validation does not exist
      security:
      - basicAuth: []
      tags:
      - token-claim-validation
    patch:
      summary: Update an existing Token Claim Validation by name
      operationId: update-token-claim-validation
      parameters:
      - description: Name of the Token Claim Validation to be updated
        explode: false
        in: path
        name: token-claim-validation-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Token Claim Validation
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/string-array-token-claim-validation-response'
                - $ref: '#/components/schemas/boolean-token-claim-validation-response'
                - $ref: '#/components/schemas/string-token-claim-validation-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Token Claim Validation does not exist
      security:
      - basicAuth: []
      tags:
      - token-claim-validation
components:
  schemas:
    add-string-array-token-claim-validation-request:
      allOf:
      - type: object
        properties:
          validationName:
            description: Name of the new Token Claim Validation
            type: string
        required:
        - validationName
      - $ref: '#/components/schemas/string-array-token-claim-validation-shared'
    string-array-token-claim-validation-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Token Claim Validation
            type: string
        required:
        - id
      - $ref: '#/components/schemas/string-array-token-claim-validation-shared'
    string-array-token-claim-validation-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumstring-array-token-claim-validationSchemaUrn'
        allRequiredValue:
          type: array
          items:
            type: string
          description: >-
              The set of all values that the claim must have to be considered valid.
        anyRequiredValue:
          type: array
          items:
            type: string
          description: >-
              The set of values that the claim may have to be considered valid.
        description:
          type: string
          description: >-
              A description for this Token Claim Validation
        claimName:
          type: string
          description: >-
              The name of the claim to be validated.
      required:
      - schemas
      - claimName
    Enumstring-array-token-claim-validationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:token-claim-validation:string-array"
    add-boolean-token-claim-validation-request:
      allOf:
      - type: object
        properties:
          validationName:
            description: Name of the new Token Claim Validation
            type: string
        required:
        - validationName
      - $ref: '#/components/schemas/boolean-token-claim-validation-shared'
    boolean-token-claim-validation-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Token Claim Validation
            type: string
        required:
        - id
      - $ref: '#/components/schemas/boolean-token-claim-validation-shared'
    boolean-token-claim-validation-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumboolean-token-claim-validationSchemaUrn'
        requiredValue:
          $ref: '#/components/schemas/Enumtoken-claim-validation-requiredValueProp'
        description:
          type: string
          description: >-
              A description for this Token Claim Validation
        claimName:
          type: string
          description: >-
              The name of the claim to be validated.
      required:
      - schemas
      - requiredValue
      - claimName
    Enumboolean-token-claim-validationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:token-claim-validation:boolean"
    add-string-token-claim-validation-request:
      allOf:
      - type: object
        properties:
          validationName:
            description: Name of the new Token Claim Validation
            type: string
        required:
        - validationName
      - $ref: '#/components/schemas/string-token-claim-validation-shared'
    string-token-claim-validation-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Token Claim Validation
            type: string
        required:
        - id
      - $ref: '#/components/schemas/string-token-claim-validation-shared'
    string-token-claim-validation-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumstring-token-claim-validationSchemaUrn'
        anyRequiredValue:
          type: array
          items:
            type: string
          description: >-
              The set of values that the claim may have to be considered valid.
        description:
          type: string
          description: >-
              A description for this Token Claim Validation
        claimName:
          type: string
          description: >-
              The name of the claim to be validated.
      required:
      - schemas
      - anyRequiredValue
      - claimName
    Enumstring-token-claim-validationSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:token-claim-validation:string"
    Enumtoken-claim-validation-requiredValueProp:
      type: string
      enum:
      - "true"
      - "false"
      description: >-
          Specifies the boolean claim's required value.
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
