openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Trusted Certificate config object
  title: PingData Trusted Certificate Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access trusted-certificates
  name: trusted-certificate
paths:
  /trusted-certificates:
    post:
      summary: Add a new Trusted Certificate to the config
      operationId: add-trusted-certificate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-trusted-certificate-request'
        description: Create a new Trusted Certificate in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trusted-certificate-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Trusted Certificate already exists
      security:
      - basicAuth: []
      tags:
      - trusted-certificate
  /trusted-certificates/{trusted-certificate-name}:
    delete:
      summary: Delete a Trusted Certificate
      operationId: delete-trusted-certificate
      parameters:
      - description: Name of the Trusted Certificate
        explode: false
        in: path
        name: trusted-certificate-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Trusted Certificate does not exist
        "409":
          description: The Trusted Certificate cannot be deleted
      security:
      - basicAuth: []
      tags:
      - trusted-certificate
    get:
      summary: Returns a single Trusted Certificate
      operationId: get-trusted-certificate
      parameters:
      - description: Name of the Trusted Certificate
        explode: false
        in: path
        name: trusted-certificate-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trusted-certificate-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Trusted Certificate does not exist
      security:
      - basicAuth: []
      tags:
      - trusted-certificate
    patch:
      summary: Update an existing Trusted Certificate by name
      operationId: update-trusted-certificate
      parameters:
      - description: Name of the Trusted Certificate
        explode: false
        in: path
        name: trusted-certificate-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Trusted Certificate
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trusted-certificate-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Trusted Certificate does not exist
      security:
      - basicAuth: []
      tags:
      - trusted-certificate
components:
  schemas:
    add-trusted-certificate-request:
      allOf:
      - type: object
        properties:
          certificateName:
            type: string
            description: >-
                Name of the new Trusted Certificate
      - $ref: '#/components/schemas/trusted-certificate-shared'
      required:
      - certificateName
    trusted-certificate-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Trusted Certificate
      - $ref: '#/components/schemas/trusted-certificate-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    trusted-certificate-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumtrusted-certificateSchemaUrn'
        certificate:
          type: string
          description: >-
              The PEM-encoded X.509v3 certificate.
      required:
      - certificate
    Enumtrusted-certificateSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:trusted-certificate"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
