openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Uncached Attribute Criteria config object
  title: PingData Uncached Attribute Criteria Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access uncached-attribute-criteria
  name: uncached-attribute-criteria
paths:
  /uncached-attribute-criteria:
    post:
      summary: Add a new Uncached Attribute Criteria to the config
      operationId: add-uncached-attribute-criteria
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-default-request'
              - $ref: '#/components/schemas/add-groovy-scripted-request'
              - $ref: '#/components/schemas/add-simple-request'
              - $ref: '#/components/schemas/add-third-party-request'
        description: Create a new Uncached Attribute Criteria in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/simple-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Uncached Attribute Criteria already exists
      security:
      - basicAuth: []
      tags:
      - location
  /uncached-attribute-criteria/{uncached-attribute-criteria-name}:
    delete:
      summary: Delete a Uncached Attribute Criteria
      operationId: delete-uncached-attribute-criteria
      parameters:
      - description: Name of the Uncached Attribute Criteria to be deleted
        explode: false
        in: path
        name: uncached-attribute-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Uncached Attribute Criteria does not exist
        "409":
          description: The Uncached Attribute Criteria cannot be deleted
      security:
      - basicAuth: []
      tags:
      - location
    get:
      summary: Returns a single Uncached Attribute Criteria
      operationId: get-uncached-attribute-criteria
      parameters:
      - description: Name of the Uncached Attribute Criteria to be read
        explode: false
        in: path
        name: uncached-attribute-criteria-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/simple-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Uncached Attribute Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - location
    patch:
      summary: Update an existing Uncached Attribute Criteria by name
      operationId: update-uncached-attribute-criteria
      parameters:
      - description: Name of the Uncached Attribute Criteria to be updated
        explode: false
        in: path
        name: uncached-attribute-criteria-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-uncached-attribute-criteria-request'
        description: Update an existing Uncached Attribute Criteria
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/default-response'
                - $ref: '#/components/schemas/groovy-scripted-response'
                - $ref: '#/components/schemas/simple-response'
                - $ref: '#/components/schemas/third-party-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Uncached Attribute Criteria does not exist
      security:
      - basicAuth: []
      tags:
      - location
components:
  schemas:
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    add-default-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Uncached Attribute Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/default-shared'
    default-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Uncached Attribute Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/default-shared'
    default-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumdefaultSchemaUrn'
        description:
          type: string
          description: A description for this Uncached Attribute Criteria
        enabled:
          type: boolean
          description: Indicates whether this Uncached Attribute Criteria is enabled for use in the server.
      required:
      - schemas
      - enabled
    EnumdefaultSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:uncached-attribute-criteria:default"
    add-groovy-scripted-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Uncached Attribute Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/groovy-scripted-shared'
    groovy-scripted-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Uncached Attribute Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/groovy-scripted-shared'
    groovy-scripted-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumgroovy-scriptedSchemaUrn'
        scriptClass:
          type: string
          description: The fully-qualified name of the Groovy class providing the logic for the Groovy Scripted Uncached Attribute Criteria.
        scriptArgument:
          type: array
          items:
            type: string
            description: The set of arguments used to customize the behavior for the Scripted Uncached Attribute Criteria. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: A description for this Uncached Attribute Criteria
        enabled:
          type: boolean
          description: Indicates whether this Uncached Attribute Criteria is enabled for use in the server.
      required:
      - schemas
      - scriptClass
      - enabled
    Enumgroovy-scriptedSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:uncached-attribute-criteria:groovy-scripted"
    add-simple-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Uncached Attribute Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/simple-shared'
    simple-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Uncached Attribute Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/simple-shared'
    simple-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/EnumsimpleSchemaUrn'
        attributeType:
          type: array
          items:
            type: string
            description: Specifies the attribute types for attributes that may be written to the uncached-id2entry database.
        minValueCount:
          type: integer
          description: Specifies the minimum number of values that an attribute must have before it will be written into the uncached-id2entry database.
        minTotalValueSize:
          type: string
          description: Specifies the minimum total value size (i.e., the sum of the sizes of all values) that an attribute must have before it will be written into the uncached-id2entry database.
        description:
          type: string
          description: A description for this Uncached Attribute Criteria
        enabled:
          type: boolean
          description: Indicates whether this Uncached Attribute Criteria is enabled for use in the server.
      required:
      - schemas
      - attributeType
      - enabled
    EnumsimpleSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:uncached-attribute-criteria:simple"
    add-third-party-request:
      allOf:
      - type: object
        properties:
          criteriaName:
            description: Name of the new Uncached Attribute Criteria
            type: string
        required:
        - criteriaName
      - $ref: '#/components/schemas/third-party-shared'
    third-party-response:
      allOf:
      - type: object
        properties:
          id:
            description: Name of the Uncached Attribute Criteria
            type: string
        required:
        - id
      - $ref: '#/components/schemas/third-party-shared'
    third-party-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumthird-partySchemaUrn'
        extensionClass:
          type: string
          description: The fully-qualified name of the Java class providing the logic for the Third Party Uncached Attribute Criteria.
        extensionArgument:
          type: array
          items:
            type: string
            description: The set of arguments used to customize the behavior for the Third Party Uncached Attribute Criteria. Each configuration property should be given in the form 'name=value'.
        description:
          type: string
          description: A description for this Uncached Attribute Criteria
        enabled:
          type: boolean
          description: Indicates whether this Uncached Attribute Criteria is enabled for use in the server.
      required:
      - schemas
      - extensionClass
      - enabled
    Enumthird-partySchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:uncached-attribute-criteria:third-party"
    update-uncached-attribute-criteria-request:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
