openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Vault Authentication Method config object
  title: PingData Vault Authentication Method Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-93/pd_ds_use_config_api
tags:
- description: Access vault-authentication-methods
  name: vault-authentication-method
paths:
  /vault-authentication-methods:
    post:
      summary: Add a new Vault Authentication Method to the config
      operationId: add-vault-authentication-method
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/add-static-token-vault-authentication-method-request'
              - $ref: '#/components/schemas/add-app-role-vault-authentication-method-request'
              - $ref: '#/components/schemas/add-user-pass-vault-authentication-method-request'
        description: Create a new Vault Authentication Method in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/static-token-vault-authentication-method-response'
                - $ref: '#/components/schemas/app-role-vault-authentication-method-response'
                - $ref: '#/components/schemas/user-pass-vault-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Vault Authentication Method already exists
      security:
      - basicAuth: []
      tags:
      - vault-authentication-method
  /vault-authentication-methods/{vault-authentication-method-name}:
    delete:
      summary: Delete a Vault Authentication Method
      operationId: delete-vault-authentication-method
      parameters:
      - description: Name of the Vault Authentication Method
        explode: false
        in: path
        name: vault-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Vault Authentication Method does not exist
        "409":
          description: The Vault Authentication Method cannot be deleted
      security:
      - basicAuth: []
      tags:
      - vault-authentication-method
    get:
      summary: Returns a single Vault Authentication Method
      operationId: get-vault-authentication-method
      parameters:
      - description: Name of the Vault Authentication Method
        explode: false
        in: path
        name: vault-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/static-token-vault-authentication-method-response'
                - $ref: '#/components/schemas/app-role-vault-authentication-method-response'
                - $ref: '#/components/schemas/user-pass-vault-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Vault Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - vault-authentication-method
    patch:
      summary: Update an existing Vault Authentication Method by name
      operationId: update-vault-authentication-method
      parameters:
      - description: Name of the Vault Authentication Method
        explode: false
        in: path
        name: vault-authentication-method-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Vault Authentication Method
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/static-token-vault-authentication-method-response'
                - $ref: '#/components/schemas/app-role-vault-authentication-method-response'
                - $ref: '#/components/schemas/user-pass-vault-authentication-method-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Vault Authentication Method does not exist
      security:
      - basicAuth: []
      tags:
      - vault-authentication-method
components:
  schemas:
    add-static-token-vault-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Vault Authentication Method
      - $ref: '#/components/schemas/static-token-vault-authentication-method-shared'
      required:
      - methodName
    static-token-vault-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Vault Authentication Method
      - $ref: '#/components/schemas/static-token-vault-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    static-token-vault-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumstatic-token-vault-authentication-methodSchemaUrn'
        vaultAccessToken:
          type: string
          format: password
          description: >-
              The static token used to authenticate to the Vault server.
        description:
          type: string
          description: >-
              A description for this Vault Authentication Method
      required:
      - schemas
      - vaultAccessToken
    Enumstatic-token-vault-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:vault-authentication-method:static-token"
    add-app-role-vault-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Vault Authentication Method
      - $ref: '#/components/schemas/app-role-vault-authentication-method-shared'
      required:
      - methodName
    app-role-vault-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Vault Authentication Method
      - $ref: '#/components/schemas/app-role-vault-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    app-role-vault-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumapp-role-vault-authentication-methodSchemaUrn'
        vaultRoleID:
          type: string
          description: >-
              The role ID for the AppRole to authenticate.
        vaultSecretID:
          type: string
          format: password
          description: >-
              The secret ID for the AppRole to authenticate.
        loginMechanismName:
          type: string
          description: >-
              The name used when enabling the desired AppRole authentication mechanism in the Vault server.
        description:
          type: string
          description: >-
              A description for this Vault Authentication Method
      required:
      - schemas
      - vaultRoleID
      - vaultSecretID
    Enumapp-role-vault-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:vault-authentication-method:app-role"
    add-user-pass-vault-authentication-method-request:
      allOf:
      - type: object
        properties:
          methodName:
            type: string
            description: >-
                Name of the new Vault Authentication Method
      - $ref: '#/components/schemas/user-pass-vault-authentication-method-shared'
      required:
      - methodName
    user-pass-vault-authentication-method-response:
      allOf:
      - type: object
        properties:
          id:
            type: string
            description: >-
                Name of the Vault Authentication Method
      - $ref: '#/components/schemas/user-pass-vault-authentication-method-shared'
      - $ref: '#/components/schemas/meta'
      required:
      - id
    user-pass-vault-authentication-method-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumuser-pass-vault-authentication-methodSchemaUrn'
        username:
          type: string
          description: >-
              The username for the user to authenticate.
        password:
          type: string
          format: password
          description: >-
              The password for the user to authenticate.
        loginMechanismName:
          type: string
          description: >-
              The name used when enabling the desired UserPass authentication mechanism in the Vault server.
        description:
          type: string
          description: >-
              A description for this Vault Authentication Method
      required:
      - schemas
      - username
      - password
    Enumuser-pass-vault-authentication-methodSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:vault-authentication-method:user-pass"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
