openapi: 3.0.3
info:
  description: This is the PingData Configuration API for the Velocity Template Loader config object
  title: PingData Velocity Template Loader Config - OpenAPI 3.0
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
tags:
- description: Access velocity-template-loaders
  name: velocity-template-loader
paths:
  /velocity-template-loaders:
    post:
      summary: Add a new Velocity Template Loader to the config
      operationId: add-velocity-template-loader
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add-velocity-template-loader-request'
        description: Create a new Velocity Template Loader in the config
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/velocity-template-loader-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Bad request
        "409":
          description: The Velocity Template Loader already exists
      security:
      - basicAuth: []
      tags:
      - velocity-template-loader
  /velocity-template-loaders/{velocity-template-loader-name}:
    delete:
      summary: Delete a Velocity Template Loader
      operationId: delete-velocity-template-loader
      parameters:
      - description: Name of the Velocity Template Loader to be deleted
        explode: false
        in: path
        name: velocity-template-loader-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Velocity Template Loader does not exist
        "409":
          description: The Velocity Template Loader cannot be deleted
      security:
      - basicAuth: []
      tags:
      - velocity-template-loader
    get:
      summary: Returns a single Velocity Template Loader
      operationId: get-velocity-template-loader
      parameters:
      - description: Name of the Velocity Template Loader to be read
        explode: false
        in: path
        name: velocity-template-loader-name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/velocity-template-loader-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "404":
          description: The Velocity Template Loader does not exist
      security:
      - basicAuth: []
      tags:
      - velocity-template-loader
    patch:
      summary: Update an existing Velocity Template Loader by name
      operationId: update-velocity-template-loader
      parameters:
      - description: Name of the Velocity Template Loader to be updated
        explode: false
        in: path
        name: velocity-template-loader-name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        description: Update an existing Velocity Template Loader
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/velocity-template-loader-response'
        "401":
          description: Requestor cannot be authenticated
        "403":
          description: Requestor does not have the required privileges
        "400":
          description: Invalid request
        "404":
          description: The Velocity Template Loader does not exist
      security:
      - basicAuth: []
      tags:
      - velocity-template-loader
components:
  schemas:
    add-velocity-template-loader-request:
      allOf:
      - type: object
        properties:
          loaderName:
            description: Name of the new Velocity Template Loader
            type: string
        required:
        - loaderName
      - $ref: '#/components/schemas/velocity-template-loader-shared'
    velocity-template-loader-response:
      allOf:
      - $ref: '#/components/schemas/meta'
      - type: object
        properties:
          id:
            description: Name of the Velocity Template Loader
            type: string
        required:
        - id
      - $ref: '#/components/schemas/velocity-template-loader-shared'
    velocity-template-loader-shared:
      type: object
      properties:
        schemas:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Enumvelocity-template-loaderSchemaUrn'
        enabled:
          type: boolean
          description: >-
              Indicates whether this Velocity Template Loader is enabled.
        evaluationOrderIndex:
          type: integer
          description: >-
              This property determines the evaluation order for determining the correct Velocity Template Loader to load a template for generating content for a particular request.
        mimeTypeMatcher:
          type: string
          description: >-
              Specifies a media type for matching Accept request-header values.
        mimeType:
          type: string
          description: >-
              Specifies a the value that will be used in the response's Content-Type header that indicates the type of content to return.
        templateSuffix:
          type: string
          description: >-
              Specifies the suffix to append to the requested resource name when searching for the template file with which to form a response.
        templateDirectory:
          type: string
          description: >-
              Specifies the directory in which to search for the template files.
      required:
      - evaluationOrderIndex
      - mimeTypeMatcher
    Enumvelocity-template-loaderSchemaUrn:
      type: string
      enum:
      - "urn:pingidentity:schemas:configuration:2.0:velocity-template-loader"
    updateRequest:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
      required:
      - operations
    Operation:
      type: object
      properties:
        op:
          $ref: '#/components/schemas/EnumOperation'
        path:
          type: string
        value:
          type: string
      required:
      - op
      - path
    EnumOperation:
      type: string
      enum:
      - "add"
      - "remove"
      - "replace"
    meta:
      type: object
      properties:
        meta:
          type: object
          properties:
            resourceType:
              type: string
            location:
              type: string
        "urn:pingidentity:schemas:configuration:messages:2.0":
          type: object
          properties:
            notifications:
              type: array
              items:
                type: string
            requiredActions:
              type: array
              items:
                type: object
                properties:
                  property:
                    type: string
                  type:
                    type: string
                  synopsis:
                    type: string
                required:
                - type
                - synopsis
  securitySchemes:
    basicAuth:
      scheme: Basic
      type: http
