/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

// InterServerAuthenticationInfoApiService InterServerAuthenticationInfoApi service
type InterServerAuthenticationInfoApiService service

type ApiGetInterServerAuthenticationInfoRequest struct {
	ctx                               context.Context
	ApiService                        *InterServerAuthenticationInfoApiService
	interServerAuthenticationInfoName string
	serverInstanceListenerName        string
	serverInstanceName                string
}

func (r ApiGetInterServerAuthenticationInfoRequest) Execute() (*GetInterServerAuthenticationInfo200Response, *http.Response, error) {
	return r.ApiService.GetInterServerAuthenticationInfoExecute(r)
}

/*
GetInterServerAuthenticationInfo Returns a single Inter Server Authentication Info

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param interServerAuthenticationInfoName Name of the Inter Server Authentication Info
	@param serverInstanceListenerName Name of the Server Instance Listener
	@param serverInstanceName Name of the Server Instance
	@return ApiGetInterServerAuthenticationInfoRequest
*/
func (a *InterServerAuthenticationInfoApiService) GetInterServerAuthenticationInfo(ctx context.Context, interServerAuthenticationInfoName string, serverInstanceListenerName string, serverInstanceName string) ApiGetInterServerAuthenticationInfoRequest {
	return ApiGetInterServerAuthenticationInfoRequest{
		ApiService:                        a,
		ctx:                               ctx,
		interServerAuthenticationInfoName: interServerAuthenticationInfoName,
		serverInstanceListenerName:        serverInstanceListenerName,
		serverInstanceName:                serverInstanceName,
	}
}

// Execute executes the request
//
//	@return GetInterServerAuthenticationInfo200Response
func (a *InterServerAuthenticationInfoApiService) GetInterServerAuthenticationInfoExecute(r ApiGetInterServerAuthenticationInfoRequest) (*GetInterServerAuthenticationInfo200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetInterServerAuthenticationInfo200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InterServerAuthenticationInfoApiService.GetInterServerAuthenticationInfo")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/server-instances/{server-instance-name}/server-instance-listeners/{server-instance-listener-name}/inter-server-authentication-info/{inter-server-authentication-info-name}"
	localVarPath = strings.Replace(localVarPath, "{"+"inter-server-authentication-info-name"+"}", url.PathEscape(parameterToString(r.interServerAuthenticationInfoName, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"server-instance-listener-name"+"}", url.PathEscape(parameterToString(r.serverInstanceListenerName, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"server-instance-name"+"}", url.PathEscape(parameterToString(r.serverInstanceName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateInterServerAuthenticationInfoRequest struct {
	ctx                               context.Context
	ApiService                        *InterServerAuthenticationInfoApiService
	interServerAuthenticationInfoName string
	serverInstanceListenerName        string
	serverInstanceName                string
	updateRequest                     *UpdateRequest
}

// Update an existing Inter Server Authentication Info
func (r ApiUpdateInterServerAuthenticationInfoRequest) UpdateRequest(updateRequest UpdateRequest) ApiUpdateInterServerAuthenticationInfoRequest {
	r.updateRequest = &updateRequest
	return r
}

func (r ApiUpdateInterServerAuthenticationInfoRequest) Execute() (*GetInterServerAuthenticationInfo200Response, *http.Response, error) {
	return r.ApiService.UpdateInterServerAuthenticationInfoExecute(r)
}

/*
UpdateInterServerAuthenticationInfo Update an existing Inter Server Authentication Info by name

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param interServerAuthenticationInfoName Name of the Inter Server Authentication Info
	@param serverInstanceListenerName Name of the Server Instance Listener
	@param serverInstanceName Name of the Server Instance
	@return ApiUpdateInterServerAuthenticationInfoRequest
*/
func (a *InterServerAuthenticationInfoApiService) UpdateInterServerAuthenticationInfo(ctx context.Context, interServerAuthenticationInfoName string, serverInstanceListenerName string, serverInstanceName string) ApiUpdateInterServerAuthenticationInfoRequest {
	return ApiUpdateInterServerAuthenticationInfoRequest{
		ApiService:                        a,
		ctx:                               ctx,
		interServerAuthenticationInfoName: interServerAuthenticationInfoName,
		serverInstanceListenerName:        serverInstanceListenerName,
		serverInstanceName:                serverInstanceName,
	}
}

// Execute executes the request
//
//	@return GetInterServerAuthenticationInfo200Response
func (a *InterServerAuthenticationInfoApiService) UpdateInterServerAuthenticationInfoExecute(r ApiUpdateInterServerAuthenticationInfoRequest) (*GetInterServerAuthenticationInfo200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetInterServerAuthenticationInfo200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InterServerAuthenticationInfoApiService.UpdateInterServerAuthenticationInfo")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/server-instances/{server-instance-name}/server-instance-listeners/{server-instance-listener-name}/inter-server-authentication-info/{inter-server-authentication-info-name}"
	localVarPath = strings.Replace(localVarPath, "{"+"inter-server-authentication-info-name"+"}", url.PathEscape(parameterToString(r.interServerAuthenticationInfoName, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"server-instance-listener-name"+"}", url.PathEscape(parameterToString(r.serverInstanceListenerName, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"server-instance-name"+"}", url.PathEscape(parameterToString(r.serverInstanceName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateRequest == nil {
		return localVarReturnValue, nil, reportError("updateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
