openapi: 3.0.3
info:
  title: PingData Location Config - OpenAPI 3.0
  description: This is the PingData configuration API for the Location config object
  version: "0.1"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/bundle/pingdirectory-91/page/ddl1564011495095.html
servers:
  - url: https://localhost:1443/config
tags:
  - name: location
    description: Access Locations
paths:
  /locations:
    post:
      tags:
        - location
      summary: Add a new location to the config
      description: Add a new location to the config
      operationId: addLocation
      requestBody:
        description: Create a new location in the config
        content:
          application/json:
            schema:
              properties:
                locationName: 
                  description: Name of the new location
                  type: string
                description:
                  description: Description of the new location
                  type: string
              required:
                - name
        required: true
      responses:
        '200':
          description: Successful operation
      security:
        - basicAuth: []
  /locations/{locationName}:
    patch:
      tags:
        - location
      summary: Update an existing location
      description: Update an existing location by name
      operationId: updateLocation
      parameters:
        - name: locationName
          in: path
          description: Name of the location that needs to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existing location
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operations'  
        required: true
      responses:
        '200':
          description: Successful operation
      security:
        - basicAuth: []
    get:
      tags:
        - location
      summary: Find location by name
      description: Returns a single location
      operationId: getLocation
      parameters:
        - name: locationName
          in: path
          description: Name of the location to be read
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  id:
                    description: Name of the location
                    type: string
                  description:
                    description: Description of the location
                    type: string
      security:
        - basicAuth: []
    delete:
      tags:
        - location
      summary: Deletes a location
      description: delete a location
      operationId: deleteLocation
      parameters:
        - name: locationName
          in: path
          description: Name of the location to be read
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
      security:
        - basicAuth: []
components:
  schemas:
    Operations:
      type: array
      items:
        $ref: '#/components/schemas/Operation'
    Operation:
      type: object
      properties:
        # This should probably be an enum
        op:
          type: string
        path:
          type: string
        # This could be anything depending on the config object and attribute it is modifying
        value:
          type: string
    Location:
      type: object
      properties:
        id: 
          description: Name of the new location
          type: string
        description:
          description: Description of the new location
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: Basic
