/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DnMapResponseAllOf struct for DnMapResponseAllOf
type DnMapResponseAllOf struct {
	// Name of the DN Map
	Id string `json:"id"`
}

// NewDnMapResponseAllOf instantiates a new DnMapResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnMapResponseAllOf(id string) *DnMapResponseAllOf {
	this := DnMapResponseAllOf{}
	this.Id = id
	return &this
}

// NewDnMapResponseAllOfWithDefaults instantiates a new DnMapResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnMapResponseAllOfWithDefaults() *DnMapResponseAllOf {
	this := DnMapResponseAllOf{}
	return &this
}

// GetId returns the Id field value
func (o *DnMapResponseAllOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DnMapResponseAllOf) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DnMapResponseAllOf) SetId(v string) {
	o.Id = v
}

func (o DnMapResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableDnMapResponseAllOf struct {
	value *DnMapResponseAllOf
	isSet bool
}

func (v NullableDnMapResponseAllOf) Get() *DnMapResponseAllOf {
	return v.value
}

func (v *NullableDnMapResponseAllOf) Set(val *DnMapResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDnMapResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDnMapResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnMapResponseAllOf(val *DnMapResponseAllOf) *NullableDnMapResponseAllOf {
	return &NullableDnMapResponseAllOf{value: val, isSet: true}
}

func (v NullableDnMapResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnMapResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


