/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RecurringTaskChainResponseAllOf struct for RecurringTaskChainResponseAllOf
type RecurringTaskChainResponseAllOf struct {
	// Name of the Recurring Task Chain
	Id string `json:"id"`
}

// NewRecurringTaskChainResponseAllOf instantiates a new RecurringTaskChainResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurringTaskChainResponseAllOf(id string) *RecurringTaskChainResponseAllOf {
	this := RecurringTaskChainResponseAllOf{}
	this.Id = id
	return &this
}

// NewRecurringTaskChainResponseAllOfWithDefaults instantiates a new RecurringTaskChainResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurringTaskChainResponseAllOfWithDefaults() *RecurringTaskChainResponseAllOf {
	this := RecurringTaskChainResponseAllOf{}
	return &this
}

// GetId returns the Id field value
func (o *RecurringTaskChainResponseAllOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RecurringTaskChainResponseAllOf) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RecurringTaskChainResponseAllOf) SetId(v string) {
	o.Id = v
}

func (o RecurringTaskChainResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableRecurringTaskChainResponseAllOf struct {
	value *RecurringTaskChainResponseAllOf
	isSet bool
}

func (v NullableRecurringTaskChainResponseAllOf) Get() *RecurringTaskChainResponseAllOf {
	return v.value
}

func (v *NullableRecurringTaskChainResponseAllOf) Set(val *RecurringTaskChainResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringTaskChainResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringTaskChainResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringTaskChainResponseAllOf(val *RecurringTaskChainResponseAllOf) *NullableRecurringTaskChainResponseAllOf {
	return &NullableRecurringTaskChainResponseAllOf{value: val, isSet: true}
}

func (v NullableRecurringTaskChainResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringTaskChainResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


