/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TimeLimitLogRetentionPolicyResponse struct for TimeLimitLogRetentionPolicyResponse
type TimeLimitLogRetentionPolicyResponse struct {
	Meta                                          *MetaMeta                                          `json:"meta,omitempty"`
	Urnpingidentityschemasconfigurationmessages20 *MetaUrnPingidentitySchemasConfigurationMessages20 `json:"urn:pingidentity:schemas:configuration:messages:2.0,omitempty"`
	// Name of the Log Retention Policy
	Id      string                                     `json:"id"`
	Schemas []EnumtimeLimitLogRetentionPolicySchemaUrn `json:"schemas"`
	// Specifies the desired minimum length of time that each log file should be retained.
	RetainDuration string `json:"retainDuration"`
	// A description for this Log Retention Policy
	Description *string `json:"description,omitempty"`
}

// NewTimeLimitLogRetentionPolicyResponse instantiates a new TimeLimitLogRetentionPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeLimitLogRetentionPolicyResponse(id string, schemas []EnumtimeLimitLogRetentionPolicySchemaUrn, retainDuration string) *TimeLimitLogRetentionPolicyResponse {
	this := TimeLimitLogRetentionPolicyResponse{}
	this.Id = id
	this.Schemas = schemas
	this.RetainDuration = retainDuration
	return &this
}

// NewTimeLimitLogRetentionPolicyResponseWithDefaults instantiates a new TimeLimitLogRetentionPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeLimitLogRetentionPolicyResponseWithDefaults() *TimeLimitLogRetentionPolicyResponse {
	this := TimeLimitLogRetentionPolicyResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *TimeLimitLogRetentionPolicyResponse) GetMeta() MetaMeta {
	if o == nil || isNil(o.Meta) {
		var ret MetaMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetMetaOk() (*MetaMeta, bool) {
	if o == nil || isNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *TimeLimitLogRetentionPolicyResponse) HasMeta() bool {
	if o != nil && !isNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaMeta and assigns it to the Meta field.
func (o *TimeLimitLogRetentionPolicyResponse) SetMeta(v MetaMeta) {
	o.Meta = &v
}

// GetUrnpingidentityschemasconfigurationmessages20 returns the Urnpingidentityschemasconfigurationmessages20 field value if set, zero value otherwise.
func (o *TimeLimitLogRetentionPolicyResponse) GetUrnpingidentityschemasconfigurationmessages20() MetaUrnPingidentitySchemasConfigurationMessages20 {
	if o == nil || isNil(o.Urnpingidentityschemasconfigurationmessages20) {
		var ret MetaUrnPingidentitySchemasConfigurationMessages20
		return ret
	}
	return *o.Urnpingidentityschemasconfigurationmessages20
}

// GetUrnpingidentityschemasconfigurationmessages20Ok returns a tuple with the Urnpingidentityschemasconfigurationmessages20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetUrnpingidentityschemasconfigurationmessages20Ok() (*MetaUrnPingidentitySchemasConfigurationMessages20, bool) {
	if o == nil || isNil(o.Urnpingidentityschemasconfigurationmessages20) {
		return nil, false
	}
	return o.Urnpingidentityschemasconfigurationmessages20, true
}

// HasUrnpingidentityschemasconfigurationmessages20 returns a boolean if a field has been set.
func (o *TimeLimitLogRetentionPolicyResponse) HasUrnpingidentityschemasconfigurationmessages20() bool {
	if o != nil && !isNil(o.Urnpingidentityschemasconfigurationmessages20) {
		return true
	}

	return false
}

// SetUrnpingidentityschemasconfigurationmessages20 gets a reference to the given MetaUrnPingidentitySchemasConfigurationMessages20 and assigns it to the Urnpingidentityschemasconfigurationmessages20 field.
func (o *TimeLimitLogRetentionPolicyResponse) SetUrnpingidentityschemasconfigurationmessages20(v MetaUrnPingidentitySchemasConfigurationMessages20) {
	o.Urnpingidentityschemasconfigurationmessages20 = &v
}

// GetId returns the Id field value
func (o *TimeLimitLogRetentionPolicyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TimeLimitLogRetentionPolicyResponse) SetId(v string) {
	o.Id = v
}

// GetSchemas returns the Schemas field value
func (o *TimeLimitLogRetentionPolicyResponse) GetSchemas() []EnumtimeLimitLogRetentionPolicySchemaUrn {
	if o == nil {
		var ret []EnumtimeLimitLogRetentionPolicySchemaUrn
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetSchemasOk() ([]EnumtimeLimitLogRetentionPolicySchemaUrn, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *TimeLimitLogRetentionPolicyResponse) SetSchemas(v []EnumtimeLimitLogRetentionPolicySchemaUrn) {
	o.Schemas = v
}

// GetRetainDuration returns the RetainDuration field value
func (o *TimeLimitLogRetentionPolicyResponse) GetRetainDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetainDuration
}

// GetRetainDurationOk returns a tuple with the RetainDuration field value
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetRetainDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetainDuration, true
}

// SetRetainDuration sets field value
func (o *TimeLimitLogRetentionPolicyResponse) SetRetainDuration(v string) {
	o.RetainDuration = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TimeLimitLogRetentionPolicyResponse) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeLimitLogRetentionPolicyResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TimeLimitLogRetentionPolicyResponse) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TimeLimitLogRetentionPolicyResponse) SetDescription(v string) {
	o.Description = &v
}

func (o TimeLimitLogRetentionPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !isNil(o.Urnpingidentityschemasconfigurationmessages20) {
		toSerialize["urn:pingidentity:schemas:configuration:messages:2.0"] = o.Urnpingidentityschemasconfigurationmessages20
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["schemas"] = o.Schemas
	}
	if true {
		toSerialize["retainDuration"] = o.RetainDuration
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableTimeLimitLogRetentionPolicyResponse struct {
	value *TimeLimitLogRetentionPolicyResponse
	isSet bool
}

func (v NullableTimeLimitLogRetentionPolicyResponse) Get() *TimeLimitLogRetentionPolicyResponse {
	return v.value
}

func (v *NullableTimeLimitLogRetentionPolicyResponse) Set(val *TimeLimitLogRetentionPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeLimitLogRetentionPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeLimitLogRetentionPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeLimitLogRetentionPolicyResponse(val *TimeLimitLogRetentionPolicyResponse) *NullableTimeLimitLogRetentionPolicyResponse {
	return &NullableTimeLimitLogRetentionPolicyResponse{value: val, isSet: true}
}

func (v NullableTimeLimitLogRetentionPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeLimitLogRetentionPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
