/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Enumpkcs11KeyManagerProviderSchemaUrn the model 'Enumpkcs11KeyManagerProviderSchemaUrn'
type Enumpkcs11KeyManagerProviderSchemaUrn string

// List of Enumpkcs11-key-manager-providerSchemaUrn
const (
	ENUMPKCS11KEYMANAGERPROVIDERSCHEMAURN_URNPINGIDENTITYSCHEMASCONFIGURATION2_0KEY_MANAGER_PROVIDERPKCS11 Enumpkcs11KeyManagerProviderSchemaUrn = "urn:pingidentity:schemas:configuration:2.0:key-manager-provider:pkcs11"
)

// All allowed values of Enumpkcs11KeyManagerProviderSchemaUrn enum
var AllowedEnumpkcs11KeyManagerProviderSchemaUrnEnumValues = []Enumpkcs11KeyManagerProviderSchemaUrn{
	"urn:pingidentity:schemas:configuration:2.0:key-manager-provider:pkcs11",
}

func (v *Enumpkcs11KeyManagerProviderSchemaUrn) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Enumpkcs11KeyManagerProviderSchemaUrn(value)
	for _, existing := range AllowedEnumpkcs11KeyManagerProviderSchemaUrnEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Enumpkcs11KeyManagerProviderSchemaUrn", value)
}

// NewEnumpkcs11KeyManagerProviderSchemaUrnFromValue returns a pointer to a valid Enumpkcs11KeyManagerProviderSchemaUrn
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumpkcs11KeyManagerProviderSchemaUrnFromValue(v string) (*Enumpkcs11KeyManagerProviderSchemaUrn, error) {
	ev := Enumpkcs11KeyManagerProviderSchemaUrn(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Enumpkcs11KeyManagerProviderSchemaUrn: valid values are %v", v, AllowedEnumpkcs11KeyManagerProviderSchemaUrnEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Enumpkcs11KeyManagerProviderSchemaUrn) IsValid() bool {
	for _, existing := range AllowedEnumpkcs11KeyManagerProviderSchemaUrnEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Enumpkcs11-key-manager-providerSchemaUrn value
func (v Enumpkcs11KeyManagerProviderSchemaUrn) Ptr() *Enumpkcs11KeyManagerProviderSchemaUrn {
	return &v
}

type NullableEnumpkcs11KeyManagerProviderSchemaUrn struct {
	value *Enumpkcs11KeyManagerProviderSchemaUrn
	isSet bool
}

func (v NullableEnumpkcs11KeyManagerProviderSchemaUrn) Get() *Enumpkcs11KeyManagerProviderSchemaUrn {
	return v.value
}

func (v *NullableEnumpkcs11KeyManagerProviderSchemaUrn) Set(val *Enumpkcs11KeyManagerProviderSchemaUrn) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumpkcs11KeyManagerProviderSchemaUrn) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumpkcs11KeyManagerProviderSchemaUrn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumpkcs11KeyManagerProviderSchemaUrn(val *Enumpkcs11KeyManagerProviderSchemaUrn) *NullableEnumpkcs11KeyManagerProviderSchemaUrn {
	return &NullableEnumpkcs11KeyManagerProviderSchemaUrn{value: val, isSet: true}
}

func (v NullableEnumpkcs11KeyManagerProviderSchemaUrn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumpkcs11KeyManagerProviderSchemaUrn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

