/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddSyslogJsonAuditLogPublisherRequest struct for AddSyslogJsonAuditLogPublisherRequest
type AddSyslogJsonAuditLogPublisherRequest struct {
	// Name of the new Log Publisher
	PublisherName string `json:"publisherName"`
	Schemas []EnumsyslogJsonAuditLogPublisherSchemaUrn `json:"schemas"`
	SyslogExternalServer []string `json:"syslogExternalServer"`
	SyslogFacility EnumlogPublisherSyslogFacilityProp `json:"syslogFacility"`
	SyslogSeverity EnumlogPublisherSyslogSeverityProp `json:"syslogSeverity"`
	// The local host name that will be included in syslog messages that are logged by this Syslog JSON Audit Log Publisher.
	SyslogMessageHostName *string `json:"syslogMessageHostName,omitempty"`
	// The application name that will be included in syslog messages that are logged by this Syslog JSON Audit Log Publisher.
	SyslogMessageApplicationName *string `json:"syslogMessageApplicationName,omitempty"`
	// The maximum number of log records that can be stored in the asynchronous queue.
	QueueSize *int32 `json:"queueSize,omitempty"`
	// Indicates whether the JSON objects should use a multi-line representation (with each object field and array value on its own line) that may be easier for administrators to read, but each message will be larger (because of additional spaces and end-of-line markers), and it may be more difficult to consume and parse through some text-oriented tools.
	WriteMultiLineMessages *bool `json:"writeMultiLineMessages,omitempty"`
	// Indicates whether the audit log should be written in reversible form so that it is possible to revert the changes if desired.
	UseReversibleForm *bool `json:"useReversibleForm,omitempty"`
	SoftDeleteEntryAuditBehavior *EnumlogPublisherSoftDeleteEntryAuditBehaviorProp `json:"softDeleteEntryAuditBehavior,omitempty"`
	// Indicates whether to include information about any operation purpose request control that may have been included in the request.
	IncludeOperationPurposeRequestControl *bool `json:"includeOperationPurposeRequestControl,omitempty"`
	// Indicates whether to include information about any intermediate client request control that may have been included in the request.
	IncludeIntermediateClientRequestControl *bool `json:"includeIntermediateClientRequestControl,omitempty"`
	ObscureAttribute []string `json:"obscureAttribute,omitempty"`
	ExcludeAttribute []string `json:"excludeAttribute,omitempty"`
	// Indicates whether internal operations (for example, operations that are initiated by plugins) should be logged along with the operations that are requested by users.
	SuppressInternalOperations *bool `json:"suppressInternalOperations,omitempty"`
	// Indicates whether log messages should include the product name for the Directory Server.
	IncludeProductName *bool `json:"includeProductName,omitempty"`
	// Indicates whether log messages should include the instance name for the Directory Server.
	IncludeInstanceName *bool `json:"includeInstanceName,omitempty"`
	// Indicates whether log messages should include the startup ID for the Directory Server, which is a value assigned to the server instance at startup and may be used to identify when the server has been restarted.
	IncludeStartupID *bool `json:"includeStartupID,omitempty"`
	// Indicates whether log messages should include the thread ID for the Directory Server in each log message. This ID can be used to correlate log messages from the same thread within a single log as well as generated by the same thread across different types of log files. More information about the thread with a specific ID can be obtained using the cn=JVM Stack Trace,cn=monitor entry.
	IncludeThreadID *bool `json:"includeThreadID,omitempty"`
	// Indicates whether log messages for operation requests should include the DN of the authenticated user for the client connection on which the operation was requested.
	IncludeRequesterDN *bool `json:"includeRequesterDN,omitempty"`
	// Indicates whether log messages for operation requests should include the IP address of the client that requested the operation.
	IncludeRequesterIPAddress *bool `json:"includeRequesterIPAddress,omitempty"`
	// Indicates whether log messages for operation requests should include a list of the OIDs of any controls included in the request.
	IncludeRequestControls *bool `json:"includeRequestControls,omitempty"`
	// Indicates whether log messages for operation results should include a list of the OIDs of any controls included in the result.
	IncludeResponseControls *bool `json:"includeResponseControls,omitempty"`
	// Indicates whether to log information about the replication change ID.
	IncludeReplicationChangeID *bool `json:"includeReplicationChangeID,omitempty"`
	// Indicates whether to log information about connections established to the server.
	LogConnects *bool `json:"logConnects,omitempty"`
	// Indicates whether to log information about connections that have been closed by the client or terminated by the server.
	LogDisconnects *bool `json:"logDisconnects,omitempty"`
	// Indicates whether to log information about the result of any security negotiation (e.g., SSL handshake) processing that has been performed.
	LogSecurityNegotiation *bool `json:"logSecurityNegotiation,omitempty"`
	// Indicates whether to log information about any client certificates presented to the server.
	LogClientCertificates *bool `json:"logClientCertificates,omitempty"`
	// Indicates whether to log information about requests received from clients.
	LogRequests *bool `json:"logRequests,omitempty"`
	// Indicates whether to log information about the results of client requests.
	LogResults *bool `json:"logResults,omitempty"`
	// Indicates whether to log information about search result entries sent to the client.
	LogSearchEntries *bool `json:"logSearchEntries,omitempty"`
	// Indicates whether to log information about search result references sent to the client.
	LogSearchReferences *bool `json:"logSearchReferences,omitempty"`
	// Indicates whether to log information about intermediate responses sent to the client.
	LogIntermediateResponses *bool `json:"logIntermediateResponses,omitempty"`
	// Indicates whether access messages that are generated by replication operations should be suppressed.
	SuppressReplicationOperations *bool `json:"suppressReplicationOperations,omitempty"`
	// Indicates whether to automatically log result messages for any operation in which the corresponding request was logged. In such cases, the result, entry, and reference criteria will be ignored, although the log-responses, log-search-entries, and log-search-references properties will be honored.
	CorrelateRequestsAndResults *bool `json:"correlateRequestsAndResults,omitempty"`
	// Specifies a set of connection criteria that must match the associated client connection in order for a connect, disconnect, request, or result message to be logged.
	ConnectionCriteria *string `json:"connectionCriteria,omitempty"`
	// Specifies a set of request criteria that must match the associated operation request in order for a request or result to be logged by this Access Log Publisher.
	RequestCriteria *string `json:"requestCriteria,omitempty"`
	// Specifies a set of result criteria that must match the associated operation result in order for that result to be logged by this Access Log Publisher.
	ResultCriteria *string `json:"resultCriteria,omitempty"`
	// Specifies a set of search entry criteria that must match the associated search result entry in order for that it to be logged by this Access Log Publisher.
	SearchEntryCriteria *string `json:"searchEntryCriteria,omitempty"`
	// Specifies a set of search reference criteria that must match the associated search result reference in order for that it to be logged by this Access Log Publisher.
	SearchReferenceCriteria *string `json:"searchReferenceCriteria,omitempty"`
	// A description for this Log Publisher
	Description *string `json:"description,omitempty"`
	// Indicates whether the Log Publisher is enabled for use.
	Enabled bool `json:"enabled"`
	LoggingErrorBehavior *EnumlogPublisherLoggingErrorBehaviorProp `json:"loggingErrorBehavior,omitempty"`
}

// NewAddSyslogJsonAuditLogPublisherRequest instantiates a new AddSyslogJsonAuditLogPublisherRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddSyslogJsonAuditLogPublisherRequest(publisherName string, schemas []EnumsyslogJsonAuditLogPublisherSchemaUrn, syslogExternalServer []string, syslogFacility EnumlogPublisherSyslogFacilityProp, syslogSeverity EnumlogPublisherSyslogSeverityProp, enabled bool) *AddSyslogJsonAuditLogPublisherRequest {
	this := AddSyslogJsonAuditLogPublisherRequest{}
	this.PublisherName = publisherName
	this.Schemas = schemas
	this.SyslogExternalServer = syslogExternalServer
	this.SyslogFacility = syslogFacility
	this.SyslogSeverity = syslogSeverity
	this.Enabled = enabled
	return &this
}

// NewAddSyslogJsonAuditLogPublisherRequestWithDefaults instantiates a new AddSyslogJsonAuditLogPublisherRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddSyslogJsonAuditLogPublisherRequestWithDefaults() *AddSyslogJsonAuditLogPublisherRequest {
	this := AddSyslogJsonAuditLogPublisherRequest{}
	return &this
}

// GetPublisherName returns the PublisherName field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetPublisherName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublisherName
}

// GetPublisherNameOk returns a tuple with the PublisherName field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetPublisherNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.PublisherName, true
}

// SetPublisherName sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetPublisherName(v string) {
	o.PublisherName = v
}

// GetSchemas returns the Schemas field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSchemas() []EnumsyslogJsonAuditLogPublisherSchemaUrn {
	if o == nil {
		var ret []EnumsyslogJsonAuditLogPublisherSchemaUrn
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSchemasOk() ([]EnumsyslogJsonAuditLogPublisherSchemaUrn, bool) {
	if o == nil {
    return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSchemas(v []EnumsyslogJsonAuditLogPublisherSchemaUrn) {
	o.Schemas = v
}

// GetSyslogExternalServer returns the SyslogExternalServer field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogExternalServer() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SyslogExternalServer
}

// GetSyslogExternalServerOk returns a tuple with the SyslogExternalServer field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogExternalServerOk() ([]string, bool) {
	if o == nil {
    return nil, false
	}
	return o.SyslogExternalServer, true
}

// SetSyslogExternalServer sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSyslogExternalServer(v []string) {
	o.SyslogExternalServer = v
}

// GetSyslogFacility returns the SyslogFacility field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogFacility() EnumlogPublisherSyslogFacilityProp {
	if o == nil {
		var ret EnumlogPublisherSyslogFacilityProp
		return ret
	}

	return o.SyslogFacility
}

// GetSyslogFacilityOk returns a tuple with the SyslogFacility field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogFacilityOk() (*EnumlogPublisherSyslogFacilityProp, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SyslogFacility, true
}

// SetSyslogFacility sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSyslogFacility(v EnumlogPublisherSyslogFacilityProp) {
	o.SyslogFacility = v
}

// GetSyslogSeverity returns the SyslogSeverity field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogSeverity() EnumlogPublisherSyslogSeverityProp {
	if o == nil {
		var ret EnumlogPublisherSyslogSeverityProp
		return ret
	}

	return o.SyslogSeverity
}

// GetSyslogSeverityOk returns a tuple with the SyslogSeverity field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogSeverityOk() (*EnumlogPublisherSyslogSeverityProp, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SyslogSeverity, true
}

// SetSyslogSeverity sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSyslogSeverity(v EnumlogPublisherSyslogSeverityProp) {
	o.SyslogSeverity = v
}

// GetSyslogMessageHostName returns the SyslogMessageHostName field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogMessageHostName() string {
	if o == nil || isNil(o.SyslogMessageHostName) {
		var ret string
		return ret
	}
	return *o.SyslogMessageHostName
}

// GetSyslogMessageHostNameOk returns a tuple with the SyslogMessageHostName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogMessageHostNameOk() (*string, bool) {
	if o == nil || isNil(o.SyslogMessageHostName) {
    return nil, false
	}
	return o.SyslogMessageHostName, true
}

// HasSyslogMessageHostName returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSyslogMessageHostName() bool {
	if o != nil && !isNil(o.SyslogMessageHostName) {
		return true
	}

	return false
}

// SetSyslogMessageHostName gets a reference to the given string and assigns it to the SyslogMessageHostName field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSyslogMessageHostName(v string) {
	o.SyslogMessageHostName = &v
}

// GetSyslogMessageApplicationName returns the SyslogMessageApplicationName field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogMessageApplicationName() string {
	if o == nil || isNil(o.SyslogMessageApplicationName) {
		var ret string
		return ret
	}
	return *o.SyslogMessageApplicationName
}

// GetSyslogMessageApplicationNameOk returns a tuple with the SyslogMessageApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSyslogMessageApplicationNameOk() (*string, bool) {
	if o == nil || isNil(o.SyslogMessageApplicationName) {
    return nil, false
	}
	return o.SyslogMessageApplicationName, true
}

// HasSyslogMessageApplicationName returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSyslogMessageApplicationName() bool {
	if o != nil && !isNil(o.SyslogMessageApplicationName) {
		return true
	}

	return false
}

// SetSyslogMessageApplicationName gets a reference to the given string and assigns it to the SyslogMessageApplicationName field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSyslogMessageApplicationName(v string) {
	o.SyslogMessageApplicationName = &v
}

// GetQueueSize returns the QueueSize field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetQueueSize() int32 {
	if o == nil || isNil(o.QueueSize) {
		var ret int32
		return ret
	}
	return *o.QueueSize
}

// GetQueueSizeOk returns a tuple with the QueueSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetQueueSizeOk() (*int32, bool) {
	if o == nil || isNil(o.QueueSize) {
    return nil, false
	}
	return o.QueueSize, true
}

// HasQueueSize returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasQueueSize() bool {
	if o != nil && !isNil(o.QueueSize) {
		return true
	}

	return false
}

// SetQueueSize gets a reference to the given int32 and assigns it to the QueueSize field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetQueueSize(v int32) {
	o.QueueSize = &v
}

// GetWriteMultiLineMessages returns the WriteMultiLineMessages field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetWriteMultiLineMessages() bool {
	if o == nil || isNil(o.WriteMultiLineMessages) {
		var ret bool
		return ret
	}
	return *o.WriteMultiLineMessages
}

// GetWriteMultiLineMessagesOk returns a tuple with the WriteMultiLineMessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetWriteMultiLineMessagesOk() (*bool, bool) {
	if o == nil || isNil(o.WriteMultiLineMessages) {
    return nil, false
	}
	return o.WriteMultiLineMessages, true
}

// HasWriteMultiLineMessages returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasWriteMultiLineMessages() bool {
	if o != nil && !isNil(o.WriteMultiLineMessages) {
		return true
	}

	return false
}

// SetWriteMultiLineMessages gets a reference to the given bool and assigns it to the WriteMultiLineMessages field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetWriteMultiLineMessages(v bool) {
	o.WriteMultiLineMessages = &v
}

// GetUseReversibleForm returns the UseReversibleForm field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetUseReversibleForm() bool {
	if o == nil || isNil(o.UseReversibleForm) {
		var ret bool
		return ret
	}
	return *o.UseReversibleForm
}

// GetUseReversibleFormOk returns a tuple with the UseReversibleForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetUseReversibleFormOk() (*bool, bool) {
	if o == nil || isNil(o.UseReversibleForm) {
    return nil, false
	}
	return o.UseReversibleForm, true
}

// HasUseReversibleForm returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasUseReversibleForm() bool {
	if o != nil && !isNil(o.UseReversibleForm) {
		return true
	}

	return false
}

// SetUseReversibleForm gets a reference to the given bool and assigns it to the UseReversibleForm field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetUseReversibleForm(v bool) {
	o.UseReversibleForm = &v
}

// GetSoftDeleteEntryAuditBehavior returns the SoftDeleteEntryAuditBehavior field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSoftDeleteEntryAuditBehavior() EnumlogPublisherSoftDeleteEntryAuditBehaviorProp {
	if o == nil || isNil(o.SoftDeleteEntryAuditBehavior) {
		var ret EnumlogPublisherSoftDeleteEntryAuditBehaviorProp
		return ret
	}
	return *o.SoftDeleteEntryAuditBehavior
}

// GetSoftDeleteEntryAuditBehaviorOk returns a tuple with the SoftDeleteEntryAuditBehavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSoftDeleteEntryAuditBehaviorOk() (*EnumlogPublisherSoftDeleteEntryAuditBehaviorProp, bool) {
	if o == nil || isNil(o.SoftDeleteEntryAuditBehavior) {
    return nil, false
	}
	return o.SoftDeleteEntryAuditBehavior, true
}

// HasSoftDeleteEntryAuditBehavior returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSoftDeleteEntryAuditBehavior() bool {
	if o != nil && !isNil(o.SoftDeleteEntryAuditBehavior) {
		return true
	}

	return false
}

// SetSoftDeleteEntryAuditBehavior gets a reference to the given EnumlogPublisherSoftDeleteEntryAuditBehaviorProp and assigns it to the SoftDeleteEntryAuditBehavior field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSoftDeleteEntryAuditBehavior(v EnumlogPublisherSoftDeleteEntryAuditBehaviorProp) {
	o.SoftDeleteEntryAuditBehavior = &v
}

// GetIncludeOperationPurposeRequestControl returns the IncludeOperationPurposeRequestControl field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeOperationPurposeRequestControl() bool {
	if o == nil || isNil(o.IncludeOperationPurposeRequestControl) {
		var ret bool
		return ret
	}
	return *o.IncludeOperationPurposeRequestControl
}

// GetIncludeOperationPurposeRequestControlOk returns a tuple with the IncludeOperationPurposeRequestControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeOperationPurposeRequestControlOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeOperationPurposeRequestControl) {
    return nil, false
	}
	return o.IncludeOperationPurposeRequestControl, true
}

// HasIncludeOperationPurposeRequestControl returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeOperationPurposeRequestControl() bool {
	if o != nil && !isNil(o.IncludeOperationPurposeRequestControl) {
		return true
	}

	return false
}

// SetIncludeOperationPurposeRequestControl gets a reference to the given bool and assigns it to the IncludeOperationPurposeRequestControl field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeOperationPurposeRequestControl(v bool) {
	o.IncludeOperationPurposeRequestControl = &v
}

// GetIncludeIntermediateClientRequestControl returns the IncludeIntermediateClientRequestControl field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeIntermediateClientRequestControl() bool {
	if o == nil || isNil(o.IncludeIntermediateClientRequestControl) {
		var ret bool
		return ret
	}
	return *o.IncludeIntermediateClientRequestControl
}

// GetIncludeIntermediateClientRequestControlOk returns a tuple with the IncludeIntermediateClientRequestControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeIntermediateClientRequestControlOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeIntermediateClientRequestControl) {
    return nil, false
	}
	return o.IncludeIntermediateClientRequestControl, true
}

// HasIncludeIntermediateClientRequestControl returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeIntermediateClientRequestControl() bool {
	if o != nil && !isNil(o.IncludeIntermediateClientRequestControl) {
		return true
	}

	return false
}

// SetIncludeIntermediateClientRequestControl gets a reference to the given bool and assigns it to the IncludeIntermediateClientRequestControl field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeIntermediateClientRequestControl(v bool) {
	o.IncludeIntermediateClientRequestControl = &v
}

// GetObscureAttribute returns the ObscureAttribute field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetObscureAttribute() []string {
	if o == nil || isNil(o.ObscureAttribute) {
		var ret []string
		return ret
	}
	return o.ObscureAttribute
}

// GetObscureAttributeOk returns a tuple with the ObscureAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetObscureAttributeOk() ([]string, bool) {
	if o == nil || isNil(o.ObscureAttribute) {
    return nil, false
	}
	return o.ObscureAttribute, true
}

// HasObscureAttribute returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasObscureAttribute() bool {
	if o != nil && !isNil(o.ObscureAttribute) {
		return true
	}

	return false
}

// SetObscureAttribute gets a reference to the given []string and assigns it to the ObscureAttribute field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetObscureAttribute(v []string) {
	o.ObscureAttribute = v
}

// GetExcludeAttribute returns the ExcludeAttribute field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetExcludeAttribute() []string {
	if o == nil || isNil(o.ExcludeAttribute) {
		var ret []string
		return ret
	}
	return o.ExcludeAttribute
}

// GetExcludeAttributeOk returns a tuple with the ExcludeAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetExcludeAttributeOk() ([]string, bool) {
	if o == nil || isNil(o.ExcludeAttribute) {
    return nil, false
	}
	return o.ExcludeAttribute, true
}

// HasExcludeAttribute returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasExcludeAttribute() bool {
	if o != nil && !isNil(o.ExcludeAttribute) {
		return true
	}

	return false
}

// SetExcludeAttribute gets a reference to the given []string and assigns it to the ExcludeAttribute field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetExcludeAttribute(v []string) {
	o.ExcludeAttribute = v
}

// GetSuppressInternalOperations returns the SuppressInternalOperations field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSuppressInternalOperations() bool {
	if o == nil || isNil(o.SuppressInternalOperations) {
		var ret bool
		return ret
	}
	return *o.SuppressInternalOperations
}

// GetSuppressInternalOperationsOk returns a tuple with the SuppressInternalOperations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSuppressInternalOperationsOk() (*bool, bool) {
	if o == nil || isNil(o.SuppressInternalOperations) {
    return nil, false
	}
	return o.SuppressInternalOperations, true
}

// HasSuppressInternalOperations returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSuppressInternalOperations() bool {
	if o != nil && !isNil(o.SuppressInternalOperations) {
		return true
	}

	return false
}

// SetSuppressInternalOperations gets a reference to the given bool and assigns it to the SuppressInternalOperations field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSuppressInternalOperations(v bool) {
	o.SuppressInternalOperations = &v
}

// GetIncludeProductName returns the IncludeProductName field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeProductName() bool {
	if o == nil || isNil(o.IncludeProductName) {
		var ret bool
		return ret
	}
	return *o.IncludeProductName
}

// GetIncludeProductNameOk returns a tuple with the IncludeProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeProductNameOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeProductName) {
    return nil, false
	}
	return o.IncludeProductName, true
}

// HasIncludeProductName returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeProductName() bool {
	if o != nil && !isNil(o.IncludeProductName) {
		return true
	}

	return false
}

// SetIncludeProductName gets a reference to the given bool and assigns it to the IncludeProductName field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeProductName(v bool) {
	o.IncludeProductName = &v
}

// GetIncludeInstanceName returns the IncludeInstanceName field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeInstanceName() bool {
	if o == nil || isNil(o.IncludeInstanceName) {
		var ret bool
		return ret
	}
	return *o.IncludeInstanceName
}

// GetIncludeInstanceNameOk returns a tuple with the IncludeInstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeInstanceNameOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeInstanceName) {
    return nil, false
	}
	return o.IncludeInstanceName, true
}

// HasIncludeInstanceName returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeInstanceName() bool {
	if o != nil && !isNil(o.IncludeInstanceName) {
		return true
	}

	return false
}

// SetIncludeInstanceName gets a reference to the given bool and assigns it to the IncludeInstanceName field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeInstanceName(v bool) {
	o.IncludeInstanceName = &v
}

// GetIncludeStartupID returns the IncludeStartupID field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeStartupID() bool {
	if o == nil || isNil(o.IncludeStartupID) {
		var ret bool
		return ret
	}
	return *o.IncludeStartupID
}

// GetIncludeStartupIDOk returns a tuple with the IncludeStartupID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeStartupIDOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeStartupID) {
    return nil, false
	}
	return o.IncludeStartupID, true
}

// HasIncludeStartupID returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeStartupID() bool {
	if o != nil && !isNil(o.IncludeStartupID) {
		return true
	}

	return false
}

// SetIncludeStartupID gets a reference to the given bool and assigns it to the IncludeStartupID field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeStartupID(v bool) {
	o.IncludeStartupID = &v
}

// GetIncludeThreadID returns the IncludeThreadID field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeThreadID() bool {
	if o == nil || isNil(o.IncludeThreadID) {
		var ret bool
		return ret
	}
	return *o.IncludeThreadID
}

// GetIncludeThreadIDOk returns a tuple with the IncludeThreadID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeThreadIDOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeThreadID) {
    return nil, false
	}
	return o.IncludeThreadID, true
}

// HasIncludeThreadID returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeThreadID() bool {
	if o != nil && !isNil(o.IncludeThreadID) {
		return true
	}

	return false
}

// SetIncludeThreadID gets a reference to the given bool and assigns it to the IncludeThreadID field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeThreadID(v bool) {
	o.IncludeThreadID = &v
}

// GetIncludeRequesterDN returns the IncludeRequesterDN field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequesterDN() bool {
	if o == nil || isNil(o.IncludeRequesterDN) {
		var ret bool
		return ret
	}
	return *o.IncludeRequesterDN
}

// GetIncludeRequesterDNOk returns a tuple with the IncludeRequesterDN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequesterDNOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeRequesterDN) {
    return nil, false
	}
	return o.IncludeRequesterDN, true
}

// HasIncludeRequesterDN returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeRequesterDN() bool {
	if o != nil && !isNil(o.IncludeRequesterDN) {
		return true
	}

	return false
}

// SetIncludeRequesterDN gets a reference to the given bool and assigns it to the IncludeRequesterDN field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeRequesterDN(v bool) {
	o.IncludeRequesterDN = &v
}

// GetIncludeRequesterIPAddress returns the IncludeRequesterIPAddress field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequesterIPAddress() bool {
	if o == nil || isNil(o.IncludeRequesterIPAddress) {
		var ret bool
		return ret
	}
	return *o.IncludeRequesterIPAddress
}

// GetIncludeRequesterIPAddressOk returns a tuple with the IncludeRequesterIPAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequesterIPAddressOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeRequesterIPAddress) {
    return nil, false
	}
	return o.IncludeRequesterIPAddress, true
}

// HasIncludeRequesterIPAddress returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeRequesterIPAddress() bool {
	if o != nil && !isNil(o.IncludeRequesterIPAddress) {
		return true
	}

	return false
}

// SetIncludeRequesterIPAddress gets a reference to the given bool and assigns it to the IncludeRequesterIPAddress field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeRequesterIPAddress(v bool) {
	o.IncludeRequesterIPAddress = &v
}

// GetIncludeRequestControls returns the IncludeRequestControls field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequestControls() bool {
	if o == nil || isNil(o.IncludeRequestControls) {
		var ret bool
		return ret
	}
	return *o.IncludeRequestControls
}

// GetIncludeRequestControlsOk returns a tuple with the IncludeRequestControls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeRequestControlsOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeRequestControls) {
    return nil, false
	}
	return o.IncludeRequestControls, true
}

// HasIncludeRequestControls returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeRequestControls() bool {
	if o != nil && !isNil(o.IncludeRequestControls) {
		return true
	}

	return false
}

// SetIncludeRequestControls gets a reference to the given bool and assigns it to the IncludeRequestControls field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeRequestControls(v bool) {
	o.IncludeRequestControls = &v
}

// GetIncludeResponseControls returns the IncludeResponseControls field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeResponseControls() bool {
	if o == nil || isNil(o.IncludeResponseControls) {
		var ret bool
		return ret
	}
	return *o.IncludeResponseControls
}

// GetIncludeResponseControlsOk returns a tuple with the IncludeResponseControls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeResponseControlsOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeResponseControls) {
    return nil, false
	}
	return o.IncludeResponseControls, true
}

// HasIncludeResponseControls returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeResponseControls() bool {
	if o != nil && !isNil(o.IncludeResponseControls) {
		return true
	}

	return false
}

// SetIncludeResponseControls gets a reference to the given bool and assigns it to the IncludeResponseControls field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeResponseControls(v bool) {
	o.IncludeResponseControls = &v
}

// GetIncludeReplicationChangeID returns the IncludeReplicationChangeID field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeReplicationChangeID() bool {
	if o == nil || isNil(o.IncludeReplicationChangeID) {
		var ret bool
		return ret
	}
	return *o.IncludeReplicationChangeID
}

// GetIncludeReplicationChangeIDOk returns a tuple with the IncludeReplicationChangeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetIncludeReplicationChangeIDOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeReplicationChangeID) {
    return nil, false
	}
	return o.IncludeReplicationChangeID, true
}

// HasIncludeReplicationChangeID returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasIncludeReplicationChangeID() bool {
	if o != nil && !isNil(o.IncludeReplicationChangeID) {
		return true
	}

	return false
}

// SetIncludeReplicationChangeID gets a reference to the given bool and assigns it to the IncludeReplicationChangeID field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetIncludeReplicationChangeID(v bool) {
	o.IncludeReplicationChangeID = &v
}

// GetLogConnects returns the LogConnects field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogConnects() bool {
	if o == nil || isNil(o.LogConnects) {
		var ret bool
		return ret
	}
	return *o.LogConnects
}

// GetLogConnectsOk returns a tuple with the LogConnects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogConnectsOk() (*bool, bool) {
	if o == nil || isNil(o.LogConnects) {
    return nil, false
	}
	return o.LogConnects, true
}

// HasLogConnects returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogConnects() bool {
	if o != nil && !isNil(o.LogConnects) {
		return true
	}

	return false
}

// SetLogConnects gets a reference to the given bool and assigns it to the LogConnects field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogConnects(v bool) {
	o.LogConnects = &v
}

// GetLogDisconnects returns the LogDisconnects field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogDisconnects() bool {
	if o == nil || isNil(o.LogDisconnects) {
		var ret bool
		return ret
	}
	return *o.LogDisconnects
}

// GetLogDisconnectsOk returns a tuple with the LogDisconnects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogDisconnectsOk() (*bool, bool) {
	if o == nil || isNil(o.LogDisconnects) {
    return nil, false
	}
	return o.LogDisconnects, true
}

// HasLogDisconnects returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogDisconnects() bool {
	if o != nil && !isNil(o.LogDisconnects) {
		return true
	}

	return false
}

// SetLogDisconnects gets a reference to the given bool and assigns it to the LogDisconnects field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogDisconnects(v bool) {
	o.LogDisconnects = &v
}

// GetLogSecurityNegotiation returns the LogSecurityNegotiation field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSecurityNegotiation() bool {
	if o == nil || isNil(o.LogSecurityNegotiation) {
		var ret bool
		return ret
	}
	return *o.LogSecurityNegotiation
}

// GetLogSecurityNegotiationOk returns a tuple with the LogSecurityNegotiation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSecurityNegotiationOk() (*bool, bool) {
	if o == nil || isNil(o.LogSecurityNegotiation) {
    return nil, false
	}
	return o.LogSecurityNegotiation, true
}

// HasLogSecurityNegotiation returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogSecurityNegotiation() bool {
	if o != nil && !isNil(o.LogSecurityNegotiation) {
		return true
	}

	return false
}

// SetLogSecurityNegotiation gets a reference to the given bool and assigns it to the LogSecurityNegotiation field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogSecurityNegotiation(v bool) {
	o.LogSecurityNegotiation = &v
}

// GetLogClientCertificates returns the LogClientCertificates field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogClientCertificates() bool {
	if o == nil || isNil(o.LogClientCertificates) {
		var ret bool
		return ret
	}
	return *o.LogClientCertificates
}

// GetLogClientCertificatesOk returns a tuple with the LogClientCertificates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogClientCertificatesOk() (*bool, bool) {
	if o == nil || isNil(o.LogClientCertificates) {
    return nil, false
	}
	return o.LogClientCertificates, true
}

// HasLogClientCertificates returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogClientCertificates() bool {
	if o != nil && !isNil(o.LogClientCertificates) {
		return true
	}

	return false
}

// SetLogClientCertificates gets a reference to the given bool and assigns it to the LogClientCertificates field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogClientCertificates(v bool) {
	o.LogClientCertificates = &v
}

// GetLogRequests returns the LogRequests field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogRequests() bool {
	if o == nil || isNil(o.LogRequests) {
		var ret bool
		return ret
	}
	return *o.LogRequests
}

// GetLogRequestsOk returns a tuple with the LogRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogRequestsOk() (*bool, bool) {
	if o == nil || isNil(o.LogRequests) {
    return nil, false
	}
	return o.LogRequests, true
}

// HasLogRequests returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogRequests() bool {
	if o != nil && !isNil(o.LogRequests) {
		return true
	}

	return false
}

// SetLogRequests gets a reference to the given bool and assigns it to the LogRequests field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogRequests(v bool) {
	o.LogRequests = &v
}

// GetLogResults returns the LogResults field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogResults() bool {
	if o == nil || isNil(o.LogResults) {
		var ret bool
		return ret
	}
	return *o.LogResults
}

// GetLogResultsOk returns a tuple with the LogResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogResultsOk() (*bool, bool) {
	if o == nil || isNil(o.LogResults) {
    return nil, false
	}
	return o.LogResults, true
}

// HasLogResults returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogResults() bool {
	if o != nil && !isNil(o.LogResults) {
		return true
	}

	return false
}

// SetLogResults gets a reference to the given bool and assigns it to the LogResults field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogResults(v bool) {
	o.LogResults = &v
}

// GetLogSearchEntries returns the LogSearchEntries field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSearchEntries() bool {
	if o == nil || isNil(o.LogSearchEntries) {
		var ret bool
		return ret
	}
	return *o.LogSearchEntries
}

// GetLogSearchEntriesOk returns a tuple with the LogSearchEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSearchEntriesOk() (*bool, bool) {
	if o == nil || isNil(o.LogSearchEntries) {
    return nil, false
	}
	return o.LogSearchEntries, true
}

// HasLogSearchEntries returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogSearchEntries() bool {
	if o != nil && !isNil(o.LogSearchEntries) {
		return true
	}

	return false
}

// SetLogSearchEntries gets a reference to the given bool and assigns it to the LogSearchEntries field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogSearchEntries(v bool) {
	o.LogSearchEntries = &v
}

// GetLogSearchReferences returns the LogSearchReferences field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSearchReferences() bool {
	if o == nil || isNil(o.LogSearchReferences) {
		var ret bool
		return ret
	}
	return *o.LogSearchReferences
}

// GetLogSearchReferencesOk returns a tuple with the LogSearchReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogSearchReferencesOk() (*bool, bool) {
	if o == nil || isNil(o.LogSearchReferences) {
    return nil, false
	}
	return o.LogSearchReferences, true
}

// HasLogSearchReferences returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogSearchReferences() bool {
	if o != nil && !isNil(o.LogSearchReferences) {
		return true
	}

	return false
}

// SetLogSearchReferences gets a reference to the given bool and assigns it to the LogSearchReferences field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogSearchReferences(v bool) {
	o.LogSearchReferences = &v
}

// GetLogIntermediateResponses returns the LogIntermediateResponses field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogIntermediateResponses() bool {
	if o == nil || isNil(o.LogIntermediateResponses) {
		var ret bool
		return ret
	}
	return *o.LogIntermediateResponses
}

// GetLogIntermediateResponsesOk returns a tuple with the LogIntermediateResponses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLogIntermediateResponsesOk() (*bool, bool) {
	if o == nil || isNil(o.LogIntermediateResponses) {
    return nil, false
	}
	return o.LogIntermediateResponses, true
}

// HasLogIntermediateResponses returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLogIntermediateResponses() bool {
	if o != nil && !isNil(o.LogIntermediateResponses) {
		return true
	}

	return false
}

// SetLogIntermediateResponses gets a reference to the given bool and assigns it to the LogIntermediateResponses field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLogIntermediateResponses(v bool) {
	o.LogIntermediateResponses = &v
}

// GetSuppressReplicationOperations returns the SuppressReplicationOperations field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSuppressReplicationOperations() bool {
	if o == nil || isNil(o.SuppressReplicationOperations) {
		var ret bool
		return ret
	}
	return *o.SuppressReplicationOperations
}

// GetSuppressReplicationOperationsOk returns a tuple with the SuppressReplicationOperations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSuppressReplicationOperationsOk() (*bool, bool) {
	if o == nil || isNil(o.SuppressReplicationOperations) {
    return nil, false
	}
	return o.SuppressReplicationOperations, true
}

// HasSuppressReplicationOperations returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSuppressReplicationOperations() bool {
	if o != nil && !isNil(o.SuppressReplicationOperations) {
		return true
	}

	return false
}

// SetSuppressReplicationOperations gets a reference to the given bool and assigns it to the SuppressReplicationOperations field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSuppressReplicationOperations(v bool) {
	o.SuppressReplicationOperations = &v
}

// GetCorrelateRequestsAndResults returns the CorrelateRequestsAndResults field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetCorrelateRequestsAndResults() bool {
	if o == nil || isNil(o.CorrelateRequestsAndResults) {
		var ret bool
		return ret
	}
	return *o.CorrelateRequestsAndResults
}

// GetCorrelateRequestsAndResultsOk returns a tuple with the CorrelateRequestsAndResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetCorrelateRequestsAndResultsOk() (*bool, bool) {
	if o == nil || isNil(o.CorrelateRequestsAndResults) {
    return nil, false
	}
	return o.CorrelateRequestsAndResults, true
}

// HasCorrelateRequestsAndResults returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasCorrelateRequestsAndResults() bool {
	if o != nil && !isNil(o.CorrelateRequestsAndResults) {
		return true
	}

	return false
}

// SetCorrelateRequestsAndResults gets a reference to the given bool and assigns it to the CorrelateRequestsAndResults field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetCorrelateRequestsAndResults(v bool) {
	o.CorrelateRequestsAndResults = &v
}

// GetConnectionCriteria returns the ConnectionCriteria field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetConnectionCriteria() string {
	if o == nil || isNil(o.ConnectionCriteria) {
		var ret string
		return ret
	}
	return *o.ConnectionCriteria
}

// GetConnectionCriteriaOk returns a tuple with the ConnectionCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetConnectionCriteriaOk() (*string, bool) {
	if o == nil || isNil(o.ConnectionCriteria) {
    return nil, false
	}
	return o.ConnectionCriteria, true
}

// HasConnectionCriteria returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasConnectionCriteria() bool {
	if o != nil && !isNil(o.ConnectionCriteria) {
		return true
	}

	return false
}

// SetConnectionCriteria gets a reference to the given string and assigns it to the ConnectionCriteria field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetConnectionCriteria(v string) {
	o.ConnectionCriteria = &v
}

// GetRequestCriteria returns the RequestCriteria field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetRequestCriteria() string {
	if o == nil || isNil(o.RequestCriteria) {
		var ret string
		return ret
	}
	return *o.RequestCriteria
}

// GetRequestCriteriaOk returns a tuple with the RequestCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetRequestCriteriaOk() (*string, bool) {
	if o == nil || isNil(o.RequestCriteria) {
    return nil, false
	}
	return o.RequestCriteria, true
}

// HasRequestCriteria returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasRequestCriteria() bool {
	if o != nil && !isNil(o.RequestCriteria) {
		return true
	}

	return false
}

// SetRequestCriteria gets a reference to the given string and assigns it to the RequestCriteria field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetRequestCriteria(v string) {
	o.RequestCriteria = &v
}

// GetResultCriteria returns the ResultCriteria field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetResultCriteria() string {
	if o == nil || isNil(o.ResultCriteria) {
		var ret string
		return ret
	}
	return *o.ResultCriteria
}

// GetResultCriteriaOk returns a tuple with the ResultCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetResultCriteriaOk() (*string, bool) {
	if o == nil || isNil(o.ResultCriteria) {
    return nil, false
	}
	return o.ResultCriteria, true
}

// HasResultCriteria returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasResultCriteria() bool {
	if o != nil && !isNil(o.ResultCriteria) {
		return true
	}

	return false
}

// SetResultCriteria gets a reference to the given string and assigns it to the ResultCriteria field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetResultCriteria(v string) {
	o.ResultCriteria = &v
}

// GetSearchEntryCriteria returns the SearchEntryCriteria field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSearchEntryCriteria() string {
	if o == nil || isNil(o.SearchEntryCriteria) {
		var ret string
		return ret
	}
	return *o.SearchEntryCriteria
}

// GetSearchEntryCriteriaOk returns a tuple with the SearchEntryCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSearchEntryCriteriaOk() (*string, bool) {
	if o == nil || isNil(o.SearchEntryCriteria) {
    return nil, false
	}
	return o.SearchEntryCriteria, true
}

// HasSearchEntryCriteria returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSearchEntryCriteria() bool {
	if o != nil && !isNil(o.SearchEntryCriteria) {
		return true
	}

	return false
}

// SetSearchEntryCriteria gets a reference to the given string and assigns it to the SearchEntryCriteria field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSearchEntryCriteria(v string) {
	o.SearchEntryCriteria = &v
}

// GetSearchReferenceCriteria returns the SearchReferenceCriteria field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSearchReferenceCriteria() string {
	if o == nil || isNil(o.SearchReferenceCriteria) {
		var ret string
		return ret
	}
	return *o.SearchReferenceCriteria
}

// GetSearchReferenceCriteriaOk returns a tuple with the SearchReferenceCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetSearchReferenceCriteriaOk() (*string, bool) {
	if o == nil || isNil(o.SearchReferenceCriteria) {
    return nil, false
	}
	return o.SearchReferenceCriteria, true
}

// HasSearchReferenceCriteria returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasSearchReferenceCriteria() bool {
	if o != nil && !isNil(o.SearchReferenceCriteria) {
		return true
	}

	return false
}

// SetSearchReferenceCriteria gets a reference to the given string and assigns it to the SearchReferenceCriteria field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetSearchReferenceCriteria(v string) {
	o.SearchReferenceCriteria = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value
func (o *AddSyslogJsonAuditLogPublisherRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AddSyslogJsonAuditLogPublisherRequest) SetEnabled(v bool) {
	o.Enabled = v
}

// GetLoggingErrorBehavior returns the LoggingErrorBehavior field value if set, zero value otherwise.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLoggingErrorBehavior() EnumlogPublisherLoggingErrorBehaviorProp {
	if o == nil || isNil(o.LoggingErrorBehavior) {
		var ret EnumlogPublisherLoggingErrorBehaviorProp
		return ret
	}
	return *o.LoggingErrorBehavior
}

// GetLoggingErrorBehaviorOk returns a tuple with the LoggingErrorBehavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) GetLoggingErrorBehaviorOk() (*EnumlogPublisherLoggingErrorBehaviorProp, bool) {
	if o == nil || isNil(o.LoggingErrorBehavior) {
    return nil, false
	}
	return o.LoggingErrorBehavior, true
}

// HasLoggingErrorBehavior returns a boolean if a field has been set.
func (o *AddSyslogJsonAuditLogPublisherRequest) HasLoggingErrorBehavior() bool {
	if o != nil && !isNil(o.LoggingErrorBehavior) {
		return true
	}

	return false
}

// SetLoggingErrorBehavior gets a reference to the given EnumlogPublisherLoggingErrorBehaviorProp and assigns it to the LoggingErrorBehavior field.
func (o *AddSyslogJsonAuditLogPublisherRequest) SetLoggingErrorBehavior(v EnumlogPublisherLoggingErrorBehaviorProp) {
	o.LoggingErrorBehavior = &v
}

func (o AddSyslogJsonAuditLogPublisherRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publisherName"] = o.PublisherName
	}
	if true {
		toSerialize["schemas"] = o.Schemas
	}
	if true {
		toSerialize["syslogExternalServer"] = o.SyslogExternalServer
	}
	if true {
		toSerialize["syslogFacility"] = o.SyslogFacility
	}
	if true {
		toSerialize["syslogSeverity"] = o.SyslogSeverity
	}
	if !isNil(o.SyslogMessageHostName) {
		toSerialize["syslogMessageHostName"] = o.SyslogMessageHostName
	}
	if !isNil(o.SyslogMessageApplicationName) {
		toSerialize["syslogMessageApplicationName"] = o.SyslogMessageApplicationName
	}
	if !isNil(o.QueueSize) {
		toSerialize["queueSize"] = o.QueueSize
	}
	if !isNil(o.WriteMultiLineMessages) {
		toSerialize["writeMultiLineMessages"] = o.WriteMultiLineMessages
	}
	if !isNil(o.UseReversibleForm) {
		toSerialize["useReversibleForm"] = o.UseReversibleForm
	}
	if !isNil(o.SoftDeleteEntryAuditBehavior) {
		toSerialize["softDeleteEntryAuditBehavior"] = o.SoftDeleteEntryAuditBehavior
	}
	if !isNil(o.IncludeOperationPurposeRequestControl) {
		toSerialize["includeOperationPurposeRequestControl"] = o.IncludeOperationPurposeRequestControl
	}
	if !isNil(o.IncludeIntermediateClientRequestControl) {
		toSerialize["includeIntermediateClientRequestControl"] = o.IncludeIntermediateClientRequestControl
	}
	if !isNil(o.ObscureAttribute) {
		toSerialize["obscureAttribute"] = o.ObscureAttribute
	}
	if !isNil(o.ExcludeAttribute) {
		toSerialize["excludeAttribute"] = o.ExcludeAttribute
	}
	if !isNil(o.SuppressInternalOperations) {
		toSerialize["suppressInternalOperations"] = o.SuppressInternalOperations
	}
	if !isNil(o.IncludeProductName) {
		toSerialize["includeProductName"] = o.IncludeProductName
	}
	if !isNil(o.IncludeInstanceName) {
		toSerialize["includeInstanceName"] = o.IncludeInstanceName
	}
	if !isNil(o.IncludeStartupID) {
		toSerialize["includeStartupID"] = o.IncludeStartupID
	}
	if !isNil(o.IncludeThreadID) {
		toSerialize["includeThreadID"] = o.IncludeThreadID
	}
	if !isNil(o.IncludeRequesterDN) {
		toSerialize["includeRequesterDN"] = o.IncludeRequesterDN
	}
	if !isNil(o.IncludeRequesterIPAddress) {
		toSerialize["includeRequesterIPAddress"] = o.IncludeRequesterIPAddress
	}
	if !isNil(o.IncludeRequestControls) {
		toSerialize["includeRequestControls"] = o.IncludeRequestControls
	}
	if !isNil(o.IncludeResponseControls) {
		toSerialize["includeResponseControls"] = o.IncludeResponseControls
	}
	if !isNil(o.IncludeReplicationChangeID) {
		toSerialize["includeReplicationChangeID"] = o.IncludeReplicationChangeID
	}
	if !isNil(o.LogConnects) {
		toSerialize["logConnects"] = o.LogConnects
	}
	if !isNil(o.LogDisconnects) {
		toSerialize["logDisconnects"] = o.LogDisconnects
	}
	if !isNil(o.LogSecurityNegotiation) {
		toSerialize["logSecurityNegotiation"] = o.LogSecurityNegotiation
	}
	if !isNil(o.LogClientCertificates) {
		toSerialize["logClientCertificates"] = o.LogClientCertificates
	}
	if !isNil(o.LogRequests) {
		toSerialize["logRequests"] = o.LogRequests
	}
	if !isNil(o.LogResults) {
		toSerialize["logResults"] = o.LogResults
	}
	if !isNil(o.LogSearchEntries) {
		toSerialize["logSearchEntries"] = o.LogSearchEntries
	}
	if !isNil(o.LogSearchReferences) {
		toSerialize["logSearchReferences"] = o.LogSearchReferences
	}
	if !isNil(o.LogIntermediateResponses) {
		toSerialize["logIntermediateResponses"] = o.LogIntermediateResponses
	}
	if !isNil(o.SuppressReplicationOperations) {
		toSerialize["suppressReplicationOperations"] = o.SuppressReplicationOperations
	}
	if !isNil(o.CorrelateRequestsAndResults) {
		toSerialize["correlateRequestsAndResults"] = o.CorrelateRequestsAndResults
	}
	if !isNil(o.ConnectionCriteria) {
		toSerialize["connectionCriteria"] = o.ConnectionCriteria
	}
	if !isNil(o.RequestCriteria) {
		toSerialize["requestCriteria"] = o.RequestCriteria
	}
	if !isNil(o.ResultCriteria) {
		toSerialize["resultCriteria"] = o.ResultCriteria
	}
	if !isNil(o.SearchEntryCriteria) {
		toSerialize["searchEntryCriteria"] = o.SearchEntryCriteria
	}
	if !isNil(o.SearchReferenceCriteria) {
		toSerialize["searchReferenceCriteria"] = o.SearchReferenceCriteria
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if !isNil(o.LoggingErrorBehavior) {
		toSerialize["loggingErrorBehavior"] = o.LoggingErrorBehavior
	}
	return json.Marshal(toSerialize)
}

type NullableAddSyslogJsonAuditLogPublisherRequest struct {
	value *AddSyslogJsonAuditLogPublisherRequest
	isSet bool
}

func (v NullableAddSyslogJsonAuditLogPublisherRequest) Get() *AddSyslogJsonAuditLogPublisherRequest {
	return v.value
}

func (v *NullableAddSyslogJsonAuditLogPublisherRequest) Set(val *AddSyslogJsonAuditLogPublisherRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddSyslogJsonAuditLogPublisherRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddSyslogJsonAuditLogPublisherRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddSyslogJsonAuditLogPublisherRequest(val *AddSyslogJsonAuditLogPublisherRequest) *NullableAddSyslogJsonAuditLogPublisherRequest {
	return &NullableAddSyslogJsonAuditLogPublisherRequest{value: val, isSet: true}
}

func (v NullableAddSyslogJsonAuditLogPublisherRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddSyslogJsonAuditLogPublisherRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


