/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EnumsizeLimitLogRetentionPolicySchemaUrn the model 'EnumsizeLimitLogRetentionPolicySchemaUrn'
type EnumsizeLimitLogRetentionPolicySchemaUrn string

// List of Enumsize-limit-log-retention-policySchemaUrn
const (
	ENUMSIZELIMITLOGRETENTIONPOLICYSCHEMAURN_URNPINGIDENTITYSCHEMASCONFIGURATION2_0LOG_RETENTION_POLICYSIZE_LIMIT EnumsizeLimitLogRetentionPolicySchemaUrn = "urn:pingidentity:schemas:configuration:2.0:log-retention-policy:size-limit"
)

// All allowed values of EnumsizeLimitLogRetentionPolicySchemaUrn enum
var AllowedEnumsizeLimitLogRetentionPolicySchemaUrnEnumValues = []EnumsizeLimitLogRetentionPolicySchemaUrn{
	"urn:pingidentity:schemas:configuration:2.0:log-retention-policy:size-limit",
}

func (v *EnumsizeLimitLogRetentionPolicySchemaUrn) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumsizeLimitLogRetentionPolicySchemaUrn(value)
	for _, existing := range AllowedEnumsizeLimitLogRetentionPolicySchemaUrnEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumsizeLimitLogRetentionPolicySchemaUrn", value)
}

// NewEnumsizeLimitLogRetentionPolicySchemaUrnFromValue returns a pointer to a valid EnumsizeLimitLogRetentionPolicySchemaUrn
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumsizeLimitLogRetentionPolicySchemaUrnFromValue(v string) (*EnumsizeLimitLogRetentionPolicySchemaUrn, error) {
	ev := EnumsizeLimitLogRetentionPolicySchemaUrn(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumsizeLimitLogRetentionPolicySchemaUrn: valid values are %v", v, AllowedEnumsizeLimitLogRetentionPolicySchemaUrnEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumsizeLimitLogRetentionPolicySchemaUrn) IsValid() bool {
	for _, existing := range AllowedEnumsizeLimitLogRetentionPolicySchemaUrnEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Enumsize-limit-log-retention-policySchemaUrn value
func (v EnumsizeLimitLogRetentionPolicySchemaUrn) Ptr() *EnumsizeLimitLogRetentionPolicySchemaUrn {
	return &v
}

type NullableEnumsizeLimitLogRetentionPolicySchemaUrn struct {
	value *EnumsizeLimitLogRetentionPolicySchemaUrn
	isSet bool
}

func (v NullableEnumsizeLimitLogRetentionPolicySchemaUrn) Get() *EnumsizeLimitLogRetentionPolicySchemaUrn {
	return v.value
}

func (v *NullableEnumsizeLimitLogRetentionPolicySchemaUrn) Set(val *EnumsizeLimitLogRetentionPolicySchemaUrn) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumsizeLimitLogRetentionPolicySchemaUrn) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumsizeLimitLogRetentionPolicySchemaUrn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumsizeLimitLogRetentionPolicySchemaUrn(val *EnumsizeLimitLogRetentionPolicySchemaUrn) *NullableEnumsizeLimitLogRetentionPolicySchemaUrn {
	return &NullableEnumsizeLimitLogRetentionPolicySchemaUrn{value: val, isSet: true}
}

func (v NullableEnumsizeLimitLogRetentionPolicySchemaUrn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumsizeLimitLogRetentionPolicySchemaUrn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
